FROM difi/integrasjonspunkt:development
COPY integrasjonspunkt-local.properties /opt/integrasjonspunkt
COPY bootstrap.properties /opt/integrasjonspunkt
COPY mock-truststore.jks /opt/integrasjonspunkt
COPY kontaktinfo-client.pem /opt/integrasjonspunkt
COPY mock.jks /opt/integrasjonspunkt






