upstream kwlocation {
  server kuberneteswrapper:3000;
}

upstream lhci {
  server lhci-server.lhci:9001;
}

upstream observability_proxy {
  server observability-proxy.observability.svc.cluster.local;
}
