location /kuberneteswrapper/ {
  proxy_pass          http://kwlocation/;
}

location /sse {
  proxy_pass          http://mcp/sse;
  proxy_http_version  1.1;
  proxy_buffering     off;
  proxy_cache         off;
  proxy_read_timeout  86400;
  chunked_transfer_encoding off;
}

location /messages {
  proxy_pass          http://mcp/messages;
  proxy_http_version  1.1;
  proxy_buffering     off;
  proxy_cache         off;
}
