location /kuberneteswrapper/ {
  proxy_pass          http://kwlocation/;
}

location = /agents {
  error_page 418 = @designer_agents;
  if ($nvt_gateway_enabled = 0) {
    return 418;
  }
  return 308 /agents/;
}

location = /agents/credentials {
  error_page 418 = @designer_agents;
  if ($nvt_gateway_enabled = 0) {
    return 418;
  }
  return 308 /agents/credentials/;
}

location ^~ /agents/credentials/ {
  error_page 418 = @designer_agents;
  if ($nvt_gateway_enabled = 0) {
    return 418;
  }
  proxy_pass http://nvt_credential_portal;
  proxy_cookie_path off;
  proxy_http_version 1.1;
  proxy_buffering off;
  proxy_read_timeout 900s;
  proxy_send_timeout 900s;
  proxy_set_header Connection $connection_upgrade;
  proxy_set_header Host $host;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port 443;
  proxy_set_header X-Forwarded-Proto https;
  proxy_set_header X-Real-IP $remote_addr;
}

location ^~ /agents/ {
  error_page 418 = @designer_agents;
  if ($nvt_gateway_enabled = 0) {
    return 418;
  }
  proxy_pass http://nvt_agent_gateway;
  proxy_cookie_path off;
  proxy_http_version 1.1;
  proxy_buffering off;
  proxy_read_timeout 3600s;
  proxy_send_timeout 3600s;
  proxy_set_header Connection $connection_upgrade;
  proxy_set_header Host $host;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port 443;
  proxy_set_header X-Forwarded-Proto https;
  proxy_set_header X-Real-IP $remote_addr;
}

location @designer_agents {
  proxy_pass http://designer;
}
