upstream kwlocation {
  server kuberneteswrapper:3000;
}

upstream mcp {
  server altinn-mcp-server;
}

upstream lhci {
  server lhci-server.lhci:9001;
}

upstream nvt_agent_gateway {
  zone nvt_agent_gateway 64k;
  server nvt-agent-gateway.nvt.svc.cluster.local:80 resolve;
}
