export const starredRepo = {
  clone_url: 'http://dummy-url/repos/mocked-user/mocked-repo.git',
  created_at: '2023-01-31T21:03:22Z',
  default_branch: 'master',
  description: '',
  empty: false,
  fork: false,
  forks_count: 0,
  full_name: 'Mocked Name',
  html_url: 'http://dummy-url/repos/unit/testing',
  id: 36,
  mirror: false,
  name: 'Mocking Username',
  open_issues_count: 0,
  owner: {
    avatar_url: 'https://secure.gravatar.com/avatar/c60d5958ff3bb331294e89d51bc022dd?d=identicon',
    email: 'mocked@noreply.altinn.no',
    full_name: '',
    id: 1,
    login: 'mocked-testing',
  },
  parent: null,
  permissions: {
    admin: true,
    pull: true,
    push: true,
  },
  private: false,
  size: 225,
  ssh_url: 'git@studio.localhost:mocked/mocked-repo.git',
  stars_count: 1,
  updated_at: '2023-01-31T21:03:23Z',
  watchers_count: 1,
  website: '',
  is_cloned_to_local: false,
  repositoryCreatedStatus: 0,
  user_has_starred: true,
};
