using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using AltinnCore.Common.Factories.ModelFactory;
using AltinnCore.Common.Services.Interfaces;
using AltinnCore.ServiceLibrary.ServiceMetadata;
using Manatee.Json;
using Manatee.Json.Schema;
using Manatee.Json.Serialization;
using Moq;
using Xunit;

namespace AltinnCore.UnitTest.Common
{
    /// <summary>
    /// Tests converting Json Schema to XSD
    /// </summary>
    public class SeresXsdParserTest
    {
        /// <summary>
        /// Converting edag Json Schema to XSD
        /// </summary>
        [Fact]
        public void ConvertJsonSchemaToXsd()
        {
            var schemaText = File.ReadAllText("Common/edag.schema.json");
            var schemaJson = JsonValue.Parse(schemaText);
            var schema = new JsonSerializer().Deserialize<JsonSchema>(schemaJson);       

            JsonSchemaToXsd converter = new JsonSchemaToXsd();

            XmlSchema xmlSchema = converter.CreateXsd(schema);

            FileStream file = new FileStream("edag.generated.xsd", FileMode.Create, FileAccess.ReadWrite);
            XmlTextWriter xwriter = new XmlTextWriter(file, new UTF8Encoding());
            xwriter.Formatting = Formatting.Indented;
            xmlSchema.Write(xwriter);
        }

        /// <summary>
        ///   convert from json schema which is autogenerated with xsdToJsonSchema parser
        /// </summary>
        [Fact]
        public void ConvertFromAutogeneratedJsonSchemaToXsd()
        {
            var schemaText = File.ReadAllText("Common/edag.melding.schema.json");
            var schemaJson = JsonValue.Parse(schemaText);
            var schema = new JsonSerializer().Deserialize<JsonSchema>(schemaJson);

            JsonSchemaToXsd converter = new JsonSchemaToXsd();
            XmlSchema xmlSchema = converter.CreateXsd(schema);

            FileStream file = new FileStream("edag.melding.generated.xsd", FileMode.Create, FileAccess.ReadWrite);
            XmlTextWriter xwriter = new XmlTextWriter(file, new UTF8Encoding());
            xwriter.Formatting = Formatting.Indented;
            xmlSchema.Write(xwriter);
        }

        /// <summary>
        ///  convert a recursive json schema
        /// </summary>
        [Fact]
        public void ConvertRecursiveSchemaJsonMetadata()
        {
            Mock<IRepository> moqRepository = new Mock<IRepository>();
            var seresParser = new SeresXsdParser(moqRepository.Object);
            XDocument mainXsd = XDocument.Load("Common/schema-w-recursion.xsd");
          
            ServiceMetadata serviceMetadata = seresParser.ParseXsdToServiceMetadata("123", "service", mainXsd, null);

            string metadataAsJson = Newtonsoft.Json.JsonConvert.SerializeObject(serviceMetadata);

            File.WriteAllText("metadata-recursive.json", metadataAsJson);

            JsonMetadataParser metadataParser = new JsonMetadataParser();
            string classMeta = metadataParser.CreateModelFromMetadata(serviceMetadata);

            File.WriteAllText("classdata-recursive.json", classMeta);           
        }

        /// <summary>
        ///   convert edagschema to json metadata and c#
        /// </summary>
        [Fact]
        public void ConvertExistingEdagSchemaToJsonMetadataAndCsharp()
        {
            Mock<IRepository> moqRepository = new Mock<IRepository>(); 
            var seresParser = new SeresXsdParser(moqRepository.Object);
            XDocument mainXsd = XDocument.Load("Common/schema.xsd");

            ServiceMetadata serviceMetadata = seresParser.ParseXsdToServiceMetadata("123", "service", mainXsd, null);

            string metadataAsJson = Newtonsoft.Json.JsonConvert.SerializeObject(serviceMetadata);

            File.WriteAllText("edag.original.metadata.json", metadataAsJson);

            JsonMetadataParser metadataParser = new JsonMetadataParser();
            string classMeta = metadataParser.CreateModelFromMetadata(serviceMetadata);

            File.WriteAllText("edag.original.csharp.cs", classMeta);
        }
    }
}
