apiVersion: apps/v1
kind: Deployment
metadata:
  name: altinn-mcp-server
  annotations:
    altinn.studio/image: altinn-mcp-server:latest
    altinn.studio/image-tag: latest
  labels:
    release: altinn-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altinn-mcp-server
  template:
    metadata:
      labels:
        app: altinn-mcp-server
    spec:
      serviceAccountName: altinn-mcp-server-sa
      containers:
        - name: altinn-mcp-server
          image: altinn-mcp-server:latest
          ports:
            - containerPort: 8070
              name: http
              protocol: TCP
          env:
            - name: AZURE_ENDPOINT
              value: "https://rndlabaidemoss0618689180.openai.azure.com/"
            - name: GITEA_URL
              value: "http://altinn-repositories-public"
            - name: AZURE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: altinn-mcp-server-secret
                  key: AZURE_API_KEY
            - name: MCP_ROOT_PATH
              value: "/mcp"
