const moduleName = 'TEXT_RESOURCES';

export const FETCH_TEXT_RESOURCES = `${moduleName}.FETCH_TEXT_RESOURCES`;
export const FETCH_TEXT_RESOURCES_FULFILLED = `${moduleName}.FETCH_TEXT_RESOURCES_FULFILLED`;
export const FETCH_TEXT_RESOURCES_REJECTED = `${moduleName}.FETCH_TEXT_RESOURCES_REJECTED`;
