export enum QueryKey {
  AppDeployments = 'APP_DEPLOYMENTS',
  AppReleases = 'APP_RELEASES',
  BranchStatus = 'BRANCH_STATUS',
  CurrentUser = 'CURRENT_USER',
  DatamodelsXsd = 'DATAMODELS_XSD',
  DeployPermissions = 'DEPLOY_PERMISSIONS',
  Environments = 'ENVIRONMENTS',
  OrgList = 'ORG_LIST',
  RepoMetaData = 'REPO_METADATA',
  RepoPullData = 'REPO_PULL_DATA',
  RepoStatus = 'REPO_STATUS',
  TextLanguages = 'TEXT_LANGUAGES',
  TextResources = 'TEXT_RESOURCES',
}
