POST /api/v1/ttd-e2e-tests/workflows HTTP/1.1
Idempotency-Key: idem-Guid_1
Content-Type: application/json; charset=utf-8

{
  "labels": {
    "org": "ttd",
    "app": "e2e-tests"
  },
  "context": null,
  "workflows": [
    {
      "ref": "wf-a",
      "operationId": "op-wf-a",
      "steps": [
        {
          "operationId": "/ping-a",
          "command": {
            "type": "webhook",
            "maxExecutionTime": null,
            "data": {
              "uri": "http://localhost:{PORT}/ping-a",
              "payload": null,
              "contentType": null
            }
          },
          "retryStrategy": null,
          "labels": null
        }
      ],
      "startAt": null,
      "state": null,
      "dependsOn": null,
      "links": null,
      "dependsOnHeads": true,
      "isHead": null
    },
    {
      "ref": "wf-b",
      "operationId": "op-wf-b",
      "steps": [
        {
          "operationId": "/ping-b",
          "command": {
            "type": "webhook",
            "maxExecutionTime": null,
            "data": {
              "uri": "http://localhost:{PORT}/ping-b",
              "payload": null,
              "contentType": null
            }
          },
          "retryStrategy": null,
          "labels": null
        }
      ],
      "startAt": null,
      "state": null,
      "dependsOn": [
        "wf-a"
      ],
      "links": null,
      "dependsOnHeads": true,
      "isHead": null
    },
    {
      "ref": "wf-c",
      "operationId": "op-wf-c",
      "steps": [
        {
          "operationId": "/ping-c",
          "command": {
            "type": "webhook",
            "maxExecutionTime": null,
            "data": {
              "uri": "http://localhost:{PORT}/ping-c",
              "payload": null,
              "contentType": null
            }
          },
          "retryStrategy": null,
          "labels": null
        }
      ],
      "startAt": null,
      "state": null,
      "dependsOn": [
        "wf-a",
        "wf-b"
      ],
      "links": null,
      "dependsOnHeads": true,
      "isHead": null
    }
  ]
}

