import { Repository } from 'app-shared/types/Repository';

export const repositoryMock: Repository = {
  clone_url: '',
  created_at: '',
  default_branch: 'test',
  description: '',
  empty: false,
  fork: false,
  forks_count: 0,
  full_name: 'app',
  html_url: '',
  id: 0,
  is_cloned_to_local: false,
  mirror: false,
  name: 'test',
  open_issues_count: 0,
  owner: {
    avatar_url: '',
    email: '',
    full_name: 'Testdepartementet',
    id: 1,
    login: 'org',
    UserType: 0,
  },
  permissions: {
    admin: true,
    pull: true,
    push: true,
  },
  private: false,
  repositoryCreatedStatus: 0,
  size: 1,
  ssh_url: '',
  stars_count: 0,
  updated_at: '',
  watchers_count: 0,
  website: '',
};

export const privateRepositoryMock: Repository = {
  clone_url: '',
  created_at: '',
  default_branch: 'test',
  description: '',
  empty: false,
  fork: false,
  forks_count: 0,
  full_name: 'privateApp',
  html_url: '',
  id: 1,
  is_cloned_to_local: false,
  mirror: false,
  name: 'privateApp',
  open_issues_count: 0,
  owner: {
    avatar_url: '',
    email: 'tester@tester.test',
    full_name: 'Tester Testersen',
    id: 3,
    login: 'tester',
    UserType: 0,
  },
  permissions: {
    admin: true,
    pull: true,
    push: true,
  },
  private: false,
  repositoryCreatedStatus: 0,
  size: 1,
  ssh_url: '',
  stars_count: 0,
  updated_at: '',
  watchers_count: 0,
  website: '',
};
