using System;
using System.Xml.Serialization;

namespace Altinn.Common.EFormidlingClient.Models
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Arkivmelding"/> class. This class represents the actual arkivmelding.
    /// This class i autogenerated. XSD definition: https://github.com/difi/felleslosninger/blob/gh-pages/resources/arkivmelding/arkivmelding.xsd
    /// </summary>
    /// 
    [XmlRoot(ElementName = "arkivmelding")]
    public class Arkivmelding
    {
        /// <summary>
        ///  Gets or sets the System
        /// </summary>
        [XmlElement(ElementName = "system")]
        public string System { get; set; }

        /// <summary>
        ///  Gets or sets the MeldingId
        /// </summary>
        [XmlElement(ElementName = "meldingId")]
        public string MeldingId { get; set; }

        /// <summary>
        ///  Gets or sets the Tidspunkt
        /// </summary>
        [XmlElement(ElementName = "tidspunkt")]
        public DateTime Tidspunkt { get; set; }

        /// <summary>
        ///  Gets or sets the AntallFiler
        /// </summary>
        [XmlElement(ElementName = "antallFiler")]
        public int AntallFiler { get; set; }

        /// <summary>
        ///  Gets or sets the Basisregistrering
        /// </summary>
        [XmlElement(ElementName = "basisregistrering")]
        public Basisregistrering Basisregistrering { get; set; }

        /// <summary>
        ///  Gets or sets the Xmlns
        /// </summary>
        [XmlAttribute(AttributeName = "xmlns")]
        public string Xmlns { get; set; }

        /// <summary>
        ///  Gets or sets the Xsi
        /// </summary>
        [XmlAttribute(AttributeName = "xsi")]
        public string Xsi { get; set; }

        /// <summary>
        ///  Gets or sets the SchemaLocation
        /// </summary>
        [XmlAttribute(AttributeName = "schemaLocation")]
        public string SchemaLocation { get; set; }

        /// <summary>
        ///  Gets or sets the Text
        /// </summary>
        [XmlText]
        public string Text { get; set; }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Dokumentobjekt"/> class.
    /// </summary>
    [XmlRoot(ElementName = "dokumentobjekt")]
    public class Dokumentobjekt
    {
        /// <summary>
        ///  Gets or sets the Versjonsnummer
        /// </summary>
        [XmlElement(ElementName = "versjonsnummer")]
        public int Versjonsnummer { get; set; }

        /// <summary>
        ///  Gets or sets the Variantformat
        /// </summary>
        [XmlElement(ElementName = "variantformat")]
        public string Variantformat { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetDato
        /// </summary>
        [XmlElement(ElementName = "opprettetDato")]
        public DateTime OpprettetDato { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetAv
        /// </summary>
        [XmlElement(ElementName = "opprettetAv")]
        public string OpprettetAv { get; set; }

        /// <summary>
        ///  Gets or sets the ReferanseDokumentfil
        /// </summary>
        [XmlElement(ElementName = "referanseDokumentfil")]
        public string ReferanseDokumentfil { get; set; }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Dokumentbeskrivelse"/> class.
    /// </summary>
    [XmlRoot(ElementName = "dokumentbeskrivelse")]
    public class Dokumentbeskrivelse
    {
        /// <summary>
        ///  Gets or sets the SystemID
        /// </summary>
        [XmlElement(ElementName = "systemID")]
        public string SystemID { get; set; }

        /// <summary>
        ///  Gets or sets the Dokumenttype
        /// </summary>
        [XmlElement(ElementName = "dokumenttype")]
        public string Dokumenttype { get; set; }

        /// <summary>
        ///  Gets or sets the Dokumentstatus
        /// </summary>
        [XmlElement(ElementName = "dokumentstatus")]
        public string Dokumentstatus { get; set; }

        /// <summary>
        ///  Gets or sets the Tittel
        /// </summary>
        [XmlElement(ElementName = "tittel")]
        public string Tittel { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetDato
        /// </summary>
        [XmlElement(ElementName = "opprettetDato")]
        public DateTime OpprettetDato { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetAv
        /// </summary>
        [XmlElement(ElementName = "opprettetAv")]
        public string OpprettetAv { get; set; }

        /// <summary>
        ///  Gets or sets the TilknyttetRegistreringSom
        /// </summary>
        [XmlElement(ElementName = "tilknyttetRegistreringSom")]
        public string TilknyttetRegistreringSom { get; set; }

        /// <summary>
        ///  Gets or sets the Dokumentnummer
        /// </summary>
        [XmlElement(ElementName = "dokumentnummer")]
        public int Dokumentnummer { get; set; }

        /// <summary>
        ///  Gets or sets the TilknyttetDato
        /// </summary>
        [XmlElement(ElementName = "tilknyttetDato")]
        public DateTime TilknyttetDato { get; set; }

        /// <summary>
        ///  Gets or sets the TilknyttetAv
        /// </summary>
        [XmlElement(ElementName = "tilknyttetAv")]
        public string TilknyttetAv { get; set; }

        /// <summary>
        ///  Gets or sets the Dokumentobjekt
        /// </summary>
        [XmlElement(ElementName = "dokumentobjekt")]
        public Dokumentobjekt Dokumentobjekt { get; set; }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Korrespondansepart"/> class.
    /// </summary>
    [XmlRoot(ElementName = "korrespondansepart")]
    public class Korrespondansepart
    {
        /// <summary>
        ///  Gets or sets the Korrespondanseparttype
        /// </summary>
        [XmlElement(ElementName = "korrespondanseparttype")]
        public string Korrespondanseparttype { get; set; }

        /// <summary>
        ///  Gets or sets the KorrespondansepartNavn
        /// </summary>
        [XmlElement(ElementName = "korrespondansepartNavn")]
        public string KorrespondansepartNavn { get; set; }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Basisregistrering"/> class.
    /// </summary>
    [XmlRoot(ElementName = "basisregistrering")]
    public class Basisregistrering
    {
        /// <summary>
        ///  Gets or sets the SystemID
        /// </summary>
        [XmlElement(ElementName = "systemID")]
        public string SystemID { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetDato
        /// </summary>
        [XmlElement(ElementName = "opprettetDato")]
        public DateTime OpprettetDato { get; set; }

        /// <summary>
        ///  Gets or sets the OpprettetAv
        /// </summary>
        [XmlElement(ElementName = "opprettetAv")]
        public string OpprettetAv { get; set; }

        /// <summary>
        ///  Gets or sets the ArkivertDato
        /// </summary>
        [XmlElement(ElementName = "arkivertDato")]
        public DateTime ArkivertDato { get; set; }

        /// <summary>
        ///  Gets or sets the ArkivertAv
        /// </summary>
        [XmlElement(ElementName = "arkivertAv")]
        public string ArkivertAv { get; set; }

        /// <summary>
        ///  Gets or sets the ReferanseForelderMappe
        /// </summary>
        [XmlElement(ElementName = "referanseForelderMappe")]
        public string ReferanseForelderMappe { get; set; }

        /// <summary>
        ///  Gets or sets the Dokumentbeskrivelse
        /// </summary>
        [XmlElement(ElementName = "dokumentbeskrivelse")]
        public Dokumentbeskrivelse Dokumentbeskrivelse { get; set; }

        /// <summary>
        ///  Gets or sets the Tittel
        /// </summary>
        [XmlElement(ElementName = "tittel")]
        public string Tittel { get; set; }

        /// <summary>
        ///  Gets or sets the OffentligTittel
        /// </summary>
        [XmlElement(ElementName = "offentligTittel")]
        public string OffentligTittel { get; set; }

        /// <summary>
        ///  Gets or sets the Journalposttype
        /// </summary>
        [XmlElement(ElementName = "journalposttype")]
        public string Journalposttype { get; set; }

        /// <summary>
        ///  Gets or sets the Journalstatus
        /// </summary>
        [XmlElement(ElementName = "journalstatus")]
        public string Journalstatus { get; set; }

        /// <summary>
        ///  Gets or sets the Journaldato
        /// </summary>
        [XmlElement(ElementName = "journaldato")]
        public DateTime Journaldato { get; set; }

        /// <summary>
        ///  Gets or sets the Korrespondansepart
        /// </summary>
        [XmlElement(ElementName = "korrespondansepart")]
        public Korrespondansepart Korrespondansepart { get; set; }

        /// <summary>
        ///  Gets or sets the Type
        /// </summary>
        [XmlAttribute(AttributeName = "type")]
        public string Type { get; set; }

        /// <summary>
        ///  Gets or sets the Text
        /// </summary>
        [XmlText]
        public string Text { get; set; }
    }
}
