import { PrefillSource } from 'app-shared/types/PrefillConfig';

/**
 * The known field names for each prefill source, as defined by the prefill JSON schema:
 * https://github.com/Altinn/altinn-cdn/blob/master/schemas/json/prefill/prefill.schema.v1.json
 *
 * QueryParameters is excluded since its keys are user-defined query parameter names rather than
 * a fixed set of fields.
 */
export const PREFILL_SOURCE_FIELDS: Record<
  Exclude<PrefillSource, PrefillSource.QueryParameters>,
  string[]
> = {
  [PrefillSource.ER]: [
    'OrgNumber',
    'Name',
    'UnitType',
    'TelephoneNumber',
    'MobileNumber',
    'FaxNumber',
    'EMailAddress',
    'InternetAddress',
    'MailingAddress',
    'MailingPostalCode',
    'MailingPostalCity',
    'BusinessAddress',
    'BusinessPostalCode',
    'BusinessPostalCity',
  ],
  [PrefillSource.DSF]: [
    'SSN',
    'Name',
    'FirstName',
    'MiddleName',
    'LastName',
    'TelephoneNumber',
    'MobileNumber',
    'MailingAddress',
    'MailingPostalCode',
    'MailingPostalCity',
    'AddressMunicipalNumber',
    'AddressMunicipalName',
    'AddressStreetName',
    'AddressHouseNumber',
    'AddressHouseLetter',
    'AddressPostalCode',
    'AddressCity',
  ],
  [PrefillSource.UserProfile]: [
    'UserId',
    'UserName',
    'PhoneNumber',
    'Email',
    'PartyId',
    'UserType',
    'ProfileSettingPreference.Language',
    'ProfileSettingPreference.PreSelectedPartyId',
    'ProfileSettingsPreference.DoNotPromptForParty',
    'Party.PartyId',
    'Party.PartyUuid',
    'Party.ExternalUrn',
    'Party.PartyTypeName',
    'Party.OrgNumber',
    'Party.SSN',
    'Party.UnitType',
    'Party.Name',
    'Party.isDeleted',
    'Party.OnlyHierarchyElementWithNoAccess',
    'Party.Person.SSN',
    'Party.Person.Name',
    'Party.Person.FirstName',
    'Party.Person.MiddleName',
    'Party.Person.LastName',
    'Party.Person.TelephoneNumber',
    'Party.Person.MobileNumber',
    'Party.Person.MailingAddress',
    'Party.Person.MailingPostalCode',
    'Party.Person.MailingPostalCity',
    'Party.Person.AddressMunicipalNumber',
    'Party.Person.AddressMunicipalName',
    'Party.Person.AddressStreetName',
    'Party.Person.AddressHouseNumber',
    'Party.Person.AddressHouseLetter',
    'Party.Person.AddressPostalCode',
    'Party.Person.AddressCity',
    'Party.Organization.OrgNumber',
    'Party.Organization.Name',
    'Party.Organization.UnitType',
    'Party.Organization.TelephoneNumber',
    'Party.Organization.MobileNumber',
    'Party.Organization.FaxNumber',
    'Party.Organization.EMailAddress',
    'Party.Organization.InternetAddress',
    'Party.Organization.MailingAddress',
    'Party.Organization.MailingPostalCode',
    'Party.Organization.MailingPostalCity',
    'Party.Organization.BusinessAddress',
    'Party.Organization.BusinessPostalCode',
    'Party.Organization.BusinessPostalCity',
  ],
};
