
const fallbackLanguage = {
  general: {
    action: 'Action',
    add: 'Add',
    add_connection: 'Add connection',
    cancel: 'Cancel',
    choose: 'Choose',
    choose_label: 'Choose label',
    choose_method: 'Choose method',
    control_submit: 'Control and submit',
    create: 'Create',
    create_new: 'Create new',
    delete: 'Delete',
    disabled: 'Disabled',
    enabled: 'Enabled',
    label: 'Label',
    no_options: 'No options available',
    required: 'Required',
    save: 'Save',
    search: 'Search',
    select_field: 'Select field',
    submit: 'Submit',
    value: 'Value',
  },
  ux_editor: {
    api_connection_header: 'Api connections',
    conditional_rendering_connection_header: 'Conditional Rendering Connections',
    form_designer: 'Form designer',
    formfiller_placeholder_user: 'OLA PRIVATPERSON',
    modal_configure_address_component_simplified: 'Simplified',
    modal_configure_api_code_list: 'Code list',
    modal_configure_api_extermnal_api: 'External API',
    modal_configure_api_header: 'Configure API connection',
    modal_configure_conditional_rendering_configure_add_new_field_mapping: 'Add new field mapping',
    modal_configure_conditional_rendering_configure_input_data_model_helper: 'Choose field from the data model',
    modal_configure_conditional_rendering_configure_input_header: 'Configure input parameters',
    modal_configure_conditional_rendering_configure_input_param_helper: 'Input param name',
    modal_configure_conditional_rendering_configure_output_action_helper: 'Select action',
    modal_configure_conditional_rendering_configure_output_field_helper:
      'that should be performed on the following fields if method returns true',
    modal_configure_conditional_rendering_configure_output_header: 'Configure output and action',
    modal_configure_conditional_rendering_header: 'Configure conditional rendering rule',
    modal_configure_conditional_rendering_helper: 'Conditional rendering rule',
    modal_configure_rules_configure_input_data_model_helper: 'Choose field from the data model',
    modal_configure_rules_configure_input_header: 'Configure input parameters',
    modal_configure_rules_configure_input_param_helper: 'Input param name',
    modal_configure_rules_configure_output_header: 'Configure output parameters',
    modal_configure_rules_configure_output_param_helper: 'Out param name',
    modal_configure_rules_header: 'Configure rules',
    modal_configure_rules_helper: 'Rule',
    modal_data_model_helper: 'Select field in data model',
    modal_data_model_input: 'Select field',
    modal_header_type_h2: 'Section title (H2)',
    modal_header_type_h3: 'Subtitle (H3)',
    modal_header_type_h4: 'Subtitle (H4)',
    modal_header_type_helper: 'Select title type',
    modal_new_option: 'Add new option',
    modal_options: 'Options',
    modal_properties_data_model_helper: 'Link to data model',
    modal_properties_description_helper: 'Write or search for description',
    modal_properties_tag_helper: 'Write or search for tag description',
    modal_properties_header_helper: 'Write a title or search',
    modal_properties_label_helper: 'Write or search for label',
    modal_properties_paragraph_helper: 'Search for paragraph text',
    modal_properties_paragraph_edit_helper: 'Or write paragraph text',
    modal_properties_header: 'Edit properties',
    modal_restrictions: 'Restrictions from data model',
    modal_restrictions_empty: 'No restrictions to show',
    modal_restrictions_helper: 'Please select a field in the data model',
    modal_text: 'Text',
    modal_text_input: 'Choose text',
    modal_text_key: 'Text key',
    repeating: 'Repeating',
    repeating_group_add: 'Add group',
    repeating_group_delete: 'Delete group',
    rule_connection_header: 'Rule Connections',
    toolbar_add_container: 'Add container',
    toolbar_header: 'Header',
    toolbar_file_upload: 'File Upload',
  },
  form_filler: {
    error_report_header: 'Det er et problem',
  }
};

export default fallbackLanguage;
