chartVersion: ""
releaseName: ""
imageTag: ""

github:
  owner: "Altinn"
  repository: "altinn-studio"
  runnerScope: "repo"
  runnerLabels: "self-hosted,linux,x64,altinn-studio"
  scalerLabels: "altinn-studio"
  appId: ""
  installationId: ""
  runnerGroup: "Default"

auth:
  secretName: "github-runner-auth"
  appPrivateKeyKey: "appPrivateKey"

runtimeClassName: "kata-vm-isolation"
dockerInDocker:
  enabled: true
  diskSize: "30G"
shareWorkspace:
  enabled: true
  sizeLimit: "20Gi"

maxConcurrentRunners: 16

resources:
  requests:
    cpu: "4"
    memory: 8Gi
    ephemeral-storage: 45Gi
  limits:
    cpu: "4"
    memory: 8Gi
    ephemeral-storage: 60Gi
