# .github/release.yml

changelog:
  exclude:
    labels:
      - skip-releasenotes
      - area/resource-registry
  categories:
    - title: Forms editor 🛠
      labels:
        - area/ui-editor
      exclude:
        labels:
          - kind/bug
    - title: Dashboard 🖥
      labels:
        - area/dashboard
      exclude:
        labels:
          - kind/bug
    - title: Text editor 💬
      labels:
        - area/text-editor
      exclude:
        labels:
          - kind/bug
    - title: Process editor ⏺→◻️→⏺
      labels:
        - area/process
      exclude:
        labels:
          - kind/bug
    - title: Data modeling 📈
      labels:
        - area/data-modeling
      exclude:
        labels:
          - kind/bug
    - title: Bugfixes 🐞
      labels:
        - kind/bug
    - title: Dependency Upgrades 📦
      labels:
        - kind/dependencies
    - title: Other Changes
      labels:
        - "*"
