apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.keda.authenticationRef.name }}
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: appKey
      name: {{ .Values.auth.secretName }}
      key: {{ .Values.auth.appPrivateKeyKey }}
