include:
  - ../workflow-engine/docker-compose.yaml

services:
  workflow-engine:
    build:
      context: ../../
      dockerfile: Runtime/workflow-engine-app/Dockerfile
    container_name: workflow-engine-app
    restart: unless-stopped
    networks:
      - workflow-engine-network
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [app, full]
