# base image
FROM gitea/gitea:1.7

# copy configuration file
# Has to be copied to the templates-folder so parsing of environment variables is correct
COPY giteaConf/prod/app.ini etc/templates/app.ini

# Copy rest of configuration
COPY src/AltinnRepositories/gitea-data/gitea/options data/gitea/options/
COPY src/AltinnRepositories/gitea-data/gitea/public/img data/gitea/public/img
COPY src/AltinnRepositories/gitea-data/gitea/templates data/gitea/templates
