# base image
FROM gitea/gitea:1.7

# copy configuration file
COPY src/AltinnRepositories/gitea-data/gitea/ data/gitea
#COPY src/AltinnRepositories/gitea-data/gitea/options data/gitea/options/
#COPY src/AltinnRepositories/gitea-data/gitea/public/img data/gitea/public/img
#COPY src/AltinnRepositories/gitea-data/gitea/templates data/gitea/templates
