apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - secret.yaml
patches:
  # Set local image and pull policy
  - target:
      kind: Deployment
      name: workflow-engine-app
    patch: |-
      - op: replace
        path: /metadata/annotations/altinn.studio~1image
        value: "localhost:5001/workflow-engine-app:latest"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "localhost:5001/workflow-engine-app:latest"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
      - op: replace
        path: /spec/replicas
        value: 1
  # Delete PDB for local (single replica)
  - patch: |-
      $patch: delete
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: workflow-engine-app-pdb
