apiVersion: v1
kind: Secret
metadata:
  name: workflow-engine-app-secrets
type: Opaque
stringData:
  secrets.json: |
    {
      "ConnectionStrings": {
        "WorkflowEngine": "Host=postgres;Port=5432;Database=workflow_engine;Username=postgres;Password=postgres123"
      },
      "AppCommandSettings": {
        "ApiKey": "local-test-api-key",
        "CommandEndpoint": "http://wiremock:6060/{Org}/{App}/instances/{InstanceOwnerPartyId}/{InstanceGuid}/workflow-engine-callbacks"
      }
    }
