apiVersion: v1
kind: ServiceAccount
metadata:
  name: dis-tls-cert-kv-uami
  namespace: default
  annotations:
    azure.workload.identity/client-id: ${ESO_DIS_TLS_CERT_CLIENT_ID}
    azure.workload.identity/tenant-id: ${TENANT_ID}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dis-tls-cert-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${DIS_TLS_CERT_KV_URI}
      serviceAccountRef:
        name: dis-tls-cert-kv-uami
        namespace: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssl-key-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dis-tls-cert-store
  target:
    name: ssl-key-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      data:
        star.altinn.studio.cert: "{{ .crt }}"
        star.altinn.studio.key: "{{ .key }}"
      type: Opaque
  data:
    - secretKey: crt
      remoteRef:
        key: ${DIS_TLS_CERT_SECRET_NAME_CRT}
    - secretKey: key
      remoteRef:
        key: ${DIS_TLS_CERT_SECRET_NAME_KEY}
