ARG COORDINATOR_IMAGE
FROM ${COORDINATOR_IMAGE} AS tools

FROM ubuntu:24.04@sha256:224a1869083a311ef3f13648a154ba79832fbef6364d31493642ca03082da254

RUN apt-get update \
    && apt-get install --yes --no-install-recommends libcap-ng0 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=tools \
  /usr/local/bin/sandbox-image \
  /usr/local/bin/sandbox-image
COPY prepared-image /opt/altinn/prepared-image

ENTRYPOINT ["/usr/local/bin/sandbox-image", "import"]
