ARG COORDINATOR_IMAGE
FROM ${COORDINATOR_IMAGE} AS tools

FROM ubuntu:24.04@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517

RUN apt-get update \
    && apt-get install --yes --no-install-recommends libcap-ng0 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=tools \
  /usr/local/bin/sandbox-image \
  /usr/local/bin/sandbox-image
COPY prepared-image /opt/altinn/prepared-image

ENTRYPOINT ["/usr/local/bin/sandbox-image", "import"]
