{
 "title": "Altinn Studio Runtime / PDF3",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statuses",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(outbound_http_route_backend_response_statuses_total{backend_namespace=~\"pdf|runtime-pdf3\"}[$__rate_interval])) by(backend_namespace, http_status)",
     "legendFormat": "{{ backend_namespace }} / {{ http_status }}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(outbound_http_route_backend_response_duration_seconds_sum{route_kind=~\"(?i)httproute\", route_namespace=\"pdf\", route_name=\"pdf3-migration\"}[$__rate_interval])) by(backend_namespace)\r\n  / \r\n  sum(rate(outbound_http_route_backend_response_duration_seconds_count{route_kind=~\"(?i)httproute\", route_namespace=\"pdf\", route_name=\"pdf3-migration\"}[$__rate_interval])) by(backend_namespace)",
     "legendFormat": "{{ backend_namespace }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"pdf|runtime-pdf3\", container!=\"\", container!=\"POD\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"pdf|runtime-pdf3\", container!=\"\", container!=\"POD\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - concurrency - proxy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"pdf3-proxy\"}) by (job)",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "sum(go_threads{job=\"pdf3-proxy\"}) by (job)",
     "legendFormat": "OS threads"
    }
   ]
  },
  {
   "title": "Go - concurrency - worker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"pdf3-worker\"}) by (job)",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "sum(go_threads{job=\"pdf3-worker\"}) by (job)",
     "legendFormat": "OS threads"
    }
   ]
  },
  {
   "title": "Go - memory - proxy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"pdf3-proxy\"}[$__rate_interval])) by (job)",
     "legendFormat": "Allocation rate"
    },
    {
     "expr": "avg(rate(go_gc_duration_seconds_sum{job=\"pdf3-proxy\"}[$__rate_interval])) by (job) * 100",
     "legendFormat": "Avg GC %"
    }
   ]
  },
  {
   "title": "Go - memory - worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"pdf3-worker\"}[$__rate_interval])) by (job)",
     "legendFormat": "Allocation rate"
    },
    {
     "expr": "avg(rate(go_gc_duration_seconds_sum{job=\"pdf3-worker\"}[$__rate_interval])) by (job) * 100",
     "legendFormat": "Avg GC %"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase({\"http.server.request.duration_seconds_bucket\", job=\"pdf3-proxy\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}