using Altinn.App.Clients.Fiks.FiksIO.Models;
using Altinn.App.Core.Features;

namespace Altinn.App.Clients.Fiks.FiksArkiv;

/// <summary>
/// Generates and sends Fiks Arkiv messages for <see cref="FiksArkivServiceTask"/>.
/// </summary>
internal interface IFiksArkivMessageSender
{
    /// <summary>
    /// Generates a message of the given type for the active instance and sends it via Fiks Arkiv.
    /// The content is generated by the configured <see cref="IFiksArkivPayloadGenerator"/>, which must be
    /// capable of generating the given message type.
    /// </summary>
    /// <param name="taskId">The task ID the message is generated from.</param>
    /// <param name="messageType">The Fiks Arkiv message type (create, update, etc).</param>
    /// <param name="sendersReference">The caller-provided sender reference used to identify retries of the same message.</param>
    /// <param name="replyAddress">
    /// The address the recipient's answers must be routed back to — for
    /// <see cref="FiksArkivServiceTask"/>, the <c>ServiceTaskMailbox.Id</c> handed to its send stage.
    /// It travels as the Fiks IO <c>klientKorrelasjonsId</c>, the one field Fiks IO echoes back on every
    /// reply, so an answer can be delivered into the mailbox the task is waiting on.
    /// </param>
    /// <param name="executionReferenceTime">The execution reference time, stable across retries.</param>
    /// <param name="dataMutator">The active instance data mutator.</param>
    /// <param name="cancellationToken">An optional cancellation token.</param>
    /// <remarks>
    /// The archive record is staged into the unit of work before the shipment leaves; a failed send discards it
    /// with the rest of the attempt's data changes, so a record is never left behind for a message that never went.
    /// </remarks>
    Task<FiksIOMessageResponse> GenerateAndSendMessage(
        string taskId,
        string messageType,
        Guid sendersReference,
        Guid replyAddress,
        DateTimeOffset executionReferenceTime,
        IInstanceDataMutator dataMutator,
        CancellationToken cancellationToken = default
    );
}
