{
 "title": "Altinn Apps",
 "tags": [ "altinn" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "org",
    "label": "Organization",
    "query": {}
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app",
    "label": "App name",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available,deployment)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Altinn Apps" } },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Instances created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customMetrics\n| where $__timeFilter(timestamp)\n| where name == \"altinn_app_lib_instances_created\"\n| where cloud_RoleName in ($app)\n| summarize Value = sum(valueCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc;",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Instances completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customMetrics\n| where $__timeFilter(timestamp)\n| where name == \"altinn_app_lib_instances_completed\"\n| where cloud_RoleName in ($app)\n| summarize Value = sum(valueCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc;",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Processes started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customMetrics\n| where $__timeFilter(timestamp)\n| where name == \"altinn_app_lib_processes_started\"\n| where cloud_RoleName in ($app)\n| summarize Value = sum(valueCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc;",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Processes ended",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customMetrics\n| where $__timeFilter(timestamp)\n| where name == \"altinn_app_lib_processes_ended\"\n| where cloud_RoleName in ($app)\n| summarize Value = sum(valueCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc;",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Failed process/next requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\n| where $__timeFilter(timestamp)\n| where success == false\n| where client_Type != 'Browser'\n| where toint(resultCode) >= 500\n| where cloud_RoleName in ($app)\n| where name has 'PUT Process/NextElement'\n| summarize Value = sum(itemCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\n| where $__timeFilter(timestamp)\n| where client_Type != 'Browser'\n| where cloud_RoleName in ($app)\n| summarize Value = sum(itemCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "5xx failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\n| where $__timeFilter(timestamp)\n| where success == false\n| where client_Type != 'Browser'\n| where toint(resultCode) >= 500\n| where cloud_RoleName in ($app)\n| summarize Value = sum(itemCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\n| where $__timeFilter(timestamp)\n| where client_Type != 'Browser'\n| where cloud_RoleName in ($app)\n| summarize Value = avg(duration) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Server exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "exceptions\n| where $__timeFilter(timestamp)\n| where client_Type != 'Browser'\n| where cloud_RoleName in ($app)\n| summarize exceptions_count = count() by bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n            container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}\n            * on(namespace,pod)\n            group_left(workload, workload_type)\n            namespace_workload_pod:kube_pod_owner:relabel{\n                namespace=\"default\",\n                workload_type=\"deployment\",\n                workload=~\"^$org-$app-deployment-v2$\"\n            }\n        ) by (workload)\n        /\n        sum(\n            kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"memory\"}\n            * on(namespace,pod)\n            group_left(workload, workload_type)\n            namespace_workload_pod:kube_pod_owner:relabel{\n                namespace=\"default\",\n                workload_type=\"deployment\",\n                workload=~\"^$org-$app-deployment-v2$\"\n            }\n        ) by (workload)\n        * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency call failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "dependencies\n| where $__timeFilter(timestamp)\n| where success == false\n| where client_Type != 'Browser'\n| where toint(resultCode) >= 500\n| where cloud_RoleName in ($app)\n| summarize Value = sum(itemCount) by cloud_RoleName, bin(timestamp, $__interval)\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "time_series",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n                sum by (namespace, pod, container) (\n                    rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\"}[5m])\n                )\n                * on(namespace,pod)\n                group_left(workload, workload_type)\n                namespace_workload_pod:kube_pod_owner:relabel{\n                    namespace=\"default\",\n                    workload_type=\"deployment\",\n                    workload=~\"^$org-$app-deployment-v2$\"\n                }\n            ) by (workload)\n            /\n            sum(\n                kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"cpu\"}\n                * on(namespace,pod)\n                group_left(workload, workload_type)\n                namespace_workload_pod:kube_pod_owner:relabel{\n                    namespace=\"default\",\n                    workload_type=\"deployment\",\n                    workload=~\"^$org-$app-deployment-v2$\"\n                }\n            ) by (workload)\n            * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(\n  100 *\n  sum by (namespace, deployment) (\n    kube_deployment_status_replicas_available{namespace=\"default\", deployment=~\"^$org-.*-deployment-v2$\"}\n  )\n  /\n  clamp_min(\n    sum by (namespace, deployment) (\n      kube_deployment_spec_replicas{namespace=\"default\", deployment=~\"^$org-$app-deployment-v2$\"}\n    ), 1\n  ),\n  100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}