apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvt-managed-csi
allowVolumeExpansion: true
parameters:
  cachingMode: ReadOnly
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
