{
 "title": "Kubernetes Deployment",
 "description": "Kubernetes deployments overview dashboard",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Loadbalancer", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 } },
  { "title": "Designer", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 } },
  { "title": "Repositories", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 } },
  { "title": "Runtime", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod_name=~\"altinn-loadbalancer.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod_name=~\"altinn-loadbalancer.*\"}) / 1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod_name=~\"altinn-loadbalancer.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod_name=~\"altinn-loadbalancer.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod_name=~\"altinn-designer.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod_name=~\"altinn-designer.*\"}) / 1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod_name=~\"altinn-designer.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod_name=~\"altinn-designer.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod_name=~\"altinn-repositories.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod_name=~\"altinn-repositories.*\"}) / 1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod_name=~\"altinn-repositories.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod_name=~\"altinn-repositories.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod_name=~\"altinn-runtime.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod_name=~\"altinn-runtime.*\"}) / 1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod_name=~\"altinn-runtime.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod_name=~\"altinn-runtime.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-loadbalancer\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-loadbalancer\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{namespace=\"default\", deployment=\"altinn-loadbalancer\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{namespace=\"default\", deployment=\"altinn-loadbalancer\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{namespace=\"default\", deployment=\"altinn-loadbalancer\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{namespace=\"default\", deployment=\"altinn-loadbalancer\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"default\", deployment=\"altinn-loadbalancer\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-designer\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-repositories\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"altinn-runtime\",namespace=\"default\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}