using Altinn.App.Core.Internal.WorkflowEngine.Commands;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.AltinnEvents;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.ProcessEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskAbandon;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskStart;
using Altinn.App.Core.Internal.WorkflowEngine.Models.AppCommand;
using Altinn.App.Core.Internal.WorkflowEngine.Models.Engine;

namespace Altinn.App.Core.Internal.WorkflowEngine;

/// <summary>
/// Defines a group of commands that should be executed for a process event.
/// </summary>
internal sealed class WorkflowCommandSet
{
    private readonly List<StepRequest> _commands = [];
    private readonly List<StepRequest> _criticalPostCommitCommands = [];
    private readonly List<StepRequest> _sideEffectCommands = [];

    /// <summary>
    /// Gets the main commands for this event. CommitProcessState will be added after these.
    /// </summary>
    public IReadOnlyList<StepRequest> Commands => _commands;

    /// <summary>
    /// Gets the post-commit commands that must complete before the transition is considered done
    /// (e.g., ExecuteServiceTask). These stay in the Main workflow and gate the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> CriticalPostCommitCommands => _criticalPostCommitCommands;

    /// <summary>
    /// Gets the non-critical, fire-and-forget post-commit commands (e.g., MovedToAltinnEvent).
    /// These run in a separate side-effects workflow that never gates the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> SideEffectCommands => _sideEffectCommands;

    /// <summary>
    /// Whether this command set schedules a service-task command after CommitProcessState.
    /// The factory copies this exact sequence fact into the commit payload.
    /// </summary>
    public bool ServiceTaskFollowsCommit { get; private set; }

    /// <summary>
    /// Creates command group for task start events.
    /// </summary>
    public static WorkflowCommandSet GetTaskStartSteps(TaskStartContext context)
    {
        // CleanupGeneratedFromTask runs before the hooks so that all task-start logic (including
        // app-supplied IOnTaskStartingHandler implementations) reads a clean slate, free of stale
        // elements generated by previous visits to the entering task.
        var group = new WorkflowCommandSet()
            .AddCommand(UnlockTaskData.Key, new TaskDataLockPayload(context.TaskId))
            .AddCommand(CleanupGeneratedFromTask.Key)
            .AddCommand(OnTaskStartingHook.Key)
            .AddCommand(CommonTaskInitialization.Key, new CommonTaskInitializationPayload(context.Prefill))
            .AddCommand(StartTask.Key);

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(MovedToAltinnEvent.Key);
        }

        if (context.ServiceTaskType is not null)
        {
            group.AddServiceTaskAfterCommit(context.ServiceTaskType, context.ServiceTaskStageNames);
        }

        if (context.IsInstantiation && context.RegisterEvents)
        {
            group.AddSideEffectCommand(InstanceCreatedAltinnEvent.Key);
        }

        if (context.IsInstantiation && context.Notification is not null)
        {
            group.AddSideEffectCommand(
                NotifyInstanceOwnerOnInstantiation.Key,
                new NotifyInstanceOwnerOnInstantiationPayload(context.Notification)
            );
        }

        return group;
    }

    /// <summary>
    /// Creates command group for task end events.
    /// </summary>
    public static WorkflowCommandSet GetTaskEndSteps(string taskId)
    {
        return new WorkflowCommandSet()
            .AddCommand(EndTask.Key)
            .AddCommand(CommonTaskFinalization.Key)
            .AddCommand(OnTaskEndingHook.Key)
            .AddCommand(LockTaskData.Key, new TaskDataLockPayload(taskId));
    }

    /// <summary>
    /// Creates command group for task abandon events.
    /// </summary>
    public static WorkflowCommandSet GetTaskAbandonSteps()
    {
        return new WorkflowCommandSet().AddCommand(AbandonTask.Key).AddCommand(OnTaskAbandonHook.Key);
    }

    /// <summary>
    /// Creates command group for process end events.
    /// </summary>
    public static WorkflowCommandSet GetProcessEndSteps(ProcessEndContext context)
    {
        var group = new WorkflowCommandSet().AddCommand(OnProcessEndingHook.Key).AddCommand(EndProcessLegacyHook.Key);

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(CompletedAltinnEvent.Key);
        }

        return group;
    }

    /// <summary>
    /// Adds a command to the main sequence.
    /// </summary>
    private WorkflowCommandSet AddCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _commands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Adds a command that executes after the ProcessNext has been committed to storage via
    /// CommitProcessState, and that must complete before the transition settles.
    /// </summary>
    /// <param name="commandKey">The command's registered key.</param>
    /// <param name="payload">Optional command payload.</param>
    /// <param name="operationId">
    /// Optional display identity for the engine step when it must differ from the command key —
    /// service-task pipeline stages carry the stage name here so the engine's records tell them apart.
    /// </param>
    /// <param name="serviceTaskStageName">
    /// For a service-task pipeline stage: the stage's name, so per-stage options can be resolved
    /// when the step request is finalized.
    /// </param>
    private WorkflowCommandSet AddCriticalPostCommitCommand(
        string commandKey,
        CommandRequestPayload? payload = null,
        string? operationId = null,
        string? serviceTaskStageName = null
    )
    {
        _criticalPostCommitCommands.Add(CreateCommand(commandKey, payload, operationId, serviceTaskStageName));
        return this;
    }

    /// <summary>
    /// Adds a non-critical post-commit command that runs in the fire-and-forget side-effects workflow.
    /// </summary>
    private WorkflowCommandSet AddSideEffectCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _sideEffectCommands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Appends the service task's engine steps after the commit: one per pipeline stage in
    /// composition order, then the concluding step (the pipeline's Finally — a simple task's
    /// Execute — identified by a null stage name). Each stage gets a distinct OperationId for the
    /// engine's records and dashboards; the payload's stage name is what callback dispatch keys on.
    /// The whole expansion is one sequence fact for the commit payload: a service task follows.
    /// </summary>
    private void AddServiceTaskAfterCommit(string serviceTaskType, IReadOnlyList<string>? stageNames)
    {
        ServiceTaskFollowsCommit = true;

        foreach (string stageName in stageNames ?? [])
        {
            AddCriticalPostCommitCommand(
                ExecuteServiceTask.Key,
                new ExecuteServiceTaskPayload(serviceTaskType, stageName),
                operationId: $"{ExecuteServiceTask.Key}: {stageName}",
                serviceTaskStageName: stageName
            );
        }

        AddCriticalPostCommitCommand(ExecuteServiceTask.Key, new ExecuteServiceTaskPayload(serviceTaskType));
    }

    private static StepRequest CreateCommand(
        string commandKey,
        CommandRequestPayload? payload = null,
        string? operationId = null,
        string? serviceTaskStageName = null
    )
    {
        string? serializedPayload = CommandPayloadSerializer.Serialize(payload);
        return new StepRequest
        {
            OperationId = operationId ?? commandKey,
            Command = CommandDefinition.Create(
                "app",
                new AppCommandData { CommandKey = commandKey, Payload = serializedPayload }
            ),
            ServiceTaskStageName = serviceTaskStageName,
        };
    }
}
