using System.Diagnostics;
using System.Globalization;
using Altinn.App.Core.Features.Process;
using Altinn.App.Core.Internal.WorkflowEngine.Commands;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.AltinnEvents;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.ProcessEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskAbandon;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskStart;
using Altinn.App.Core.Internal.WorkflowEngine.Models.AppCommand;
using Altinn.App.Core.Internal.WorkflowEngine.Models.Engine;

namespace Altinn.App.Core.Internal.WorkflowEngine;

/// <summary>
/// A segment's receive half. The two indexes are different positions: <paramref name="Step"/> names the
/// handler by its own item index, while <paramref name="OpeningStageIndex"/> is what addresses the mailbox.
/// </summary>
/// <param name="Step">The receive workflow's single step.</param>
/// <param name="OpeningStageIndex">The item index whose stage's mint the receiver is enqueued against.</param>
internal sealed record MailboxReceivePlan(StepRequest Step, int OpeningStageIndex);

/// <summary>
/// One planned pipeline segment. A non-null <see cref="Receive"/> means the enqueuing hop must end the
/// segment with an <c>EnqueueReceiveWorkflow</c> step of its own — deliberately not planned here, because its
/// labels, operation id and callback context belong to the hop doing the enqueueing.
/// </summary>
/// <param name="Steps">The segment's steps, in execution order, with options unresolved.</param>
/// <param name="Receive">The exchange the segment ends on, or null when it ends with the conclusion.</param>
internal sealed record ServiceTaskSegmentPlan(IReadOnlyList<StepRequest> Steps, MailboxReceivePlan? Receive);

/// <summary>
/// Defines a group of commands that should be executed for a process event.
/// </summary>
internal sealed class WorkflowCommandSet
{
    private readonly List<StepRequest> _commands = [];
    private readonly List<StepRequest> _criticalPostCommitCommands = [];
    private readonly List<StepRequest> _sideEffectCommands = [];

    /// <summary>
    /// Gets the main commands for this event. SaveProcessStateToStorage will be added after these.
    /// </summary>
    public IReadOnlyList<StepRequest> Commands => _commands;

    /// <summary>
    /// Gets the post-commit commands that must complete before the transition is considered done
    /// (e.g., ExecuteServiceTask). These stay in the Main workflow and gate the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> CriticalPostCommitCommands => _criticalPostCommitCommands;

    /// <summary>
    /// Gets the non-critical, fire-and-forget post-commit commands (e.g., MovedToAltinnEvent).
    /// These run in a separate side-effects workflow that never gates the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> SideEffectCommands => _sideEffectCommands;

    /// <summary>
    /// For a mailbox-opening service task: the one step its receive workflows run, and the exchange it
    /// answers. Null for every other event.
    /// </summary>
    public MailboxReceivePlan? MailboxReceive { get; private set; }

    /// <summary>
    /// Creates command group for task start events.
    /// </summary>
    public static WorkflowCommandSet GetTaskStartSteps(TaskStartContext context)
    {
        // CleanupGeneratedFromTask runs before the hooks so that all task-start logic (including
        // app-supplied IOnTaskStartingHandler implementations) reads a clean slate, free of stale
        // elements generated by previous visits to the entering task.
        var group = new WorkflowCommandSet()
            .AddCommand(UnlockTaskData.Key)
            .AddCommand(CleanupGeneratedFromTask.Key)
            .AddCommand(OnTaskStartingHook.Key)
            .AddCommand(CommonTaskInitialization.Key, new CommonTaskInitializationPayload(context.Prefill))
            .AddCommand(StartTask.Key);

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(MovedToAltinnEvent.Key);
        }

        if (context.ServiceTask is { } serviceTask)
        {
            ServiceTaskSegmentPlan segment = PlanSegment(serviceTask.Type, serviceTask.Pipeline);
            group.AddCriticalPostCommitSteps(segment.Steps);
            group.MailboxReceive = segment.Receive;
        }

        if (context.IsInstantiation && context.RegisterEvents)
        {
            group.AddSideEffectCommand(InstanceCreatedAltinnEvent.Key);
        }

        if (context.IsInstantiation && context.Notification is not null)
        {
            group.AddSideEffectCommand(
                NotifyInstanceOwnerOnInstantiation.Key,
                new NotifyInstanceOwnerOnInstantiationPayload(context.Notification)
            );
        }

        return group;
    }

    /// <summary>
    /// Creates command group for task end events.
    /// </summary>
    public static WorkflowCommandSet GetTaskEndSteps()
    {
        return new WorkflowCommandSet()
            .AddCommand(EndTask.Key)
            .AddCommand(CommonTaskFinalization.Key)
            .AddCommand(OnTaskEndingHook.Key)
            .AddCommand(LockTaskData.Key);
    }

    /// <summary>
    /// Creates command group for task abandon events.
    /// </summary>
    public static WorkflowCommandSet GetTaskAbandonSteps()
    {
        return new WorkflowCommandSet().AddCommand(AbandonTask.Key).AddCommand(OnTaskAbandonHook.Key);
    }

    /// <summary>
    /// Creates command group for process end events.
    /// </summary>
    public static WorkflowCommandSet GetProcessEndSteps(ProcessEndContext context)
    {
        // EndProcessLegacyHook runs post-commit because IProcessEnd.End reads instance.Process.EndEvent,
        // which is only set when the process state is persisted. This matches the old ProcessEngine behavior
        // where RunAppDefinedProcessEndHandlers ran after HandleEventsAndUpdateStorage.
        var group = new WorkflowCommandSet()
            .AddCommand(OnProcessEndingHook.Key)
            .AddCriticalPostCommitCommand(EndProcessLegacyHook.Key);

        if (context.HasAutoDeleteDataTypes)
        {
            group.AddCriticalPostCommitCommand(DeleteDataElementsIfConfigured.Key);
        }

        if (context.AutoDeleteInstanceOnProcessEnd)
        {
            group.AddCriticalPostCommitCommand(DeleteInstanceIfConfigured.Key);
        }

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(CompletedAltinnEvent.Key);
        }

        return group;
    }

    /// <summary>
    /// Adds a command to the main sequence.
    /// </summary>
    private WorkflowCommandSet AddCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _commands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Adds a command that executes after the ProcessNext has been committed to storage via
    /// SaveProcessStateToStorage, and that must complete before the transition settles.
    /// </summary>
    /// <param name="commandKey">The command's registered key.</param>
    /// <param name="payload">Optional command payload.</param>
    private WorkflowCommandSet AddCriticalPostCommitCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _criticalPostCommitCommands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    private WorkflowCommandSet AddCriticalPostCommitSteps(IEnumerable<StepRequest> steps)
    {
        _criticalPostCommitCommands.AddRange(steps);
        return this;
    }

    /// <summary>
    /// Adds a non-critical post-commit command that runs in the fire-and-forget side-effects workflow.
    /// </summary>
    private WorkflowCommandSet AddSideEffectCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _sideEffectCommands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Plans one pipeline segment: one <c>ExecuteServiceTask</c> step per stage in composition order — each
    /// preceded by a <c>MintMailbox</c> step where the stage opens a mailbox — ending on the first item that
    /// ends a segment (a reply handler's receive half, or the concluding step). Segments are the items split
    /// at each reply handler: segment 0 rides Main (<paramref name="afterHandlerItemIndex"/> null), segment k
    /// rides the continuation the relay enqueues when exchange k concludes, and a handler is never a step of
    /// the segment it ends. Options are left unresolved and a receive half's enqueue step is the caller's to
    /// append — the frontier-never-empty convention is the caller's to hold.
    /// </summary>
    internal static ServiceTaskSegmentPlan PlanSegment(
        string serviceTaskType,
        ServiceTaskPipeline pipeline,
        int? afterHandlerItemIndex = null
    )
    {
        var steps = new List<StepRequest>();

        for (int index = FindSegmentStart(afterHandlerItemIndex); index < pipeline.Items.Count; index++)
        {
            switch (pipeline.Items[index])
            {
                case ReplySegment handler:
                    return new ServiceTaskSegmentPlan(
                        steps,
                        new MailboxReceivePlan(CreateReceiveHandlerStep(serviceTaskType, index), handler.OpeningIndex)
                    );

                case PipelineConclusion.ReplyExchange exchange:
                    return new ServiceTaskSegmentPlan(
                        steps,
                        new MailboxReceivePlan(CreateReceiveHandlerStep(serviceTaskType, index), exchange.OpeningIndex)
                    );

                case PipelineConclusion.FinalStep:
                    steps.Add(
                        CreateCommand(
                            ExecuteServiceTask.Key,
                            new ExecuteServiceTaskPayload(serviceTaskType, ItemIndex: index),
                            operationId: $"{ExecuteServiceTask.Key}: {index.ToString(CultureInfo.InvariantCulture)}",
                            serviceTaskItemIndex: index
                        )
                    );
                    return new ServiceTaskSegmentPlan(steps, Receive: null);

                case ServiceTaskStage stage:
                    if (stage is ServiceTaskStage.MailboxOpening)
                    {
                        // The mint hugs the stage that sends, on both sides: the deadline clock starts here,
                        // and the stage must never send without an address. No stage index on the step — the
                        // mint must not inherit the stage's options.
                        steps.Add(
                            CreateCommand(
                                MintMailbox.Key,
                                new MintMailboxPayload(serviceTaskType, index),
                                operationId: $"{MintMailbox.Key}: {index.ToString(CultureInfo.InvariantCulture)}"
                            )
                        );
                    }

                    // A distinct OperationId per stage, for the engine's records and dashboards.
                    steps.Add(
                        CreateCommand(
                            ExecuteServiceTask.Key,
                            new ExecuteServiceTaskPayload(serviceTaskType, ItemIndex: index),
                            operationId: $"{ExecuteServiceTask.Key}: {index.ToString(CultureInfo.InvariantCulture)}",
                            serviceTaskItemIndex: index
                        )
                    );
                    break;

                default:
                    throw new UnreachableException(
                        $"Unknown pipeline item type: {pipeline.Items[index].GetType().Name}"
                    );
            }
        }

        // Named rather than swallowed: planning nothing here would silently drop the rest of the task.
        throw new UnreachableException(
            $"Service task '{serviceTaskType}' composes {pipeline.Items.Count} pipeline items, so a segment "
                + $"starting at index {FindSegmentStart(afterHandlerItemIndex)} reaches no conclusion. Either "
                + "the segment was planned after an item that is not a reply handler, or Define did not return "
                + "the same pipeline it returned to the dispatch that named that handler."
        );
    }

    /// <summary>
    /// Where the requested segment starts: the beginning for segment 0, and otherwise the item after the
    /// handler at <paramref name="afterHandlerItemIndex"/>.
    /// </summary>
    private static int FindSegmentStart(int? afterHandlerItemIndex) =>
        afterHandlerItemIndex is { } handler ? handler + 1 : 0;

    /// <summary>
    /// The one step a receive workflow runs: an <c>ExecuteServiceTask</c> step naming the reply handler that
    /// answers the message by its item index, fixed here at the receiver's enqueue and never re-derived. The
    /// index travels three ways, deliberately: in the payload (dispatch reads it), in
    /// <see cref="StepRequest.ServiceTaskItemIndex"/> (the enqueueing hop resolves options by it), and in the
    /// OperationId (the engine's own record). Which exchange the step answers is not carried at all: it is
    /// read off the handler this index resolves to.
    /// </summary>
    internal static StepRequest CreateReceiveHandlerStep(string serviceTaskType, int handlerItemIndex) =>
        CreateCommand(
            ExecuteServiceTask.Key,
            new ExecuteServiceTaskPayload(serviceTaskType, ItemIndex: handlerItemIndex),
            operationId: $"{ExecuteServiceTask.Key}: {handlerItemIndex.ToString(CultureInfo.InvariantCulture)}",
            serviceTaskItemIndex: handlerItemIndex
        );

    /// <summary>
    /// The step that ends a segment ending on an exchange: it enqueues the exchange's first receive workflow,
    /// carrying the workflow its hop pre-assembled and the item index whose stage's mailbox that receiver is
    /// declared against. Shared by the two hops that end a segment — Main's assembly and the relay's
    /// continuation — while the workflow inside it is each hop's own.
    /// </summary>
    internal static StepRequest CreateReceiveEnqueueStep(
        WorkflowEnqueueRequest receiveEnqueueRequest,
        int openingStageIndex
    ) =>
        CreateCommand(
            EnqueueReceiveWorkflow.Key,
            new EnqueueReceiveWorkflowPayload(receiveEnqueueRequest, openingStageIndex)
        );

    private static StepRequest CreateCommand(
        string commandKey,
        CommandRequestPayload? payload = null,
        string? operationId = null,
        int? serviceTaskItemIndex = null
    )
    {
        string? serializedPayload = CommandPayloadSerializer.Serialize(payload);
        return new StepRequest
        {
            OperationId = operationId ?? commandKey,
            Command = CommandDefinition.Create(
                "app",
                new AppCommandData { CommandKey = commandKey, Payload = serializedPayload }
            ),
            CommandKey = commandKey,
            ServiceTaskItemIndex = serviceTaskItemIndex,
        };
    }
}
