using Altinn.App.Core.Internal.WorkflowEngine.Commands;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.AltinnEvents;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.ProcessEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskAbandon;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskEnd;
using Altinn.App.Core.Internal.WorkflowEngine.Commands.ProcessNext.TaskStart;
using Altinn.App.Core.Internal.WorkflowEngine.Models.AppCommand;
using Altinn.App.Core.Internal.WorkflowEngine.Models.Engine;

namespace Altinn.App.Core.Internal.WorkflowEngine;

/// <summary>
/// Defines a group of commands that should be executed for a process event.
/// </summary>
internal sealed class WorkflowCommandSet
{
    private readonly List<StepRequest> _commands = [];
    private readonly List<StepRequest> _criticalPostCommitCommands = [];
    private readonly List<StepRequest> _sideEffectCommands = [];

    /// <summary>
    /// Gets the main commands for this event. SaveProcessStateToStorage will be added after these.
    /// </summary>
    public IReadOnlyList<StepRequest> Commands => _commands;

    /// <summary>
    /// Gets the post-commit commands that must complete before the transition is considered done
    /// (e.g., ExecuteServiceTask). These stay in the Main workflow and gate the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> CriticalPostCommitCommands => _criticalPostCommitCommands;

    /// <summary>
    /// Gets the non-critical, fire-and-forget post-commit commands (e.g., MovedToAltinnEvent).
    /// These run in a separate side-effects workflow that never gates the next transition.
    /// </summary>
    public IReadOnlyList<StepRequest> SideEffectCommands => _sideEffectCommands;

    /// <summary>
    /// Creates command group for task start events.
    /// </summary>
    public static WorkflowCommandSet GetTaskStartSteps(TaskStartContext context)
    {
        // CleanupGeneratedFromTask runs before the hooks so that all task-start logic (including
        // app-supplied IOnTaskStartingHandler implementations) reads a clean slate, free of stale
        // elements generated by previous visits to the entering task.
        var group = new WorkflowCommandSet()
            .AddCommand(UnlockTaskData.Key)
            .AddCommand(CleanupGeneratedFromTask.Key)
            .AddCommand(OnTaskStartingHook.Key)
            .AddCommand(CommonTaskInitialization.Key, new CommonTaskInitializationPayload(context.Prefill))
            .AddCommand(StartTask.Key);

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(MovedToAltinnEvent.Key);
        }

        if (context.ServiceTaskType is not null)
        {
            group.AddCriticalPostCommitCommand(
                ExecuteServiceTask.Key,
                new ExecuteServiceTaskPayload(context.ServiceTaskType)
            );
        }

        if (context.IsInstantiation && context.RegisterEvents)
        {
            group.AddSideEffectCommand(InstanceCreatedAltinnEvent.Key);
        }

        if (context.IsInstantiation && context.Notification is not null)
        {
            group.AddSideEffectCommand(
                NotifyInstanceOwnerOnInstantiation.Key,
                new NotifyInstanceOwnerOnInstantiationPayload(context.Notification)
            );
        }

        return group;
    }

    /// <summary>
    /// Creates command group for task end events.
    /// </summary>
    public static WorkflowCommandSet GetTaskEndSteps()
    {
        return new WorkflowCommandSet()
            .AddCommand(EndTask.Key)
            .AddCommand(CommonTaskFinalization.Key)
            .AddCommand(OnTaskEndingHook.Key)
            .AddCommand(LockTaskData.Key);
    }

    /// <summary>
    /// Creates command group for task abandon events.
    /// </summary>
    public static WorkflowCommandSet GetTaskAbandonSteps()
    {
        return new WorkflowCommandSet().AddCommand(AbandonTask.Key).AddCommand(OnTaskAbandonHook.Key);
    }

    /// <summary>
    /// Creates command group for process end events.
    /// </summary>
    public static WorkflowCommandSet GetProcessEndSteps(ProcessEndContext context)
    {
        // EndProcessLegacyHook runs post-commit because IProcessEnd.End reads instance.Process.EndEvent,
        // which is only set when the process state is persisted. This matches the old ProcessEngine behavior
        // where RunAppDefinedProcessEndHandlers ran after HandleEventsAndUpdateStorage.
        var group = new WorkflowCommandSet()
            .AddCommand(OnProcessEndingHook.Key)
            .AddCriticalPostCommitCommand(EndProcessLegacyHook.Key);

        if (context.HasAutoDeleteDataTypes)
        {
            group.AddCriticalPostCommitCommand(DeleteDataElementsIfConfigured.Key);
        }

        if (context.AutoDeleteInstanceOnProcessEnd)
        {
            group.AddCriticalPostCommitCommand(DeleteInstanceIfConfigured.Key);
        }

        if (context.RegisterEvents)
        {
            group.AddSideEffectCommand(CompletedAltinnEvent.Key);
        }

        return group;
    }

    /// <summary>
    /// Adds a command to the main sequence.
    /// </summary>
    private WorkflowCommandSet AddCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _commands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Adds a command that executes after the ProcessNext has been committed to storage via
    /// SaveProcessStateToStorage, and that must complete before the transition settles.
    /// </summary>
    private WorkflowCommandSet AddCriticalPostCommitCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _criticalPostCommitCommands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    /// <summary>
    /// Adds a non-critical post-commit command that runs in the fire-and-forget side-effects workflow.
    /// </summary>
    private WorkflowCommandSet AddSideEffectCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        _sideEffectCommands.Add(CreateCommand(commandKey, payload));
        return this;
    }

    private static StepRequest CreateCommand(string commandKey, CommandRequestPayload? payload = null)
    {
        string? serializedPayload = CommandPayloadSerializer.Serialize(payload);
        return new StepRequest
        {
            OperationId = commandKey,
            Command = CommandDefinition.Create(
                "app",
                new AppCommandData { CommandKey = commandKey, Payload = serializedPayload }
            ),
        };
    }
}
