# base image
FROM gitea/gitea:1.10.2

# copy configuration file
COPY ./AltinnRepositories/gitea-data/gitea/conf/app.ini data/gitea/conf/app.ini
COPY ./AltinnRepositories/gitea-data/gitea/options data/gitea/options/
COPY ./AltinnRepositories/gitea-data/gitea/public/img data/gitea/public/img
COPY ./AltinnRepositories/gitea-data/gitea/templates data/gitea/templates
