const moduleName = 'FILE_UPLOAD';

export const UPLOAD_ATTACHMENT = `${moduleName}.UPLOAD_ATTACHMENT`;
export const UPLOAD_ATTACHMENT_FULFILLED = `${moduleName}.UPLOAD_ATTACHMENT_FULFILLED`;
export const UPLOAD_ATTACHMENT_REJECTED = `${moduleName}.UPLOAD_ATTACHMENT_REJECTED`;

export const UPDATE_ATTACHMENT = `${moduleName}.UPDATE_ATTACHMENT`;
export const UPDATE_ATTACHMENT_FULFILLED = `${moduleName}.UPDATE_ATTACHMENT_FULFILLED`;
export const UPDATE_ATTACHMENT_REJECTED = `${moduleName}.UPDATE_ATTACHMENT_REJECTED`;

export const DELETE_ATTACHMENT = `${moduleName}.DELETE_ATTACHMENT`;
export const DELETE_ATTACHMENT_FULFILLED = `${moduleName}.DELETE_ATTACHMENT_FULFILLED`;
export const DELETE_ATTACHMENT_REJECTED = `${moduleName}.DELETE_ATTACHMENT_REJECTED`;

export const MAP_ATTACHMENTS = `${moduleName}.MAP_ATTACHMENTS`;
export const MAP_ATTACHMENTS_FULFILLED = `${moduleName}.MAP_ATTACHMENTS_FULFILLED`;
export const MAP_ATTACHMENTS_REJECTED = `${moduleName}.MAP_ATTACHMENTS_REJECTED`;
