using Altinn.Studio.Cli.Upgrade;
using Altinn.Studio.Cli.Upgrade.v8Tov9;
using Altinn.Studio.Cli.Upgrade.v8Tov9.CSharpApiMigration;

namespace Studioctl.Tests.Upgrade.v8Tov9;

/// <summary>
/// Covers <see cref="RedundantUsingDirectiveMigration"/> on a syntax-only scanner, the view the upgrade
/// has for an app that already targets v9 or does not compile: only what is provably redundant goes,
/// and the lines around it keep their shape.
/// </summary>
public sealed class RedundantUsingDirectiveMigrationTests : IDisposable
{
    private static readonly IReadOnlySet<string> _globalNamespaces = new HashSet<string>(StringComparer.Ordinal)
    {
        "System",
        "System.Collections.Generic",
        "System.Linq",
        "Microsoft.Extensions.Logging",
        "Altinn.App.Core.Features",
    };

    private readonly TempAppFolder _app = new();

    public void Dispose() => _app.Dispose();

    private (int ChangedFiles, string Log) Migrate()
    {
        var csproj = _app.Write("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk.Web\"></Project>");
        var report = new UpgradeReport();
        using var scope = UpgradeConsole.Use(report, new StringWriter());
        UpgradeConsole.BeginStep("test");

        var changedFiles = new RedundantUsingDirectiveMigration(
            CSharpSourceScanner.ForProject(csproj),
            _globalNamespaces
        ).Migrate();

        var log = string.Join(Environment.NewLine, report.Steps.SelectMany(s => s.Messages.Select(m => m.Text)));
        return (changedFiles, log);
    }

    [Fact]
    public void RemovesFileLevelDuplicates_AndKeepsTheRest()
    {
        _app.Write(
            "Program.cs",
            """
            using System;
            using System.Linq;
            using Altinn.App.Core.Features;
            using Altinn.App.Api.Extensions;
            using Microsoft.Extensions.Logging;

            namespace Altinn.App;

            """
        );

        var (changedFiles, log) = Migrate();

        Assert.Equal(1, changedFiles);
        Assert.Contains("Removed 4 redundant using directive(s)", log, StringComparison.Ordinal);
        Assert.Equal(
            """
            using Altinn.App.Api.Extensions;

            namespace Altinn.App;

            """,
            _app.Read("Program.cs")
        );
    }

    [Fact]
    public void LeavesAliasesAndStaticImportsAlone()
    {
        const string source = """
            using Console = System.Console;
            using static System.Linq.Enumerable;

            namespace Altinn.App;

            """;
        _app.Write("Program.cs", source);

        var (changedFiles, _) = Migrate();

        Assert.Equal(0, changedFiles);
        Assert.Equal(source, _app.Read("Program.cs"));
    }

    [Fact]
    public void KeepsHeaderCommentsAndPreprocessorDirectives()
    {
        // A generated file starts like this: the header and '#nullable enable' are leading trivia of
        // the first using directive and must survive its removal.
        _app.Write(
            "logic/Generated.cs",
            """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using Newtonsoft.Json;

            namespace Altinn.App.Models;

            """
        );

        Migrate();

        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable
            using Newtonsoft.Json;

            namespace Altinn.App.Models;

            """,
            _app.Read("logic/Generated.cs")
        );
    }

    [Fact]
    public void LeavesTheGeneratedModelsFolderAlone()
    {
        // Studio regenerates the data model classes with every using directive in place, so removing
        // them here would only produce churn on the next regeneration.
        const string model = """
            #nullable enable
            using System;
            using System.Collections.Generic;
            using Newtonsoft.Json;

            namespace Altinn.App.Models;

            """;
        _app.Write("models/model.cs", model);
        _app.Write("Models/Nested/other.cs", model);

        var (changedFiles, _) = Migrate();

        Assert.Equal(0, changedFiles);
        Assert.Equal(model, _app.Read("models/model.cs"));
        Assert.Equal(model, _app.Read("Models/Nested/other.cs"));
    }

    [Fact]
    public void DoesNotLeaveBlankLinesAtTheTopOfTheFile()
    {
        _app.Write(
            "Program.cs",
            """
            using System;
            using System.Linq;

            using Newtonsoft.Json;

            namespace Altinn.App;

            """
        );

        Migrate();

        Assert.Equal(
            """
            using Newtonsoft.Json;

            namespace Altinn.App;

            """,
            _app.Read("Program.cs")
        );
    }

    [Fact]
    public void RemovingEveryUsing_LeavesTheDeclarationAtTheTop()
    {
        _app.Write(
            "Program.cs",
            """
            using System;
            using System.Linq;

            namespace Altinn.App
            {
                public class C { }
            }

            """
        );

        Migrate();

        Assert.Equal(
            """
            namespace Altinn.App
            {
                public class C { }
            }

            """,
            _app.Read("Program.cs")
        );
    }

    [Fact]
    public void KeepsACommentOnTheSameLine()
    {
        _app.Write(
            "Program.cs",
            """
            using System; // TODO: revisit
            using Newtonsoft.Json;

            """
        );

        Migrate();

        Assert.Equal(
            """
            // TODO: revisit
            using Newtonsoft.Json;

            """,
            _app.Read("Program.cs")
        );
    }

    [Fact]
    public void RemovesGlobalUsingsAndGlobalAliasQualifiedNames()
    {
        _app.Write(
            "GlobalUsings.cs",
            """
            global using System;
            using global::System.Linq;
            using System . Collections . Generic;
            using Newtonsoft.Json;

            """
        );

        Migrate();

        Assert.Equal(
            """
            using Newtonsoft.Json;

            """,
            _app.Read("GlobalUsings.cs")
        );
    }

    [Fact]
    public void WithoutSemanticModels_KeepsUsingsInsideNamespaces()
    {
        // Inside a namespace 'using System;' may bind to a nested namespace, which only the semantic
        // model can tell. A syntax-only view leaves it in place rather than guess.
        const string source = """
            namespace Altinn.App
            {
                using System;

                public class C { }
            }

            """;
        _app.Write("Program.cs", source);

        var (changedFiles, _) = Migrate();

        Assert.Equal(0, changedFiles);
        Assert.Equal(source, _app.Read("Program.cs"));
    }

    [Fact]
    public void TouchesOnlyFilesWithRedundantUsings()
    {
        const string untouched = """
            using Newtonsoft.Json;

            namespace Altinn.App;

            """;
        _app.Write("Untouched.cs", untouched);
        _app.Write("Program.cs", "using System;\nnamespace Altinn.App;\n");

        var (changedFiles, _) = Migrate();

        Assert.Equal(1, changedFiles);
        Assert.Equal(untouched, _app.Read("Untouched.cs"));
        Assert.Equal("namespace Altinn.App;\n", _app.Read("Program.cs"));
    }
}
