// <auto-generated />

using AltinnCore.ServiceLibrary.Enums;
using System.Collections.Generic;

namespace AltinnCore.Common.Models
{
    /// <summary>
    /// The rule container class
    /// </summary>
    public class RuleContainer
    {
        /// <summary>
        /// Gets or sets the id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the conditions
        /// </summary>
        public List<Condition> Conditions { get; set; }

        /// <summary>
        /// Gets or sets the list of rules
        /// </summary>
        public List<Rule> Rules { get; set; }

        /// <summary>
        /// Gets or sets the list of child rule containers 
        /// </summary>
        public List<RuleContainer> ChildContainers { get; set; }

        /// <summary>
        /// Gets or sets the service event type
        /// </summary>
        public ServiceEventType ServiceEventType { get; set; }
    }

    /// <summary>
    /// The condition group class
    /// </summary>
    public class ConditionGroup
    {
        /// <summary>
        /// Gets or sets the list of condition
        /// </summary>
        public List<Condition> Condition { get; set; }

        /// <summary>
        /// Gets or sets the list of condition delimiters
        /// </summary>
        public List<ConditionDelimiter> ConditionDelimiters { get; set; }
    }

    /// <summary>
    /// The condition class
    /// </summary>
    public class Condition
    {
        /// <summary>
        /// Gets or sets the condition type id
        /// </summary>
        public int ConditionTypeId { get; set; }

        /// <summary>
        /// Gets or sets the condition group
        /// </summary>
        public ConditionGroup ConditionGroup { get; set; }

        /// <summary>
        /// Gets or sets the list of parameters
        /// </summary>
        public List<Parameter> Parameters { get; set; }

        /// <summary>
        /// Gets or sets the delimiter
        /// </summary>
        public ConditionDelimiter Delimiter { get; set; }
    }

    /// <summary>
    /// The condition delimiter class
    /// </summary>
    public class ConditionDelimiter
    {
        /// <summary>
        /// Gets or sets the condition delimiter value
        /// </summary>
        public string Value { get; set; }
    }

    /// <summary>
    /// The rule class
    /// </summary>
    public class Rule
    {
        /// <summary>
        /// Gets or sets the rule type id
        /// </summary>
        public int RuleTypeId { get; set; }
        
        /// <summary>
        /// Gets or sets the list of parameter
        /// </summary>
        public List<Parameter> Parameters { get; set; }
    }

    /// <summary>
    /// The parameter class
    /// </summary>
    public class Parameter
    {
        /// <summary>
        /// Gets or sets the parameter index
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets the parameter element id
        /// </summary>
        public string ElementId { get; set; }
    }

    /// <summary>
    /// The condition type class
    /// </summary>
    public class ConditionType
    {
        /// <summary>
        /// Gets or sets the condition type id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the condition template
        /// </summary>
        public string Template { get; set; }

        /// <summary>
        /// Gets or sets the condition name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the condition description
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the list of parameter details
        /// </summary>
        public List<ParameterDetails> Parameters { get; set; }
    }

    /// <summary>
    /// The parameter details class
    /// </summary>
    public class ParameterDetails
    {
        /// <summary>
        /// Gets or sets the description
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the index
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the supported types
        /// </summary>
        public List<ValueType> SupportedTypes { get; set; }
    }

    /// <summary>
    /// The rule type class
    /// </summary>
    public class RuleType
    {
        /// <summary>
        /// Gets or sets the rule type id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the rule type template
        /// </summary>
        public string Template { get; set; }

        /// <summary>
        /// Gets or sets the list of parameters
        /// </summary>
        public List<ParameterDetails> Parameters { get; set; }

        /// <summary>
        /// Gets or sets the rule type name
        /// </summary>
        public string Name { get; internal set; }
    }

    /// <summary>
    /// The value type enum
    /// </summary>
    public enum ValueType
    {
        /// <summary>
        /// The string type
        /// </summary>
        String,
        /// <summary>
        /// The int 32 type
        /// </summary>
        Int32,
        /// <summary>
        /// The int 64 type
        /// </summary>
        Int64,
        /// <summary>
        /// The decimal type
        /// </summary>
        Decimal,
        /// <summary>
        /// The model property type
        /// </summary>
        ModelProperty
    }
}
