apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://localtest_victoria_metrics:8428
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
      timeInterval: "10s"

  - name: Traces
    type: jaeger
    uid: traces
    access: proxy
    orgId: 1
    url: http://localtest_victoria_traces:10428/select/jaeger/
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
