receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 5s
    send_batch_size: 10000

exporters:
  nop: {}
  otlphttp/victoria-traces:
    traces_endpoint: http://localtest_victoria_traces:10428/insert/opentelemetry/v1/traces
  prometheusremotewrite/victoria-metrics:
    endpoint: http://localtest_victoria_metrics:8428/api/v1/write

service:
  telemetry:
    logs:
      level: error
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoria-traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/victoria-metrics]
    logs:
      receivers: [otlp]
      exporters: [nop]
