export {
  mapLanguageKeyToLanguageText,
  getMissingInputLanguageString,
  getResourceIdentifierErrorMessage,
  deepCompare,
  getAvailableEnvironments,
  getEnvLabel,
  availableForTypeMap,
  resourceStatusMap,
  mapKeywordStringToKeywordTypeArray,
  mapKeywordsArrayToString,
  resourceTypeMap,
  validateResource,
  getAltinn2Reference,
  getMigrationErrorMessage,
  convertMetadataStringToConsentMetadata,
  getConsentResourcePolicyRules,
  getResourceSubjects,
} from './resourceUtils';
export type { EnvId, Environment } from './resourceUtils';
