//! OpenSSH client configuration files owned by the platform.
//!
//! `agentd` rewrites `<home>/ssh/config` and `<home>/ssh/known_hosts` as Agents
//! are applied and deleted; `agentctl ssh-config install` inserts one `Include`
//! of that config at the top of the user's own `~/.ssh/config` and touches
//! nothing else in it.

use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
};

use crate::Error;

/// One `Host` block in the generated client configuration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HostEntry {
    /// `Host` alias, `altinn-agent-<agent-name>`.
    pub alias: String,
    /// Guest user.
    pub user: String,
    /// Complete `ProxyCommand` value.
    pub proxy_command: String,
    /// `HostKeyAlias`, the stable incarnation-keyed `known_hosts` name.
    pub host_key_alias: String,
    /// Absolute private key path.
    pub identity_file: PathBuf,
    /// Absolute `known_hosts` path.
    pub known_hosts_file: PathBuf,
}

/// Renders the platform-owned client configuration for every SSH-enabled Agent.
#[must_use]
pub fn render_config(entries: &[HostEntry], user_home: Option<&Path>) -> String {
    let mut text = String::from(
        "# Generated by agentd for `agentctl ssh`; every edit is overwritten.\n\
         # Include it from your own client configuration with `agentctl ssh-config install`.\n",
    );
    for entry in entries {
        let _infallible = writeln!(
            text,
            "\nHost {}\n    User {}\n    ProxyCommand {}\n    HostKeyAlias {}\n    IdentityFile {}\n    UserKnownHostsFile {}\n    IdentitiesOnly yes",
            entry.alias,
            entry.user,
            entry.proxy_command,
            entry.host_key_alias,
            render_path(&entry.identity_file, user_home),
            render_path(&entry.known_hosts_file, user_home),
        );
    }
    text
}

/// Renders a host path for an OpenSSH configuration value.
///
/// A path below the user's home is written `~/...` with forward slashes, which
/// every OpenSSH port expands; anything else is written as the host spells it.
/// Anything outside a conservative character set is double-quoted with `"` and
/// `\` escaped, which is what OpenSSH's tokenizer understands.
#[must_use]
pub fn render_path(path: &Path, user_home: Option<&Path>) -> String {
    let text = user_home
        .and_then(|home| path.strip_prefix(home).ok())
        .filter(|relative| !relative.as_os_str().is_empty())
        .map_or_else(
            || path.display().to_string(),
            |relative| {
                let mut text = String::from("~");
                for component in relative.components() {
                    text.push('/');
                    text.push_str(&component.as_os_str().to_string_lossy());
                }
                text
            },
        );
    quote_config_value(&text)
}

/// Renders the `ProxyCommand` value dialing one Agent through `agentctl`.
///
/// The executable is always absolute: the shell running the command on Unix
/// would expand `~`, Win32-OpenSSH would not, and neither has `agentctl` on a
/// predictable `PATH`. OpenSSH hands the value to a shell, so the executable
/// is quoted with `"` and `\` escaped: that is the one quoting form OpenSSH's
/// own tokenizer, `/bin/sh` and Win32-OpenSSH all leave intact. `$`, backticks
/// and `;` inside double quotes would still be shell syntax on Unix, so a path
/// containing them is refused rather than rendered.
///
/// # Errors
///
/// Returns an error when the executable path contains characters that cannot be
/// passed through the shell safely.
pub fn render_proxy_command(agentctl: &Path, agent: &str) -> Result<String, Error> {
    let executable = agentctl.display().to_string();
    if executable.contains(['$', '`', ';', '\n', '\r', '\0']) || agentctl.as_os_str().to_str().is_none() {
        return Err(Error::Invalid(format!(
            "agentctl path {executable:?} contains characters that cannot be passed to the SSH ProxyCommand shell; \
             install agentctl at a plain path"
        )));
    }
    Ok(format!("{} ssh-proxy agent/{agent}", quote_config_value(&executable)))
}

/// Quotes an OpenSSH configuration token unless it consists only of characters
/// that need no quoting. Inside quotes `\` and `"` are backslash-escaped.
fn quote_config_value(text: &str) -> String {
    let plain = !text.is_empty()
        && text
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "/~._-:+@".contains(character));
    if plain {
        return text.to_owned();
    }
    let mut quoted = String::with_capacity(text.len() + 2);
    quoted.push('"');
    for character in text.chars() {
        if character == '"' || character == '\\' {
            quoted.push('\\');
        }
        quoted.push(character);
    }
    quoted.push('"');
    quoted
}

/// Replaces every `known_hosts` line for `alias` with `public_key`.
///
/// # Errors
///
/// Returns an error when the file cannot be read or rewritten.
pub fn upsert_known_host(path: &Path, alias: &str, public_key: &str) -> Result<(), Error> {
    let mut lines = known_hosts_without(path, alias)?;
    lines.push(format!("{alias} {public_key}"));
    write_lines(path, &lines)
}

/// Removes every `known_hosts` line for `alias`, leaving other entries untouched.
///
/// # Errors
///
/// Returns an error when the file cannot be read or rewritten.
pub fn remove_known_host(path: &Path, alias: &str) -> Result<(), Error> {
    if !path.exists() {
        return Ok(());
    }
    let lines = known_hosts_without(path, alias)?;
    write_lines(path, &lines)
}

fn known_hosts_without(path: &Path, alias: &str) -> Result<Vec<String>, Error> {
    let existing = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(error.into()),
    };
    Ok(existing
        .lines()
        .filter(|line| line.split_whitespace().next() != Some(alias))
        .map(str::to_owned)
        .collect())
}

fn write_lines(path: &Path, lines: &[String]) -> Result<(), Error> {
    let mut text = lines.join("\n");
    if !text.is_empty() {
        text.push('\n');
    }
    write_private_file(path, text.as_bytes())
}

/// Writes a user-only file atomically: the content lands under a temporary
/// name beside the target and is renamed over it.
///
/// # Errors
///
/// Returns an error when the parent directory is missing or the file cannot be written.
pub(super) fn write_private_file(path: &Path, contents: &[u8]) -> Result<(), Error> {
    let directory = path
        .parent()
        .ok_or_else(|| Error::Invalid(format!("{} has no parent directory", path.display())))?;
    let file_name = path
        .file_name()
        .ok_or_else(|| Error::Invalid(format!("{} has no file name", path.display())))?
        .to_string_lossy();
    let temporary = directory.join(format!(".{file_name}.{}.tmp", std::process::id()));
    std::fs::write(&temporary, contents)?;
    crate::local::home::secure_file(&temporary)?;
    if let Err(error) = std::fs::rename(&temporary, path) {
        let _ignored = std::fs::remove_file(&temporary);
        return Err(error.into());
    }
    Ok(())
}

/// Result of installing the `Include` line into the user's client configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IncludeOutcome {
    /// The line was inserted at the top of the file.
    Installed,
    /// The file already carried the line.
    AlreadyInstalled,
}

/// Renders the `Include` directive for the generated configuration.
#[must_use]
pub fn render_include(config: &Path, user_home: Option<&Path>) -> String {
    format!("Include {}", render_path(config, user_home))
}

/// Idempotently inserts `include` as the first line of `user_config`.
///
/// OpenSSH applies an `Include` inside a `Host` or `Match` block only to that
/// block, so only a copy that precedes the first block counts as installed; a
/// copy nested in a block is left alone and a global one is added above it.
/// Every existing line is kept verbatim. A symbolic link, as dotfile managers
/// create, is followed so the linked file is updated and the link survives. A
/// missing file or directory is created with user-only access.
///
/// # Errors
///
/// Returns an error when the file cannot be read or written.
pub fn install_include(user_config: &Path, include: &str) -> Result<IncludeOutcome, Error> {
    let target = std::fs::canonicalize(user_config).unwrap_or_else(|_| user_config.to_path_buf());
    let existing = match std::fs::read_to_string(&target) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(error.into()),
    };
    if global_lines(&existing).any(|line| line == include) {
        return Ok(IncludeOutcome::AlreadyInstalled);
    }
    if let Some(directory) = target.parent()
        && !directory.exists()
    {
        std::fs::create_dir_all(directory)?;
        crate::local::home::secure_directory(directory)?;
    }
    let mut text = format!("{include}\n");
    if !existing.is_empty() {
        text.push('\n');
        text.push_str(&existing);
    }
    write_private_file(&target, text.as_bytes())?;
    Ok(IncludeOutcome::Installed)
}

/// Yields the trimmed lines of an OpenSSH client configuration that apply
/// unconditionally: everything before the first `Host` or `Match` keyword.
fn global_lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines().map(str::trim).take_while(|line| {
        let keyword = line
            .split(|character: char| character.is_whitespace() || character == '=')
            .next()
            .unwrap_or_default();
        !keyword.eq_ignore_ascii_case("host") && !keyword.eq_ignore_ascii_case("match")
    })
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use std::path::Path;

    use super::{
        HostEntry, IncludeOutcome, install_include, remove_known_host, render_config, render_include, render_path,
        render_proxy_command, upsert_known_host,
    };

    fn entry(name: &str, id: &str, root: &Path) -> HostEntry {
        HostEntry {
            alias: format!("altinn-agent-{name}"),
            user: "agent".into(),
            proxy_command: render_proxy_command(Path::new("/usr/local/bin/agentctl"), name).expect("proxy command"),
            host_key_alias: format!("agent-{id}"),
            identity_file: root.join(id).join("id_ed25519"),
            known_hosts_file: root.join("known_hosts"),
        }
    }

    #[test]
    fn config_dials_through_agentctl_and_pins_the_incarnation_key() {
        let home = Path::new("/home/me");
        let root = home.join(".agent").join("ssh");
        let text = render_config(&[entry("worker", "1111", &root)], Some(home));
        let expected = "\
# Generated by agentd for `agentctl ssh`; every edit is overwritten.
# Include it from your own client configuration with `agentctl ssh-config install`.

Host altinn-agent-worker
    User agent
    ProxyCommand /usr/local/bin/agentctl ssh-proxy agent/worker
    HostKeyAlias agent-1111
    IdentityFile ~/.agent/ssh/1111/id_ed25519
    UserKnownHostsFile ~/.agent/ssh/known_hosts
    IdentitiesOnly yes
";
        assert_eq!(text, expected);
        assert_eq!(render_config(&[], Some(home)).lines().count(), 2);
    }

    #[test]
    fn paths_outside_home_and_with_spaces_are_absolute_and_quoted() {
        assert_eq!(
            render_path(
                Path::new("/srv/agent home/ssh/known_hosts"),
                Some(Path::new("/home/me"))
            ),
            "\"/srv/agent home/ssh/known_hosts\""
        );
        assert_eq!(
            render_path(Path::new("/home/me"), Some(Path::new("/home/me"))),
            "/home/me"
        );
        assert_eq!(
            render_proxy_command(Path::new("/opt/agent tools/agentctl"), "worker").expect("quoted"),
            "\"/opt/agent tools/agentctl\" ssh-proxy agent/worker"
        );
        assert_eq!(
            render_proxy_command(Path::new(r"C:\Program Files\agent\agentctl.exe"), "worker").expect("Windows"),
            r#""C:\\Program Files\\agent\\agentctl.exe" ssh-proxy agent/worker"#
        );
        assert_eq!(
            render_path(Path::new("/srv/say \"hi\"/known_hosts"), None),
            r#""/srv/say \"hi\"/known_hosts""#
        );
        for hostile in ["/opt/a;rm -rf /", "/opt/$HOME/agentctl", "/opt/`id`/agentctl"] {
            assert!(
                render_proxy_command(Path::new(hostile), "worker").is_err(),
                "{hostile} must be refused"
            );
        }
        assert_eq!(
            render_include(Path::new("/home/me/.agent/ssh/config"), Some(Path::new("/home/me"))),
            "Include ~/.agent/ssh/config"
        );
    }

    #[test]
    fn known_hosts_entries_are_keyed_by_alias() {
        let directory = tempfile::tempdir().expect("temporary directory");
        let path = directory.path().join("known_hosts");
        std::fs::write(&path, "github.com ssh-ed25519 AAAAgithub\n").expect("seed");
        upsert_known_host(&path, "agent-1", "ssh-ed25519 AAAAone").expect("insert");
        upsert_known_host(&path, "agent-2", "ssh-ed25519 AAAAtwo").expect("insert second");
        upsert_known_host(&path, "agent-1", "ssh-ed25519 AAAAone-rotated").expect("replace");
        assert_eq!(
            std::fs::read_to_string(&path).expect("read"),
            "github.com ssh-ed25519 AAAAgithub\nagent-2 ssh-ed25519 AAAAtwo\nagent-1 ssh-ed25519 AAAAone-rotated\n"
        );
        remove_known_host(&path, "agent-1").expect("remove");
        remove_known_host(&path, "agent-missing").expect("remove absent alias");
        assert_eq!(
            std::fs::read_to_string(&path).expect("read"),
            "github.com ssh-ed25519 AAAAgithub\nagent-2 ssh-ed25519 AAAAtwo\n"
        );
        remove_known_host(&directory.path().join("absent"), "agent-1").expect("absent file is fine");
    }

    #[test]
    fn include_goes_to_the_top_once_and_keeps_every_other_line() {
        let directory = tempfile::tempdir().expect("temporary directory");
        let config = directory.path().join(".ssh").join("config");
        let include = "Include ~/.agent/ssh/config";

        assert_eq!(
            install_include(&config, include).expect("fresh install"),
            IncludeOutcome::Installed
        );
        assert_eq!(
            std::fs::read_to_string(&config).expect("read"),
            "Include ~/.agent/ssh/config\n"
        );
        assert_eq!(
            install_include(&config, include).expect("repeat"),
            IncludeOutcome::AlreadyInstalled
        );

        let existing = "# mine\nHost github.com\n    User git\n";
        std::fs::write(&config, existing).expect("user config");
        assert_eq!(
            install_include(&config, include).expect("install"),
            IncludeOutcome::Installed
        );
        assert_eq!(
            std::fs::read_to_string(&config).expect("read"),
            format!("Include ~/.agent/ssh/config\n\n{existing}")
        );
        assert_eq!(
            install_include(&config, include).expect("repeat"),
            IncludeOutcome::AlreadyInstalled
        );

        // A copy scoped to a Host block does not apply to the Agent aliases, so the
        // global line is still added; the scoped copy is kept verbatim.
        let scoped = "Host x\n  Include ~/.agent/ssh/config\n";
        std::fs::write(&config, scoped).expect("scoped include");
        assert_eq!(
            install_include(&config, include).expect("scoped copy"),
            IncludeOutcome::Installed
        );
        assert_eq!(
            std::fs::read_to_string(&config).expect("read"),
            format!("Include ~/.agent/ssh/config\n\n{scoped}")
        );
        std::fs::write(&config, "  include ~/.agent/ssh/config\nMatch all\n").expect("indented global");
        assert_eq!(
            install_include(&config, "include ~/.agent/ssh/config").expect("indented global line counts"),
            IncludeOutcome::AlreadyInstalled
        );
    }

    #[cfg(unix)]
    #[test]
    fn include_install_follows_a_symlinked_user_config() {
        let directory = tempfile::tempdir().expect("temporary directory");
        let dotfiles = directory.path().join("dotfiles").join("ssh_config");
        std::fs::create_dir_all(dotfiles.parent().expect("parent")).expect("dotfiles");
        std::fs::write(&dotfiles, "Host github.com\n    User git\n").expect("managed config");
        let ssh = directory.path().join(".ssh");
        std::fs::create_dir_all(&ssh).expect(".ssh");
        let config = ssh.join("config");
        std::os::unix::fs::symlink(&dotfiles, &config).expect("symlink");

        assert_eq!(
            install_include(&config, "Include ~/.agent/ssh/config").expect("install"),
            IncludeOutcome::Installed
        );
        assert!(
            std::fs::symlink_metadata(&config)
                .expect("metadata")
                .file_type()
                .is_symlink()
        );
        assert_eq!(
            std::fs::read_to_string(&dotfiles).expect("managed config"),
            "Include ~/.agent/ssh/config\n\nHost github.com\n    User git\n"
        );
    }
}
