apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: github-runners
  namespace: default
spec:
  interval: 5m
  url: oci://altinntjenestercontainerregistry.azurecr.io/altinn-studio/configs/github-runners-repo
  ref:
    tag: ${ENVIRONMENT}
  provider: azure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-runners
  namespace: default
spec:
  interval: 5m
  targetNamespace: github-runners
  sourceRef:
    kind: OCIRepository
    name: github-runners
    namespace: default
  path: ./${ENVIRONMENT}
  prune: true
  timeout: 1m
