apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: studio-key-vault
  namespace: default
spec:
  interval: 5m
  url: oci://altinntjenestercontainerregistry.azurecr.io/altinn-studio/configs/studio-key-vault-repo
  ref:
    tag: ${ENVIRONMENT}
  provider: azure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: studio-key-vault
  namespace: default
spec:
  interval: 5m
  targetNamespace: default
  sourceRef:
    kind: OCIRepository
    name: studio-key-vault
    namespace: default
  path: ./
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      TENANT_ID: ${TENANT_ID}
      ESO_STUDIO_KV_CLIENT_ID: ${ESO_STUDIO_KV_CLIENT_ID}
      STUDIO_KV_URI: ${STUDIO_KV_URI}
