apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlay

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: observability-proxy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
