export enum ComponentType {
  Accordion = 'Accordion',
  AccordionGroup = 'AccordionGroup',
  ActionButton = 'ActionButton',
  Address = 'Address',
  Alert = 'Alert',
  AttachmentList = 'AttachmentList',
  Button = 'Button',
  ButtonGroup = 'ButtonGroup',
  Checkboxes = 'Checkboxes',
  Custom = 'Custom',
  CustomButton = 'CustomButton',
  Datepicker = 'Datepicker',
  Dropdown = 'Dropdown',
  FileUpload = 'FileUpload',
  FileUploadWithTag = 'FileUploadWithTag',
  Grid = 'Grid',
  Group = 'Group',
  // Keep Header for frontend v4 apps; frontend v9 uses Heading.
  Header = 'Header',
  Heading = 'Heading',
  IFrame = 'IFrame',
  Image = 'Image',
  ImageUpload = 'ImageUpload',
  Input = 'Input',
  InstanceInformation = 'InstanceInformation',
  InstantiationButton = 'InstantiationButton',
  Likert = 'Likert',
  Link = 'Link',
  List = 'List',
  Map = 'Map',
  MultipleSelect = 'MultipleSelect',
  NavigationBar = 'NavigationBar',
  NavigationButtons = 'NavigationButtons',
  // Keep the British-spelled type for frontend v4 apps; frontend v9 uses OrganizationLookup.
  OrganisationLookup = 'OrganisationLookup',
  OrganizationLookup = 'OrganizationLookup',
  Panel = 'Panel',
  Paragraph = 'Paragraph',
  Payment = 'Payment',
  PaymentDetails = 'PaymentDetails',
  PersonLookup = 'PersonLookup',
  PrintButton = 'PrintButton',
  RadioButtons = 'RadioButtons',
  RepeatingGroup = 'RepeatingGroup',
  Subform = 'Subform',
  Summary = 'Summary',
  Summary2 = 'Summary2',
  Text = 'Text',
  TextArea = 'TextArea',
  Divider = 'Divider',
}

export enum CustomComponentType {
  CloseSubformButton = 'CloseSubformButton',
}
