apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ConfigMap
      name: apps-runtime-common-config-env
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: apps-runtime-common-config-env
      data:
        PlatformSettings__ApiStorageEndpoint: https://platform.tt02.altinn.no/storage/api/v1/
        PlatformSettings__ApiRegisterEndpoint: https://platform.tt02.altinn.no/register/api/v1/
        PlatformSettings__ApiProfileEndpoint: https://platform.tt02.altinn.no/profile/api/v1/
        PlatformSettings__ApiAuthenticationEndpoint: https://platform.tt02.altinn.no/authentication/api/v1/
        PlatformSettings__ApiAuthorizationEndpoint: https://platform.tt02.altinn.no/authorization/api/v1/
        PlatformSettings__ApiEventsEndpoint: https://platform.tt02.altinn.no/events/api/v1/
        PlatformSettings__ApiNotificationEndpoint: https://platform.tt02.altinn.no/notifications/api/v1/
        PlatformSettings__ApiAccessManagementEndpoint: https://platform.tt02.altinn.no/accessmanagement/api/v1/
        PlatformSettings__ApiCorrespondenceEndpoint: https://platform.tt02.altinn.no/correspondence/api/v1/
        GeneralSettings__HostName: tt02.altinn.no
        PlatformFrontendSettings__LogoutUrl: https://platform.tt02.altinn.no/authentication/api/v1/logout
        PlatformFrontendSettings__LoginUrl: https://platform.tt02.altinn.no/authentication/api/v1/authentication?goto={goTo}
        PlatformFrontendSettings__UpgradeAuthenticationLevelUrl: https://platform.tt02.altinn.no/authentication/api/v1/authentication?goTo={goTo}&acr_values=idporten-loa-high
        PlatformFrontendSettings__ArbeidsflateInboxUrl: https://af.tt02.altinn.no/
        PlatformFrontendSettings__ArbeidsflateDialogUrl: https://af.tt02.altinn.no/inbox/{dialogId}
        PlatformFrontendSettings__ArbeidsflateProfileUrl: https://af.tt02.altinn.no/profile
        PlatformFrontendSettings__AccessManagementChangeAndRedirectUrl: https://am.ui.tt02.altinn.no/accessmanagement/api/v1/reportee/changeandredirect?partyId={partyId}&goTo={goTo}
        AppSettings__OpenIdWellKnownEndpoint: https://platform.tt02.altinn.no/authentication/api/v1/openid/
        ASPNETCORE_ENVIRONMENT: Staging
        AppSettings__EFormidlingSender: "991825827"
        EFormidlingClientSettings__BaseUrl: https://platform.tt02.altinn.no/eformidling/api/
  - target:
      kind: ConfigMap
      name: apps-runtime-common-config
    patch: |-
      - op: add
        path: /data/runtime-overrides.json
        value: |-
          {
            "PlatformSettings": {
              "ApiStorageEndpoint": "https://platform.tt02.altinn.no/storage/api/v1/",
              "ApiRegisterEndpoint": "https://platform.tt02.altinn.no/register/api/v1/",
              "ApiProfileEndpoint": "https://platform.tt02.altinn.no/profile/api/v1/",
              "ApiAuthenticationEndpoint": "https://platform.tt02.altinn.no/authentication/api/v1/",
              "ApiAuthorizationEndpoint": "https://platform.tt02.altinn.no/authorization/api/v1/",
              "ApiEventsEndpoint": "https://platform.tt02.altinn.no/events/api/v1/",
              "ApiNotificationEndpoint": "https://platform.tt02.altinn.no/notifications/api/v1/",
              "ApiAccessManagementEndpoint": "https://platform.tt02.altinn.no/accessmanagement/api/v1/",
              "ApiCorrespondenceEndpoint": "https://platform.tt02.altinn.no/correspondence/api/v1/"
            },
            "GeneralSettings": {
              "HostName": "tt02.altinn.no"
            },
            "PlatformFrontendSettings": {
              "LogoutUrl": "https://platform.tt02.altinn.no/authentication/api/v1/logout",
              "LoginUrl": "https://platform.tt02.altinn.no/authentication/api/v1/authentication?goto={goTo}",
              "UpgradeAuthenticationLevelUrl": "https://platform.tt02.altinn.no/authentication/api/v1/authentication?goTo={goTo}&acr_values=idporten-loa-high",
              "ArbeidsflateInboxUrl": "https://af.tt02.altinn.no/",
              "ArbeidsflateDialogUrl": "https://af.tt02.altinn.no/inbox/{dialogId}",
              "ArbeidsflateProfileUrl": "https://af.tt02.altinn.no/profile",
              "AccessManagementChangeAndRedirectUrl": "https://am.ui.tt02.altinn.no/accessmanagement/api/v1/reportee/changeandredirect?partyId={partyId}&goTo={goTo}"
            },
            "AppSettings": {
              "OpenIdWellKnownEndpoint": "https://platform.tt02.altinn.no/authentication/api/v1/openid/",
              "EFormidlingSender": "991825827"
            },
            "EFormidlingClientSettings": {
              "BaseUrl": "https://platform.tt02.altinn.no/eformidling/api/"
            },
            "ASPNETCORE_ENVIRONMENT": "Staging"
          }
