import type { ComponentCatalog, PropertyDefinition, PropertyValueDefinition } from '@app/layout-contract';

import { CG } from 'src/codegen/CG';
import { ComponentCatalogContext } from 'src/codegen/ComponentCatalogContext';
import type { SchemaFileProps } from 'src/codegen/SchemaFile';

type CatalogValue = ComponentCatalog | PropertyValueDefinition;

function propertyAccess(parent: string, property: string): string {
  return `${parent}[${JSON.stringify(property)}]`;
}

function indexPaths(value: unknown, path: string, paths: WeakMap<object, string>): void {
  if (typeof value !== 'object' || value === null || paths.has(value)) {
    return;
  }
  paths.set(value, path);
  for (const [key, child] of Object.entries(value)) {
    indexPaths(child, propertyAccess(path, key), paths);
  }
}

function renderValue(value: unknown, paths: WeakMap<object, string>, currentSymbol?: string): string {
  if (typeof value !== 'object' || value === null) {
    return JSON.stringify(value);
  }

  const path = paths.get(value);
  if (path && path !== currentSymbol && !path.startsWith(`${currentSymbol}[`)) {
    return path;
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => renderValue(item, paths, currentSymbol)).join(', ')}]`;
  }
  return `{ ${Object.entries(value)
    .map(([key, child]) => `${JSON.stringify(key)}: ${renderValue(child, paths, currentSymbol)}`)
    .join(', ')} }`;
}

function referencedSymbols(source: string, symbols: ReadonlyMap<string, PropertyValueDefinition>): Set<string> {
  return new Set([...symbols.keys()].filter((name) => new RegExp(`\\b${name}\\b`).test(source)));
}

export function generateComponentCatalog({ configMap, componentList, sortedKeys }: SchemaFileProps): {
  source: string;
  componentCatalog: ComponentCatalog;
  commonProperties: Readonly<Record<string, PropertyDefinition>>;
} {
  const { root, symbols } = ComponentCatalogContext.generate(() => {
    const components = sortedKeys
      .filter((key) => configMap[key].config.availability === 'configurable')
      .map((key) => [componentList[key], configMap[key].generateComponentCatalogEntry()] as const);
    return {
      componentCatalog: Object.fromEntries(components) satisfies ComponentCatalog,
      commonProperties: CG.common('ComponentBase').toComponentCatalog(),
      pageValidationDefinition: CG.common('PageValidation').toComponentCatalog(),
    };
  });

  const paths = new WeakMap<object, string>();
  for (const [name, definition] of symbols) {
    indexPaths(definition, name, paths);
  }

  const contract = root as {
    componentCatalog: ComponentCatalog;
    commonProperties: PropertyValueDefinition;
    pageValidationDefinition: PropertyValueDefinition;
  };
  const renderedRoot = renderValue(contract as Record<string, CatalogValue>, paths);
  const requiredSymbols = referencedSymbols(renderedRoot, symbols);
  for (const name of requiredSymbols) {
    const definition = symbols.get(name)!;
    for (const dependency of referencedSymbols(renderValue(definition, paths, name), symbols)) {
      requiredSymbols.add(dependency);
    }
  }
  const symbolDeclarations = [...symbols]
    .filter(([name]) => requiredSymbols.has(name))
    .map(([name, definition]) => `const ${name} = ${renderValue(definition, paths, name)} as const;`);

  return {
    source: [
      '// This file is generated by `yarn gen` in src/App/frontend. Do not edit manually.',
      '',
      "import type { ComponentCatalog, PropertyValueDefinition } from './types';",
      '',
      ...symbolDeclarations.map((declaration) => `${declaration}\n`),
      `const generatedContract = ${renderedRoot} as const;`,
      '',
      `export const componentCatalog = generatedContract.componentCatalog satisfies ComponentCatalog;`,
      `export const pageValidationDefinition = generatedContract.pageValidationDefinition satisfies PropertyValueDefinition;`,
    ].join('\n'),
    componentCatalog: contract.componentCatalog,
    commonProperties: contract.commonProperties.type === 'object' ? contract.commonProperties.properties : {},
  };
}
