const moduleName: string = 'APP_DEPLOYMENT';

export const GET_APP_DEPLOYMENTS: string = `${moduleName}.GET_APP_DEPLOYMENTS`;
export const GET_APP_DEPLOYMENTS_FULFILLED: string = `${moduleName}.GET_APP_DEPLOYMENTS_FULFILLED`;
export const GET_APP_DEPLOYMENTS_REJECTED: string = `${moduleName}.GET_APP_DEPLOYMENTS_REJECTED`;

export const GET_APP_DEPLOYMENTS_START_INTERVAL: string = `${moduleName}.GET_APP_DEPLOYMENTS_START_INTERVAL`;
export const GET_APP_DEPLOYMENTS_STOP_INTERVAL: string = `${moduleName}.GET_APP_DEPLOYMENTS_STOP_INTERVAL`;

export const CREATE_APP_DEPLOYMENT: string = `${moduleName}.CREATE_APP_DEPLOYMENT`;
export const CREATE_APP_DEPLOYMENT_FULFILLED: string = `${moduleName}.CREATE_APP_DEPLOYMENT_FULFILLED`;
export const CREATE_APP_DEPLOYMENT_REJECTED: string = `${moduleName}.CREATE_APP_DEPLOYMENT_REJECTED`;
