export enum AppNames {
  CREATE_APP_ONLY = 'simple-app-test',
  DATA_MODEL_APP = 'data-model-app-test',
  DATA_MODEL_V8_APP = 'data-model-v8-app-test',
  DASHBOARD_APP = 'dashboard-app-test',
  DASHBOARD_V8_APP = 'dashboard-v8-app-test',
  GIT_SYNC_APP = 'git-sync-app-test',
  GIT_SYNC_V8_APP = 'git-sync-v8-app-test',
  MAIN_NAVIGATION_APP = 'navigation-app-test',
  MAIN_NAVIGATION_V8_APP = 'navigation-v8-app-test',
  APP_SETTINGS_APP = 'app-settings-app-test',
  APP_SETTINGS_V8_APP = 'app-settings-v8-app-test',
  UI_EDITOR_APP = 'ui-editor-app-test',
  UI_EDITOR_V8_APP = 'ui-editor-v8-app-test',
  TEXT_EDITOR_APP = 'text-editor-app-test',
  TEXT_EDITOR_V8_APP = 'text-editor-v8-app-test',
  PROCESS_EDITOR_APP = 'process-editor-app-test',
  PROCESS_EDITOR_V8_APP = 'process-editor-v8-app-test',
  ORG_LIBRARY = 'org-library-app-test',
  ORG_LIBRARY_V8 = 'org-library-v8-app-test',
  BRANCHING_APP = 'branching-app-test',
  BRANCHING_V8_APP = 'branching-v8-app-test',
}
