export enum TestNames {
  SETUP = 'setup',
  CREATE_APP_ONLY = 'create-app-only',
  DATA_MODEL = 'data-model',
  DATA_MODEL_V8 = 'data-model-v8',
  DASHBOARD = 'dashboard',
  DASHBOARD_V8 = 'dashboard-v8',
  LOGOUT = 'logout',
  INVALID_LOGIN = 'invalid-login',
  MAIN_NAVIGATION_BETWEEN_SUB_APPS = 'main-navigation-between-sub-apps',
  MAIN_NAVIGATION_BETWEEN_SUB_APPS_V8 = 'main-navigation-between-sub-apps-v8',
  UI_EDITOR = 'ui-editor',
  UI_EDITOR_V8 = 'ui-editor-v8',
  GIT_SYNC = 'git-sync',
  GIT_SYNC_V8 = 'git-sync-v8',
  APP_SETTINGS = 'app-settings',
  APP_SETTINGS_V8 = 'app-settings-v8',
  TEXT_EDITOR = 'text-editor',
  TEXT_EDITOR_V8 = 'text-editor-v8',
  PROCESS_EDITOR = 'process-editor',
  PROCESS_EDITOR_V8 = 'process-editor-v8',
  ORG_LIBRARY = 'org-library',
  ORG_LIBRARY_V8 = 'org-library-v8',
  BRANCHING = 'branching',
  BRANCHING_V8 = 'branching-v8',
}
