export enum TestNames {
  SETUP = 'setup',
  CREATE_APP_ONLY = 'create-app-only',
  DATA_MODEL = 'data-model',
  DATA_MODEL_V9 = 'data-model-v9',
  DASHBOARD = 'dashboard',
  DASHBOARD_V9 = 'dashboard-v9',
  LOGOUT = 'logout',
  INVALID_LOGIN = 'invalid-login',
  MAIN_NAVIGATION_BETWEEN_SUB_APPS = 'main-navigation-between-sub-apps',
  MAIN_NAVIGATION_BETWEEN_SUB_APPS_V9 = 'main-navigation-between-sub-apps-v9',
  UI_EDITOR = 'ui-editor',
  UI_EDITOR_V9 = 'ui-editor-v9',
  GIT_SYNC = 'git-sync',
  GIT_SYNC_V9 = 'git-sync-v9',
  APP_SETTINGS = 'app-settings',
  APP_SETTINGS_V9 = 'app-settings-v9',
  TEXT_EDITOR = 'text-editor',
  TEXT_EDITOR_V9 = 'text-editor-v9',
  PROCESS_EDITOR = 'process-editor',
  PROCESS_EDITOR_V9 = 'process-editor-v9',
  ORG_LIBRARY = 'org-library',
  ORG_LIBRARY_V9 = 'org-library-v9',
  BRANCHING = 'branching',
  BRANCHING_V9 = 'branching-v9',
}
