CREATE ROLE gitea WITH LOGIN PASSWORD 'gitea';
CREATE ROLE designer WITH LOGIN PASSWORD 'designer';
CREATE DATABASE giteadb WITH OWNER gitea TEMPLATE template0 ENCODING UTF8 LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8';
CREATE DATABASE designerdb WITH OWNER designer TEMPLATE template0 ENCODING UTF8 LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8';
