import type { SimpleSubExpressionValueType } from '../enums/SimpleSubExpressionValueType';
import type { LogicalTupleOperator } from '../enums/LogicalTupleOperator';
import type { ExpressionErrorKey } from '../enums/ExpressionErrorKey';
import type { RelationalOperator } from './RelationalOperator';
import type { InstanceContext } from '../enums/InstanceContext';

export type ExpressionTexts = {
  addSubExpression: string;
  and: string;
  andOr: string;
  cannotSaveSinceInvalid: string;
  cannotSimplify: string;
  changeToSimplifiedWarning: string;
  componentId: string;
  confirmDeleteSubExpression: string;
  datamodelPath: string;
  delete: string;
  disabledLogicalOperator: string;
  edit: string;
  errorListFooter: string;
  errorListHeader: string;
  errorMessages: Record<ExpressionErrorKey, string>;
  false: string;
  firstOperand: string;
  instanceContext: Record<InstanceContext, string>;
  instanceContextKey: string;
  invalidExpression: string;
  logicalOperation: string;
  logicalOperator: string;
  logicalTupleOperators: Record<LogicalTupleOperator, string>;
  manual: string;
  or: string;
  readonlyComponentId: string;
  readonlyDatamodelPath: string;
  readonlyInstanceContext: string;
  relationalOperator: string;
  relationalOperators: Record<RelationalOperator, string>;
  save: string;
  saveAndClose: string;
  secondOperand: string;
  simplified: string;
  subExpression: (index: number) => string;
  transformToLogical: string;
  true: string;
  value: string;
  valueType: string;
  valueTypes: Record<SimpleSubExpressionValueType, string>;
};
