export enum QueryKey {
  AppDeployments = 'AppDeployments',
  AppReleases = 'AppReleases',
  BranchStatus = 'BranchStatus',
  CurrentUser = 'CurrentUser',
  Datamodel = 'Datamodel',
  DatamodelMetadata = 'DatamodelMetadata',
  DatamodelsMetadata = 'DatamodelsMetadata',
  DatamodelsXsd = 'DatamodelsXsd',
  DeployPermissions = 'DeployPermissions',
  Environments = 'Environments',
  FormLayoutSettings = 'FormLayoutSettings',
  FormLayouts = 'FormLayouts',
  InstanceId = 'InstanceId',
  LayoutSets = 'LayoutSets',
  OrgList = 'OrgList',
  Organizations = 'Organizations',
  RepoMetaData = 'RepoMetaData',
  RepoPullData = 'RepoPullData',
  RepoReset = 'RepoReset',
  RepoStatus = 'RepoStatus',
  RuleConfig = 'RuleConfig',
  RuleHandler = 'RuleHandler',
  SearchRepos = 'SearchRepos',
  StarredRepos = 'StarredRepos',
  TextLanguages = 'TextLanguages',
  TextResources = 'TextResources',
  Widgets = 'Widgets',
  OptionListIds = 'OptionListIds',

  // Resourceadm
  ResourcePolicy = 'ResourcePolicy',
  ResourcePolicyActions = 'ResourcePolicyActions',
  ResourcePolicySubjects = 'ResourcePolicySubjects',
  ResourcePublishStatus = 'ResourcePublishStatus',
  ResourceList = 'ResourceList',
  SingleResource = 'SingleResource',
  ValidatePolicy = 'ValidatePolicy',
  ValidateResource = 'ValidateResource',
  ResourceSectors = 'ResourceSectors',
  ResourceThematicLos = 'ResourceThematicLos',
  ResourceThematicEurovoc = 'ResourceThematicEurovoc'
}
