export enum QueryKey {
  AppDeployments = 'AppDeployments',
  AppPolicy = 'AppPolicy',
  AppReleases = 'AppReleases',
  BranchStatus = 'BranchStatus',
  CurrentUser = 'CurrentUser',
  DatamodelMetadata = 'DatamodelMetadata',
  DatamodelsJson = 'DatamodelsJson',
  DatamodelsMetadata = 'DatamodelsMetadata',
  DatamodelsXsd = 'DatamodelsXsd',
  DeployPermissions = 'DeployPermissions',
  Environments = 'Environments',
  FetchBpmn = 'FetchBpmn',
  FormComponent = 'FormComponent',
  FormLayoutSettings = 'FormLayoutSettings',
  FormLayouts = 'FormLayouts',
  InstanceId = 'InstanceId',
  JsonSchema = 'JsonSchema',
  LayoutSchema = 'LayoutSchema',
  LayoutSets = 'LayoutSets',
  OptionListIds = 'OptionListIds',
  OrgList = 'OrgList',
  Organizations = 'Organizations',
  RepoMetaData = 'RepoMetaData',
  RepoPullData = 'RepoPullData',
  RepoReset = 'RepoReset',
  RepoStatus = 'RepoStatus',
  RuleConfig = 'RuleConfig',
  RuleHandler = 'RuleHandler',
  SearchRepos = 'SearchRepos',
  StarredRepos = 'StarredRepos',
  TextLanguages = 'TextLanguages',
  TextResources = 'TextResources',
  Widgets = 'Widgets',

  // Resourceadm
  ResourceList = 'ResourceList',
  ResourcePolicy = 'ResourcePolicy',
  ResourcePolicyActions = 'ResourcePolicyActions',
  ResourcePolicySubjects = 'ResourcePolicySubjects',
  ResourcePublishStatus = 'ResourcePublishStatus',
  ResourceSectors = 'ResourceSectors',
  ResourceThematicEurovoc = 'ResourceThematicEurovoc',
  ResourceThematicLos = 'ResourceThematicLos',
  SingleResource = 'SingleResource',
  ValidatePolicy = 'ValidatePolicy',
  ValidateResource = 'ValidateResource',
}
