export enum QueryKey {
  AppDeployments = 'AppDeployments',
  AppReleases = 'AppReleases',
  BranchStatus = 'BranchStatus',
  CurrentUser = 'CurrentUser',
  Datamodel = 'Datamodel',
  DatamodelsXsd = 'DatamodelsXsd',
  DeployPermissions = 'DeployPermissions',
  Environments = 'Environments',
  FormLayoutSettings = 'FormLayoutSettings',
  FormLayouts = 'FormLayouts',
  InstanceId = 'InstanceId',
  LayoutSets = 'LayoutSets',
  OrgList = 'OrgList',
  Organizations = 'Organizations',
  RepoMetaData = 'RepoMetaData',
  RepoPullData = 'RepoPullData',
  RepoStatus = 'RepoStatus',
  RuleConfig = 'RuleConfig',
  RuleHandler = 'RuleHandler',
  SearchRepos = 'SearchRepos',
  StarredRepos = 'StarredRepos',
  TextLanguages = 'TextLanguages',
  TextResources = 'TextResources',
  Widgets = 'Widgets',
}
