const moduleName = 'APPLICATION_METADATA';

export const FETCH_APPLICATION_METADATA = `${moduleName}.FETCH_APPLICATION_METADATA`;
export const FETCH_APPLICATION_METADATA_FULFILLED = `${moduleName}.FETCH_APPLICATION_METADATA_FULFILLED`;
export const FETCH_APPLICATION_METADATA_REJECTED = `${moduleName}.FETCH_APPLICATION_METADATA_REJECTED`;
