apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: ${DISDB_METANAME}
  namespace: studio-admin
spec:
  name: ${DISDB_PGNAME}
  server:
    name: workflow-engine-db-server
  access:
    principals:
      - role: Owner
        servicePrincipal:
          name: ${DISDB_GRANTEE_NAME}
          principalId: "${DISDB_GRANTEE_OID}"
  deletionPolicy: Retain
