FROM ubuntu:24.04@sha256:224a1869083a311ef3f13648a154ba79832fbef6364d31493642ca03082da254

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        mdadm \
        nvme-cli \
        util-linux \
        xfsprogs \
    && rm -rf /var/lib/apt/lists/*

COPY --chmod=0755 init-storage.sh /usr/local/bin/init-storage

ENTRYPOINT ["/usr/local/bin/init-storage"]
