apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-runtime-common-config-env
  namespace: default
data:
  ServiceRepositorySettings__BaseResourceFolderContainer: /AltinnService/
  ServiceRepositorySettings__RepositoryLocation: /AltinnService/
  PdfGeneratorSettings__ServiceEndpointUri: http://pdf-generator.pdf.svc.cluster.local/pdf
  PlatformSettings__ApiPdf2Endpoint: http://pdf-generator.pdf.svc.cluster.local/pdf
  PlatformSettings__ApiWorkflowEngineEndpoint: http://workflow-engine-app.runtime-workflow-engine-app.svc.cluster.local/api/v1/workflows/
  GeneralSettings__ExternalAppBaseUrl: https://{org}.apps.{hostName}/{org}/{app}/
  PlatformFrontendSettings__PostalCodesUrl: https://altinncdn.no/postcodes/registry.json
---
apiVersion: v1
kind: Secret
metadata:
  name: apps-runtime-common-secrets-env
  namespace: default
type: Opaque
