import type { HTMLInputAutoCompleteAttribute, HTMLInputTypeAttribute } from 'react';

export type InputType = Extract<
  HTMLInputTypeAttribute,
  'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url'
>;

export const EXTERNAL_INPUT_TYPE = ['text', 'search'] satisfies InputType[];

export const INPUT_AUTO_COMPLETE: HTMLInputAutoCompleteAttribute[] = [
  'on',
  'off',
  'name',
  'honorific-prefix',
  'given-name',
  'additional-name',
  'family-name',
  'honorific-suffix',
  'nickname',
  'email',
  'username',
  'new-password',
  'current-password',
  'one-time-code',
  'organization-title',
  'organization',
  'street-address',
  'address-line1',
  'address-line2',
  'address-line3',
  'address-level4',
  'address-level3',
  'address-level2',
  'address-level1',
  'country',
  'country-name',
  'postal-code',
  'cc-name',
  'cc-given-name',
  'cc-additional-name',
  'cc-family-name',
  'cc-number',
  'cc-exp',
  'cc-exp-month',
  'cc-exp-year',
  'cc-csc',
  'cc-type',
  'transaction-currency',
  'transaction-amount',
  'language',
  'bday',
  'bday-day',
  'bday-month',
  'bday-year',
  'sex',
  'tel',
  'tel-country-code',
  'tel-national',
  'tel-area-code',
  'tel-local',
  'tel-extension',
  'url',
  'photo',
];
