# Keep src/ build context minimal for gateway image.
**
!common/Altinn.Studio.Runtime.Common.csproj
!common/src/**
!Runtime/gateway/Directory.Packages.props
!Runtime/gateway/src/Altinn.Studio.Gateway.Api/**
!Runtime/gateway/src/Altinn.Studio.Gateway.Contracts/**
**/bin
**/obj
