const moduleName: string = 'DATA_TASK_QUEUE';

export const START_INITIAL_DATA_TASK_QUEUE: string = `${moduleName}.START_INITIAL_DATA_TASK_QUEUE`;
export const START_INITIAL_DATA_TASK_QUEUE_FULFILLED: string = `${moduleName}.START_INITIAL_DATA_TASK_QUEUE_FULFILLED`;
