using AltinnCore.ServiceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AltinnCoreServiceImplementation.Template
{{
    /// <summary>
    /// This is the Template ServiceImplementation that handles the service events
    /// </summary>
    public class GeneratedMethods
    {{
		#region Internal properties
        private IPlatformServices platformServices;

        private SERVICE_MODEL_NAME SERVICE_MODEL_NAME;

        private RequestContext requestContext;

		#endregion
		
        public GeneratedMethods(IPlatformServices platformServices, SERVICE_MODEL_NAME SERVICE_MODEL_NAME, RequestContext requestContext)	
        {{
			this.platformServices = platformServices;
			this.SERVICE_MODEL_NAME = SERVICE_MODEL_NAME;
			this.requestContext = requestContext;
        }}

		#region Service event handles
        public void HandleBeforeRenderEvent()
        {{
			// Autogenerated rules that should run during the calculation event
			{0}
        }}

        public void HandleCalculationEvent()
        {{
			// Autogenerated rules that should run during the calculation event
			{1}
        }}

        public void HandleInstansiationEvent(ServiceContext serviceContext)
        {{
			// Autogenerated rules that should run during the calculation event
			{2}
        }}

        public void HandleValidateInstansiationEvent(StartServiceModel startServiceModel, ModelStateDictionary modelState)
        {{
			// Autogenerated rules that should run during the calculation event
			{3}
        }}

        public void HandleValidationEvent(ModelStateDictionary modelState)
        {{
			// Autogenerated rules that should run during the calculation event
			{4}
        }}
		#endregion
		
		#region Auto-generated utility methods
		{5}
		#endregion
    }}
}}
