const moduleName = 'PROCESS';

export const GET_PROCESS_STATE = `${moduleName}.GET_PROCESS_STATE`;
export const GET_PROCESS_STATE_FULFILLED = `${moduleName}.GET_PROCESS_STATE_FULFILLED`;
export const GET_PROCESS_STATE_REJECTED = `${moduleName}.GET_PROCESS_STATE_REJECTED`;

export const START_PROCESS = `${moduleName}.START_PROCESS`;
export const START_PROCESS_FULFILLED = `${moduleName}.START_PROCESS_FULFILLED`;
export const START_PROCESS_REJECTED = `${moduleName}.START_PROCESS_REJECTED`;

export const COMPLETE_PROCESS = `${moduleName}.COMPLETE_PROCESS`;
export const COMPLETE_PROCESS_FULFILLED = `${moduleName}.COMPLETE_PROCESS_FULFILLED`;
export const COMPLETE_PROCESS_REJECTED = `${moduleName}.COMPLETE_PROCESS_REJECTED`;

export const CHECK_PROCESS_UPDATED = `${moduleName}.CHECK_PROCESS_UPDATED`;
