<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="../Directory.Build.props" />
  <Import Project="$(MSBuildThisFileDirectory)../../PackageVersioning.props" />
  <Import Project="$(MSBuildThisFileDirectory)../../AppCoreDependency.props" />

  <ItemGroup>
    <None Include="../../README.md" Link="README.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)../../../../LICENSE" Link="LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

  <PropertyGroup>
    <AnalysisMode>Recommended</AnalysisMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RepoRoot>$([System.IO.Directory]::GetParent($(MSBuildThisFileDirectory)).Parent.FullName)</RepoRoot>

    <PackageVersionTagPrefix>codelists/v</PackageVersionTagPrefix>
    <PackageDefaultBaseVersion>9.0.0-preview.0</PackageDefaultBaseVersion>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Altinn Platform Contributors</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Altinn/altinn-studio</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition="'$(Deterministic)'=='true'">
    <SourceRoot Include="$(MSBuildThisFileDirectory)/" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Deterministic)'=='true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
