apiVersion: batch/v1
kind: CronJob
metadata:
  name: runner-org-sync
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: runner-org-sync
              env:
                - name: RUNNER_ORG_SYNC_ORGS
                  value: "ttd,brg,dsb,ssb,ksdigi,pat,dibk,skm,sfvt"
                - name: RUNNER_ORG_SYNC_KEYVAULT_NAME
                  value: "altinn-studio-prod-kv"
                - name: OTEL_RESOURCE_ATTRIBUTES
                  value: "service.namespace=studio-runners,deployment.environment=prod"
