import type { DataModelMetadataResponse } from 'app-shared/types/api/DataModelMetadataResponse';

export const dataModelMetadataMock: DataModelMetadataResponse = {
  elements: {
    defaultModel: {
      id: 'defaultModel',
      type: 'ComplexType',
      dataBindingName: null,
      displayString: 'defaultModel',
      isReadOnly: false,
      isTagContent: false,
      jsonSchemaPointer: '#/definitions/defaultModel',
      maxOccurs: 1,
      minOccurs: 1,
      name: 'defaultModel',
      parentElement: null,
      restrictions: [],
      texts: [],
      xmlSchemaXPath: '/defaultModel',
      xPath: '/defaultModel',
    },
    'defaultModel.field1': {
      id: 'defaultModel.field1',
      type: 'SimpleType',
      dataBindingName: 'field1',
      displayString: 'defaultModel.field1',
      isReadOnly: false,
      isTagContent: false,
      jsonSchemaPointer: '#/definitions/defaultModel/properties/field1',
      maxOccurs: 1,
      minOccurs: 1,
      name: 'field1',
      parentElement: 'defaultModel',
      restrictions: [],
      texts: [],
      xmlSchemaXPath: '/defaultModel/field1',
      xPath: '/defaultModel/field1',
    },
    'defaultModel.field2': {
      id: 'defaultModel.field2',
      type: 'SimpleType',
      dataBindingName: 'field2',
      displayString: 'defaultModel.field2',
      isReadOnly: false,
      isTagContent: false,
      jsonSchemaPointer: '#/definitions/defaultModel/properties/field2',
      maxOccurs: 1,
      minOccurs: 1,
      name: 'field2',
      parentElement: 'defaultModel',
      restrictions: [],
      texts: [],
      xmlSchemaXPath: '/defaultModel/field2',
      xPath: '/defaultModel/field2',
    },
  },
};
