# Container images for studioctl
# This file is embedded in the binary as defaults
# Renovate will automatically update image tags in the repository version

images:
  core:
    localtest:
      image: ghcr.io/altinn/altinn-studio/runtime-localtest
      tag: "4b5f3ee16a"
    pdf3:
      image: ghcr.io/altinn/altinn-studio/runtime-pdf3-worker
      tag: "b885f9a75f"
    workflow-engine:
      image: ghcr.io/altinn/altinn-studio/runtime-workflow-engine-app
      tag: "2fefe03efb"
    workflow-engine-db:
      image: postgres
      tag: "18.3"
    pgadmin:
      image: dpage/pgadmin4
      tag: "9.14"

  monitoring:
    tempo:
      image: grafana/tempo
      tag: "2.4.1"
    mimir:
      image: grafana/mimir
      tag: "2.12.0"
    loki:
      image: grafana/loki
      tag: "3.0.0"
    otel-collector:
      image: otel/opentelemetry-collector-contrib
      tag: "0.98.0"
    grafana:
      image: grafana/grafana
      tag: "10.4.2"
