apiVersion: agents.platform/v1alpha1
kind: AgentVariant
extends: agent.nested.yaml

metadata:
  name: altinn-full-nested-build

spec:
  sandbox:
    image:
      type: build
      context: ..
      dockerfile: Dockerfile
