package internal

import "errors"

var (
	errContextRequired        = errors.New("context is required")
	errComponentRequired      = errors.New("component is required")
	errBaseBranchRequired     = errors.New("base branch is required")
	errRepoRootRequired       = errors.New("repo root is required")
	errGitRequired            = errors.New("git client is required")
	errGitHubRequired         = errors.New("github client is required")
	errNoGitRemotes           = errors.New("repository has no git remotes")
	errPushRemoteAmbiguous    = errors.New("git push remote is ambiguous")
	errPushRemoteMissing      = errors.New("configured git push remote does not exist")
	errPushRemoteMultipleURLs = errors.New("git push remote has multiple push URLs")
	errCanonicalRemoteMissing = errors.New("canonical GitHub repository has no matching git remote")
	errCanonicalPushMismatch  = errors.New("canonical remote pushes to a different repository")
	errRepositoryHostMismatch = errors.New("push repository is not hosted on github.com")
	errRepositoryURLInvalid   = errors.New("invalid GitHub repository URL")
	errChangelogNil           = errors.New("changelog is required")
	errReleaseVersionRequired = errors.New("version or release kind is required")
	errReleaseVersionConflict = errors.New("version and release kind cannot be combined")
	errReleaseKindInvalid     = errors.New("invalid release kind (expected prerelease, stabilization, or patch)")
	errReleaseLineRequired    = errors.New("release line is required (e.g., v1.0)")
	errReleaseLineConflict    = errors.New("conflicting release line input")
	errNoActivePrereleaseLine = errors.New("no active prerelease release line found")
	errPrereleaseSeqInvalid   = errors.New("active prerelease version must end with numeric prerelease identifier")
	errPrereleaseLineOpen     = errors.New("active prerelease line has not entered stabilization")
	errPrereleaseLineNotNewer = errors.New("planned prerelease line must be newer than the active line")
	errPrereleaseLineClosed   = errors.New("prerelease line is already stabilizing or stable")
	errStabilizationMismatch  = errors.New("stabilization candidate differs between main and release branch")
	errValidationBaseRequired = errors.New("base commit is required")
	errValidationHeadRequired = errors.New("head commit is required")
	errChangelogVersionExists = errors.New("version already exists in changelog")
	errReleaseBranchMissing   = errors.New("release branch does not exist for patch release")
	errBackportCommitRequired = errors.New("commit SHA is required")
	errBackportBranchRequired = errors.New("release line is required (e.g., v1.0)")
	errBackportNoEntries      = errors.New("no changelog entries found in commit")
	errReleaseLineInvalid     = errors.New("invalid release line format (expected vX.Y)")
	errUnsafeCleanDirPath     = errors.New("refusing to clean unsafe directory path")
	errUnsafeReleaseNotesPath = errors.New("release notes intro path outside repo root")
	errNoExistingParentPath   = errors.New("path has no existing parent directory")
	errPromptIORequired       = errors.New("prompt input/output is required")

	// ErrActionNotConfirmed indicates a user declined a confirmation prompt.
	ErrActionNotConfirmed = errors.New("action not confirmed")
)
