apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics-oci
  namespace: victoriametrics-operator
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/victoriametrics/helm-charts
