/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;

namespace Altinn.Studio.Designer.RepositoryClient.Model
{
    /// <summary>
    /// PayloadCommitVerification represents the GPG verification of a commit
    /// </summary>
    [DataContract]
    public partial class PayloadCommitVerification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadCommitVerification"/> class.
        /// </summary>
        public PayloadCommitVerification()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadCommitVerification" /> class.
        /// </summary>
        /// <param name="Payload">Payload.</param>
        /// <param name="Reason">Reason.</param>
        /// <param name="Signature">Signature.</param>
        /// <param name="Verified">Verified.</param>
        public PayloadCommitVerification(string Payload = default(string), string Reason = default(string), string Signature = default(string), bool? Verified = default(bool?))
        {
            this.Payload = Payload;
            this.Reason = Reason;
            this.Signature = Signature;
            this.Verified = Verified;
        }
        
        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [DataMember(Name="payload", EmitDefaultValue=false)]
        public string Payload { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public string Signature { get; set; }

        /// <summary>
        /// Gets or Sets Verified
        /// </summary>
        [DataMember(Name="verified", EmitDefaultValue=false)]
        public bool? Verified { get; set; }
    }
}
