using Altinn.Studio.Cli.Upgrade.v8Tov9.CSharpApiMigration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Altinn.Studio.Cli.Upgrade.v8Tov9;

/// <summary>
/// Removes <c>using</c> directives that import a namespace the project already imports globally, be it
/// through the SDK's implicit usings or a <c>Using</c> item in the project file. A file-level duplicate
/// of a global using only earns a hidden diagnostic, so this is a tidy-up, not a fix: every removal must
/// be provably redundant, and formatting around the removed lines is kept intact.
/// </summary>
internal sealed class RedundantUsingDirectiveMigration
{
    private const string GlobalAliasPrefix = "global::";

    private readonly CSharpSourceScanner _scanner;
    private readonly IReadOnlySet<string> _globalNamespaces;

    public RedundantUsingDirectiveMigration(CSharpSourceScanner scanner, IReadOnlySet<string> globalNamespaces)
    {
        _scanner = scanner;
        _globalNamespaces = globalNamespaces;
    }

    /// <returns>The number of files that were rewritten.</returns>
    public int Migrate()
    {
        var changedFiles = 0;
        // Update replaces the file instance in the scanner, so iterate over a snapshot of the list.
        foreach (var file in _scanner.Files.ToArray())
        {
            if (IsGeneratedModel(file))
                continue;

            var redundant = FindRedundant(file).ToArray();
            if (redundant.Length == 0)
                continue;

            _scanner.Update(file, Remove(file.Root, redundant));
            UpgradeConsole.Ok($"Removed {redundant.Length} redundant using directive(s) in {file.Path}");
            changedFiles++;
        }

        return changedFiles;
    }

    /// <summary>
    /// The data model classes under <c>models/</c> are generated by Studio, which writes every using
    /// directive back on the next regeneration. Cleaning them up would only produce churn, so they are
    /// left alone; Studio marks them as generated code, which keeps analyzers quiet about the directives.
    /// </summary>
    private static bool IsGeneratedModel(ScannedCSharpFile file)
    {
        var firstSegment = file.RelativePath.Split(['/', '\\'], 2)[0];
        return string.Equals(firstSegment, "models", StringComparison.OrdinalIgnoreCase);
    }

    private IEnumerable<UsingDirectiveSyntax> FindRedundant(ScannedCSharpFile file)
    {
        foreach (var directive in file.Root.DescendantNodes().OfType<UsingDirectiveSyntax>())
        {
            // Aliases and static imports are not namespace imports; a 'global using' in the app's own
            // source duplicates the project-level one exactly like a file-level directive does.
            if (directive.Alias is not null || directive.StaticKeyword.IsKind(SyntaxKind.StaticKeyword))
                continue;

            if (directive.Name is null || !_globalNamespaces.Contains(NormalizedName(directive.Name)))
                continue;

            if (IsGlobalNamespaceImport(file, directive))
                yield return directive;
        }
    }

    /// <summary>
    /// A directive at the top of the file resolves from the global namespace, so its text alone
    /// identifies the namespace. Inside a namespace declaration the same text may bind to a nested
    /// namespace instead (<c>using Models;</c> inside <c>Altinn.App</c> is <c>Altinn.App.Models</c>),
    /// so those are removed only when the semantic model confirms the binding.
    /// </summary>
    private static bool IsGlobalNamespaceImport(ScannedCSharpFile file, UsingDirectiveSyntax directive)
    {
        if (directive.Parent is CompilationUnitSyntax)
            return true;

        if (directive.Name is null || file.SemanticModel is not { } model)
            return false;

        return model.GetSymbolInfo(directive.Name).Symbol is INamespaceSymbol ns
            && string.Equals(ns.ToDisplayString(), NormalizedName(directive.Name), StringComparison.Ordinal);
    }

    private static string NormalizedName(NameSyntax name)
    {
        var text = name.WithoutTrivia().ToString();
        // ToString keeps trivia between name parts ("System . Linq"), and 'global::' says nothing
        // about which namespace is meant.
        text = string.Concat(text.Where(c => !char.IsWhiteSpace(c)));
        return text.StartsWith(GlobalAliasPrefix, StringComparison.Ordinal) ? text[GlobalAliasPrefix.Length..] : text;
    }

    private static CompilationUnitSyntax Remove(CompilationUnitSyntax root, UsingDirectiveSyntax[] directives)
    {
        var tracked = root.TrackNodes(directives);
        foreach (var directive in directives)
        {
            var current = Current(tracked, directive);

            // The directive's own line goes, but not a comment or preprocessor directive (such as
            // '#nullable enable') on the lines above it, nor a comment after it on the same line. Those
            // are handed to whatever follows, minus the whitespace that separated them from the code.
            var carriedLeading = current.GetLeadingTrivia().Any(static trivia => !IsBlank(trivia))
                ? current.GetLeadingTrivia()
                : SyntaxTriviaList.Empty;
            var carriedTrailing = current
                .GetTrailingTrivia()
                .Any(static trivia => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
                ? new SyntaxTriviaList(
                    current.GetTrailingTrivia().Where(static trivia => !trivia.IsKind(SyntaxKind.WhitespaceTrivia))
                )
                : SyntaxTriviaList.Empty;

            var options = SyntaxRemoveOptions.KeepNoTrivia;
            if (carriedLeading.Count > 0 || carriedTrailing.Count > 0)
            {
                tracked = tracked.ReplaceNode(
                    current,
                    current.WithLeadingTrivia(carriedLeading).WithTrailingTrivia(carriedTrailing)
                );
                current = Current(tracked, directive);
                options = SyntaxRemoveOptions.KeepExteriorTrivia;
            }

            tracked =
                tracked.RemoveNode(current, options)
                ?? throw new InvalidOperationException("Failed to remove using directive");
        }

        return TrimLeadingBlankLines(tracked);
    }

    private static UsingDirectiveSyntax Current(CompilationUnitSyntax tracked, UsingDirectiveSyntax original) =>
        tracked.GetCurrentNode(original) ?? throw new InvalidOperationException("Failed to track using directive");

    /// <summary>
    /// Removing the first directive of a file leaves the blank line that separated it from what
    /// follows at the very top of the file. A file does not start with blank lines, so drop them.
    /// </summary>
    private static CompilationUnitSyntax TrimLeadingBlankLines(CompilationUnitSyntax root)
    {
        var firstToken = root.GetFirstToken(includeZeroWidth: true);
        var leading = firstToken.LeadingTrivia;

        var blankCount = 0;
        var lastLineBreak = -1;
        while (blankCount < leading.Count && IsBlank(leading[blankCount]))
        {
            if (leading[blankCount].IsKind(SyntaxKind.EndOfLineTrivia))
                lastLineBreak = blankCount;
            blankCount++;
        }

        if (lastLineBreak < 0)
            return root;

        var trimmed = new SyntaxTriviaList(leading.Skip(lastLineBreak + 1));
        return root.ReplaceToken(firstToken, firstToken.WithLeadingTrivia(trimmed));
    }

    private static bool IsBlank(SyntaxTrivia trivia) =>
        trivia.IsKind(SyntaxKind.WhitespaceTrivia) || trivia.IsKind(SyntaxKind.EndOfLineTrivia);
}
