apiVersion: agents.platform/v1alpha1
kind: AgentVariant
extends: agent.yaml

metadata:
  name: agent-dev-nested

spec:
  sandbox:
    resources:
      cpu: "2"
      memory: "3Gi"
      rootFilesystem:
        capacity: "16Gi"
        mode: direct
