{
 "title": "ASP.NET Core Endpoint",
 "description": "ASP.NET Core endpoint metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({\"http.server.active_requests\"}, \"service.name\")"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({\"http.server.active_requests\", \"service.name\"=~\"$service\"}, \"service.instance.id\")"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({\"http.server.request.duration_count\"}, \"http.route\")"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values({\"http.server.request.duration_count\", \"http.route\"=~\"$route\"}, \"http.request.method\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration - $method $route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate({\"http.server.request.duration_bucket\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - $method $route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\", \"http.response.status_code\"=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\", \"http.response.status_code\"=~\"4..\"}[5m]) or vector(0)) / sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\", \"http.response.status_code\"=~\"5..\"}[5m]) or vector(0)) / sum(rate({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Unhandled Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (\"error.type\") (\r\n  max_over_time({\"http.server.request.duration_count\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\", \"error.type\"!=\"\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (\"http.response.status_code\") (\r\n    max_over_time({\"http.server.request.duration_count\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http.response.status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (\"url.scheme\") (\r\n    max_over_time({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time({\"http.server.request.duration_count\", \"service.name\"=\"$service\", \"service.instance.id\"=\"$instance\", \"http.route\"=\"$route\", \"http.request.method\"=\"$method\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network.protocol.version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}