apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scaledjob.yaml
  - triggerauthentication.yaml
replacements:
  - source:
      kind: ScaledJob
      name: github-runners
      fieldPath: metadata.annotations.[altinn.studio/image]
    targets:
      - select:
          kind: ScaledJob
          name: github-runners
        fieldPaths:
          - spec.jobTargetRef.template.spec.containers.[name=github-runner].image
