// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Altinn.App.Models
{
    [XmlRoot("bestilling")]
    public class Bestilling
    {
        [XmlAttribute("orderid")]
        public string orderid { get; set; }
        [XmlElement("dato")]
        public DateTime dato { get; set; }
        [XmlElement("referanse")]
        public string referanse { get; set; }
        [XmlElement("postadresse")]
        public Adresse postadresse { get; set; }
        [XmlElement("ordrelinje")]
        public List<Ordrelinje> ordrelinje { get; set; }
    }
    public class Adresse
    {
        [XmlElement("navn")]
        public string navn { get; set; }
        [XmlElement("adresse")]
        public string adresse { get; set; }
        [Range(Int32.MinValue, Int32.MaxValue)]
        [XmlElement("postNummber")]
        public decimal postNummber { get; set; }
        [XmlElement("postSted")]
        public string postSted { get; set; }
    }
    public class Ordrelinje
    {
        [XmlElement("produkt")]
        public string produkt { get; set; }
        [XmlElement("note")]
        public string note { get; set; }
        [Range(1, Int32.MaxValue)]
        [XmlElement("antall")]
        public decimal antall { get; set; }
        [XmlElement("pris")]
        public decimal pris { get; set; }
    }
}

