apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: altinn-altinity-agents-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: studio-key-vault
  target:
    name: altinn-altinity-agents-eso-secret
    creationPolicy: Owner
  data:
    - secretKey: AZURE_API_KEY
      remoteRef:
        key: agent-azure-api-key
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: agent-langfuse-secret-key
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: agent-langfuse-public-key
    - secretKey: LANGFUSE_BASE_URL
      remoteRef:
        key: agent-langfuse-base-url
    - secretKey: LANGFUSE_ENVIRONMENT
      remoteRef:
        key: agent-langfuse-environment
