ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

ssl_certificate /etc/nginx/ssl/altinn_studio/star.altinn.studio.cert;
ssl_certificate_key /etc/nginx/ssl/altinn_studio/star.altinn.studio.key;

ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /etc/nginx/ssl/altinn_studio/star.altinn.studio.cert;

ssl_session_cache shared:SSL:40m;
ssl_session_timeout 4h;
ssl_session_tickets on;

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
