// <auto-generated />

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

using System.Reflection;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers.Internal;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using AltinnCore.ServiceLibrary.Services.Interfaces;

namespace AltinnCore.Designer.TagHelpers
{
    /// <summary>
    /// <see cref="ITagHelper"/> implementation targeting &lt;select&gt; elements with <c>asp-for</c> and/or
    /// <c>asp-items</c> attribute(s).
    /// This is a modification of the Standard Select Tag Helper in ASP.Net Core MVC 1.0.1 that supports getting CodeLists
    /// from AltinnCore repo
    /// </summary>
    [HtmlTargetElement("select", Attributes = ForAttributeName)]
    [HtmlTargetElement("select", Attributes = ItemsAttributeName)]
    public class SelectTagHelper : TagHelper
    {
        private const string ForAttributeName = "altinn-for";
        private const string ItemsAttributeName = "altinn-items";
        private const string CodeValueAttributeName = "altinn-value-name";
        private const string CodeTextAttributeName = "altinn-text-name";
        private bool _allowMultiple;
        private ICollection<string> _currentValues;

        /// <summary>
        /// Creates a new <see cref="SelectTagHelper"/>.
        /// </summary>
        /// <param name="generator">The <see cref="IHtmlGenerator"/>.</param>
        public SelectTagHelper(IHtmlGenerator generator)
        {
            Generator = generator;
        }

        /// <inheritdoc />
        public override int Order
        {
            get
            {
                return -1000;
            }
        }

        /// <summary>
        /// The generator
        /// </summary>
        protected IHtmlGenerator Generator { get; }

        /// <summary>
        /// The view context
        /// </summary>
        [HtmlAttributeNotBound]
        [ViewContext]
        public ViewContext ViewContext { get; set; }

        /// <summary>
        /// An expression to be evaluated against the current model.
        /// </summary>
        [HtmlAttributeName(ForAttributeName)]
        public ModelExpression For { get; set; }

        /// <summary>
        /// A collection of <see cref="SelectListItem"/> objects used to populate the &lt;select&gt; element with
        /// &lt;optgroup&gt; and &lt;option&gt; elements.
        /// </summary>
        [HtmlAttributeName(ItemsAttributeName)]
        public string CodeList { get; set; }

        /// <summary>
        /// The value name
        /// </summary>
        [HtmlAttributeName(CodeValueAttributeName)]
        public string ValueName { get; set; }

        /// <summary>
        /// The text name
        /// </summary>
        [HtmlAttributeName(CodeTextAttributeName)]
        public string TextName { get; set; }

        /// <inheritdoc />
        public override void Init(TagHelperContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (For == null)
            {
                // Informs contained elements that they're running within a targeted <select/> element.
                context.Items[typeof(SelectTagHelper)] = null;
                return;
            }

            // Note null or empty For.Name is allowed because TemplateInfo.HtmlFieldPrefix may be sufficient.
            // IHtmlGenerator will enforce name requirements.
            if (For.Metadata == null)
            {
                //throw new InvalidOperationException(Resources.FormatTagHelpers_NoProvidedMetadata(
                //    "<select>",
                //    ForAttributeName,
                //    nameof(IModelMetadataProvider),
                //    For.Name));
            }

            // Base allowMultiple on the instance or declared type of the expression to avoid a
            // "SelectExpressionNotEnumerable" InvalidOperationException during generation.
            // Metadata.IsEnumerableType is similar but does not take runtime type into account.
            var realModelType = For.ModelExplorer.ModelType;

            // TODO: Figure out if this is Relevant for AltinnCore. Disabled now because of NetStandard issues
            _allowMultiple = typeof(string) != realModelType &&
             typeof(IEnumerable).IsAssignableFrom(realModelType);
            _currentValues = Generator.GetCurrentValues(
                ViewContext,
                For.ModelExplorer,
                expression: For.Name,
                allowMultiple: _allowMultiple);

            // Whether or not (not being highly unlikely) we generate anything, could update contained <option/>
            // elements. Provide selected values for <option/> tag helpers.
            var currentValues = _currentValues == null ? null : new CurrentValues(_currentValues);
            context.Items[typeof(SelectTagHelper)] = currentValues;
        }

        /// <inheritdoc />
        /// <remarks>Does nothing if <see cref="For"/> is <c>null</c>.</remarks>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (output == null)
            {
                throw new ArgumentNullException(nameof(output));
            }

            IPlatformServices platFormServices = ViewContext.ViewBag.PlatFormServices;

            List<SelectListItem> selectItems = null;

            if (!string.IsNullOrEmpty(CodeList))
            {
              selectItems =  platFormServices.GetPresentationCodelist(CodeList, TextName, ValueName);
            }

            // Ensure GenerateSelect() _never_ looks anything up in ViewData.
            var items = Enumerable.Empty<SelectListItem>();

            if(selectItems != null && selectItems.Count > 0)
            {
                items = selectItems;
            }

            if (For == null)
            {
                var options = Generator.GenerateGroupsAndOptions(optionLabel: null, selectList: items);
                output.PostContent.AppendHtml(options);
                return;
            }

            var tagBuilder = Generator.GenerateSelect(
                ViewContext,
                For.ModelExplorer,
                optionLabel: null,
                expression: For.Name,
                selectList: items,
                currentValues: _currentValues,
                allowMultiple: _allowMultiple,
                htmlAttributes: null);

            if (tagBuilder != null)
            {
                output.MergeAttributes(tagBuilder);
                output.PostContent.AppendHtml(tagBuilder.InnerHtml);
            }
        }
    }
}
