apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvt-chart
  namespace: nvt
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:f1669ee34029a0d989278cd8290a103e4bbaa234c3f826210935009eac81a5df
  url: oci://ghcr.io/mirkosekulic/helm/nvt
