apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvt-chart
  namespace: nvt
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:107cc2e97cb2b680bf521ab8fd9f46aee4f48f20cb91aa3efafa853f4f9ec480
  url: oci://ghcr.io/mirkosekulic/helm/nvt
