apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvt-chart
  namespace: nvt
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:fa11b475b652e592f25932230d5e02e46117cca6f999298ccf7486ef11554660
  url: oci://ghcr.io/mirkosekulic/helm/nvt
