// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Data.Context;

#nullable disable

namespace WorkflowEngine.Data.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    [Migration("20260902113347_AddNamespaceThrottling")]
    partial class AddNamespaceThrottling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngine.Data.Entities.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Namespace")
                        .HasColumnType("text")
                        .HasColumnName("namespace");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("RequestBodyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_body_hash");

                    b.PrimitiveCollection<Guid[]>("WorkflowIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("workflow_ids");

                    b.HasKey("IdempotencyKey", "Namespace")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_keys_created_at");

                    b.ToTable("idempotency_keys", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.MailboxDeliveryEntity", b =>
                {
                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<long>("Idx")
                        .HasColumnType("bigint")
                        .HasColumnName("idx");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("MailboxId", "Idx")
                        .HasName("pk_mailbox_deliveries");

                    b.HasIndex("MailboxId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_mailbox_deliveries_mailbox_id_idempotency_key");

                    b.ToTable("mailbox_deliveries", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.MailboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CollectionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("collection_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<DateTimeOffset?>("DisposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disposed_at");

                    b.Property<string>("DisposedReason")
                        .HasColumnType("text")
                        .HasColumnName("disposed_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("namespace");

                    b.Property<long>("NextIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("next_idx");

                    b.Property<long>("NextSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("next_seq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<TimeSpan>("Timeout")
                        .HasColumnType("interval")
                        .HasColumnName("timeout");

                    b.HasKey("Id")
                        .HasName("pk_mailboxes");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("ix_mailboxes_deadline_open")
                        .HasFilter("status = 'open'");

                    b.HasIndex("DisposedAt")
                        .HasDatabaseName("ix_mailboxes_disposed_at")
                        .HasFilter("status = 'disposed'");

                    b.HasIndex("Namespace", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_mailboxes_namespace_idempotency_key");

                    b.HasIndex("Namespace", "CollectionKey", "Status")
                        .HasDatabaseName("ix_mailboxes_namespace_collection_key");

                    b.ToTable("mailboxes", "engine", t =>
                        {
                            t.HasCheckConstraint("ck_mailboxes_disposal_is_complete", "(status = 'open' AND disposed_reason IS NULL AND disposed_at IS NULL) OR (status = 'disposed' AND disposed_reason IS NOT NULL AND disposed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_mailboxes_disposed_reason", "disposed_reason IN ('request', 'deadline')");

                            t.HasCheckConstraint("ck_mailboxes_status", "status IN ('open', 'disposed')");
                        });
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.MailboxReceiverEntity", b =>
                {
                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("HeldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_at");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("MailboxId", "Seq")
                        .HasName("pk_mailbox_receivers");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ix_mailbox_receivers_workflow_id");

                    b.ToTable("mailbox_receivers", "engine", t =>
                        {
                            t.HasCheckConstraint("ck_mailbox_receivers_birth_is_recorded", "held_at IS NOT NULL OR released_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.NamespaceThrottleEntity", b =>
                {
                    b.Property<string>("Namespace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("namespace");

                    b.Property<string>("Canaries")
                        .HasColumnType("jsonb")
                        .HasColumnName("canaries");

                    b.Property<TimeSpan>("CurrentWindow")
                        .HasColumnType("interval")
                        .HasColumnName("current_window");

                    b.Property<int>("LastActiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_active_count");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<int>("LastRequeuedCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_requeued_count");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("TrippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tripped_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Namespace")
                        .HasName("pk_namespace_throttles");

                    b.ToTable("namespace_throttles", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.StepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("command_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeferCount")
                        .HasColumnType("integer")
                        .HasColumnName("defer_count");

                    b.Property<string>("EngineTraceContext")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_trace_context");

                    b.Property<string>("ErrorHistory")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_history");

                    b.Property<DateTimeOffset?>("FirstDeferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_deferred_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<string>("LastDeferReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_defer_reason");

                    b.Property<DateTimeOffset?>("LastDeferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_deferred_at");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_id");

                    b.Property<int>("ProcessingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("processing_order");

                    b.Property<int>("RequeueCount")
                        .HasColumnType("integer")
                        .HasColumnName("requeue_count");

                    b.Property<string>("RetryStrategyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("retry_strategy_json");

                    b.Property<string>("StateOut")
                        .HasColumnType("text")
                        .HasColumnName("state_out");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_steps");

                    b.HasIndex("Labels")
                        .HasDatabaseName("ix_steps_labels");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Labels"), "gin");

                    b.HasIndex("JobId", "Status")
                        .HasDatabaseName("ix_steps_job_id_status");

                    b.ToTable("steps", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.WorkflowCollectionEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Namespace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("namespace");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<Guid[]>("Heads")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("heads");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Key", "Namespace")
                        .HasName("pk_workflow_collections");

                    b.HasIndex("Namespace")
                        .HasDatabaseName("ix_workflow_collections_namespace");

                    b.ToTable("workflow_collections", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BackoffUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("backoff_until");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<string>("CollectionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("collection_key");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DistributedTraceContext")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distributed_trace_context");

                    b.Property<string>("EngineTraceContext")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_trace_context");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InitialState")
                        .HasColumnType("text")
                        .HasColumnName("initial_state");

                    b.Property<bool?>("IsHead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_head");

                    b.Property<string>("Labels")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<Guid?>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("namespace");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_id");

                    b.Property<int>("ReclaimCount")
                        .HasColumnType("integer")
                        .HasColumnName("reclaim_count");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("ThrottledUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("throttled_until");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("CollectionKey")
                        .HasDatabaseName("ix_workflows_collection_key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_workflows_created_at");

                    b.HasIndex("HeartbeatAt")
                        .HasDatabaseName("ix_workflows_heartbeat_at")
                        .HasFilter("status = 1");

                    b.HasIndex("Labels")
                        .HasDatabaseName("ix_workflows_labels");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Labels"), "gin");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workflows_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_workflows_updated_at")
                        .HasFilter("status IN (3, 4, 5, 6, 7)");

                    b.HasIndex("BackoffUntil", "CreatedAt")
                        .HasDatabaseName("ix_workflows_backoff_until_created_at")
                        .HasFilter("status IN (0, 2, 8)");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("BackoffUntil", "CreatedAt"), new[] { "ThrottledUntil" });
                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("BackoffUntil", "CreatedAt"), new[] { NullSortOrder.NullsFirst, NullSortOrder.NullsLast });

                    b.HasIndex("Namespace", "Status")
                        .HasDatabaseName("ix_workflows_namespace_status");

                    b.HasIndex(new[] { "Namespace", "Status" }, "ix_workflows_namespace_status_incomplete")
                        .HasDatabaseName("ix_workflows_namespace_status_incomplete")
                        .HasFilter("status IN (0, 1, 2, 8, 9)");

                    b.ToTable("workflows", "engine");
                });

            modelBuilder.Entity("workflow_dependency", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("DependsOnWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_workflow_id");

                    b.HasKey("WorkflowId", "DependsOnWorkflowId")
                        .HasName("pk_workflow_dependency");

                    b.HasIndex("DependsOnWorkflowId")
                        .HasDatabaseName("ix_workflow_dependency_depends_on_workflow_id");

                    b.ToTable("workflow_dependency", "engine");
                });

            modelBuilder.Entity("workflow_link", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("LinkedWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_workflow_id");

                    b.HasKey("WorkflowId", "LinkedWorkflowId")
                        .HasName("pk_workflow_link");

                    b.HasIndex("LinkedWorkflowId")
                        .HasDatabaseName("ix_workflow_link_linked_workflow_id");

                    b.ToTable("workflow_link", "engine");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.MailboxDeliveryEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.MailboxEntity", null)
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mailbox_deliveries_mailboxes_mailbox_id");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.MailboxReceiverEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.MailboxEntity", null)
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mailbox_receivers_mailboxes_mailbox_id");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.StepEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_steps_workflows_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("workflow_dependency", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("DependsOnWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_dependency_workflows_depends_on_workflow_id");

                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_dependency_workflows_workflow_id");
                });

            modelBuilder.Entity("workflow_link", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("LinkedWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_link_workflows_linked_workflow_id");

                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_link_workflows_workflow_id");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.WorkflowEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
