// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Data.Context;

#nullable disable

namespace WorkflowEngine.Data.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    partial class EngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowDependency", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnWorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowId", "DependsOnWorkflowId");

                    b.HasIndex("DependsOnWorkflowId");

                    b.ToTable("WorkflowDependency");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RequestBodyHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.PrimitiveCollection<Guid[]>("WorkflowIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("IdempotencyKey", "Namespace");

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.StepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CommandJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProcessingOrder")
                        .HasColumnType("integer");

                    b.Property<int>("RequeueCount")
                        .HasColumnType("integer");

                    b.Property<string>("RetryStrategyJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("StateOut")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Status");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BackoffUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineTraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialState")
                        .HasColumnType("text");

                    b.Property<string>("LabelsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("TenantId");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TraceContext")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LabelsJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LabelsJson"), "gin");

                    b.HasIndex("Status");

                    b.HasIndex("BackoffUntil", "CreatedAt")
                        .HasFilter("\"Status\" IN (0, 2)");

                    NpgsqlIndexBuilderExtensions.HasNullSortOrder(b.HasIndex("BackoffUntil", "CreatedAt"), new[] { NullSortOrder.NullsFirst, NullSortOrder.NullsLast });

                    b.HasIndex("Namespace", "Status");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("WorkflowLink", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkedWorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowId", "LinkedWorkflowId");

                    b.HasIndex("LinkedWorkflowId");

                    b.ToTable("WorkflowLink");
                });

            modelBuilder.Entity("WorkflowDependency", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("DependsOnWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.StepEntity", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WorkflowLink", b =>
                {
                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("LinkedWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Data.Entities.WorkflowEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowEngine.Data.Entities.WorkflowEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
