"""
altinn_datamodel_docs - Datamodel documentation tool.
altinn_datamodel_sync - Generate XSD/C# from JSON schema.
"""

import json
import pathlib
from typing import Dict, Any
from server.handlers import (
    register_tool,
    ToolCategory,
    OperationMode,
    ToolSuccess,
    ToolError,
    ToolRecommendation,
)


@register_tool(
    name="altinn_datamodel_docs",
    description="Get documentation on Altinn datamodels, JSON Schema, XSD, and data bindings.",
    category=ToolCategory.DOCS,
    mode=OperationMode.ONCE_PER_SESSION,
)
def datamodel_docs() -> Dict[str, Any]:
    """Get static documentation on Altinn datamodels."""
    current_dir = pathlib.Path(__file__).parent
    doc_path = current_dir / "datamodel_context.md"
    
    if doc_path.exists():
        with open(doc_path, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = _get_datamodel_docs_fallback()
    
    return ToolSuccess(
        content=content,
        next_steps=[
            ToolRecommendation(
                tool="altinn_datamodel_sync",
                reason="Generate XSD and C# files from your .schema.json",
                args_template={"schema_content": "<JSON_SCHEMA>", "schema_filename": "model.schema.json"},
            ),
        ],
    ).to_dict()


def _get_datamodel_docs_fallback() -> str:
    """Fallback documentation if file not found."""
    return """
# Altinn Datamodel Documentation

## File Structure
```
App/models/
├── model.schema.json  ← Create this manually (source of truth)
├── model.xsd          ← Generated by altinn_datamodel_sync
└── model.cs           ← Generated by altinn_datamodel_sync
```

## CRITICAL
- Only manually create .schema.json
- NEVER manually create .xsd or .cs files
- Use altinn_datamodel_sync to generate derived files
"""


@register_tool(
    name="altinn_datamodel_sync",
    description="Generate XSD and C# model files from a JSON schema.",
    category=ToolCategory.GENERATION,
    mode=OperationMode.IDEMPOTENT,
    prerequisites=["altinn_datamodel_docs"],
    schema_hints={
        "schema_content": "MUST be valid JSON schema as a string.",
        "schema_filename": "Filename like 'model.schema.json'.",
    },
)
def datamodel_sync(
    schema_content: str,
    schema_filename: str,
) -> Dict[str, Any]:
    """Generate XSD and C# files from JSON schema.
    
    Args:
        schema_content: Complete JSON schema as a string.
        schema_filename: Filename (e.g., "model.schema.json").
    """
    if not schema_content or not schema_content.strip():
        return ToolError(
            error_code="MISSING_SCHEMA_CONTENT",
            message="schema_content is required and must not be empty",
            recommended_tool="altinn_datamodel_docs",
            why="Review datamodel documentation to understand the required schema format",
        ).to_dict()
    
    if not schema_filename or not schema_filename.strip():
        return ToolError(
            error_code="MISSING_SCHEMA_FILENAME",
            message="schema_filename is required (e.g., 'model.schema.json')",
        ).to_dict()
    
    try:
        json.loads(schema_content)
    except json.JSONDecodeError as e:
        return ToolError(
            error_code="INVALID_JSON",
            message=f"schema_content is not valid JSON: {e}",
            recommended_tool="altinn_datamodel_docs",
            why="Review the JSON schema format in the documentation",
        ).to_dict()
    
    try:
        from server.handlers.datamodel_tool.datamodel_sync_tool import datamodel_sync as sync_datamodel
        
        result = sync_datamodel(
            user_goal="",
            schema_content=schema_content,
            schema_filename=schema_filename,
        )
        
        if result.get("status") == "error":
            return ToolError(
                error_code=result.get("error_code", "GENERATION_FAILED"),
                message=result.get("errors", ["Failed to generate files"])[0] if result.get("errors") else "Failed to generate files",
                recommended_tool="altinn_datamodel_docs",
                why="Check schema format against documentation",
            ).to_dict()
        
        return {
            "status": "success",
            "generated": result.get("generated", []),
            "warnings": result.get("warnings", []),
            "next_steps": [
                {
                    "tool": None,
                    "reason": "Write all three files to App/models/: .schema.json, .xsd, and .cs",
                }
            ],
        }
        
    except ImportError as e:
        return ToolError(
            error_code="SYNC_NOT_AVAILABLE",
            message=f"Datamodel sync functionality is not available: {str(e)}",
            why="The datamodel sync module could not be loaded",
        ).to_dict()
