# Keep src/ build context minimal for localtest image.
**
!Runtime/
!Runtime/localtest/
!Runtime/common/
!Runtime/localtest/src/**
!Runtime/localtest/testdata/**
!Runtime/common/dotnet/
!Runtime/common/dotnet/Altinn.Studio.Runtime.Common/
!Runtime/common/dotnet/Altinn.Studio.Runtime.Common/**
**/bin
**/obj
