apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      version: 2.5.0
  values:
    installCRDs: true
    global:
      podAnnotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      kubernetes.azure.com/mode: system
