replicaCount: 1

image:
  repository: altinntjenestercontainerregistry.azurecr.io/altinn-kuberneteswrapper
  tag: latest
  containerPort: 80
  pullPolicy: Always
  pullSecrets:
    # Change this to the name of your pull secret
    - name: acrsecret
  serviceAccount: kuberneteswrappersa

hosts:
  dev: dev.altinn.studio
  staging: staging.altinn.studio
  prod: altinn.studio

service:
  name: kuberneteswrapper
  externalPort: 3000
  ingressRouteExternalPort: 80
  internalPort: 80

ingress:
  - metadata:
      name: kuberneteswrapper-base-path
      annotations:
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        traefik.frontend.priority: "500"
    paths:
      - path: /kuberneteswrapper/

middlewares:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: kuberneteswrapper-strip-prefix
    spec:
      replacePathRegex:
        regex: ^/kuberneteswrapper/(.*)
        replacement: /$1

ingressRoute:
  name: ""
  entryPoints:
    - http
    - https
  routes: []
  tls: []
