FROM --platform=$BUILDPLATFORM golang:1.26.3-trixie@sha256:0f6b034c99663ea8957e7dae99124e37374cbe7fcb5b5646f19b185f8f976279 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o main ./cmd/proxy

FROM scratch

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 5030

COPY --from=builder /etc/passwd /etc/passwd
USER nobody

ENTRYPOINT ["./main"]
