const MODULE_NAME: string = 'APPLICATION_METADATA';

export const GET_APPLICATION_METADATA: string = `${MODULE_NAME}.GET`;
export const GET_APPLICATION_METADATA_FULFILLED: string = `${MODULE_NAME}.GET_FULFILLED`;
export const GET_APPLICATION_METADATA_REJECTED: string = `${MODULE_NAME}.GET_REJECTED`;

export const PUT_APPLICATION_METADATA: string = `${MODULE_NAME}.PUT`;
export const PUT_APPLICATION_METADATA_FULFILLED: string = `${MODULE_NAME}.PUT_FULFILLED`;
export const PUT_APPLICATION_METADATA_REJECTED: string = `${MODULE_NAME}.PUT_REJECTED`;
