// <auto-generated/>
using System;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;
namespace App.IntegrationTests.Mocks.Apps.Ttd.Dayplanner
{
    public class MyDay
    {
        [XmlElement("Planner")]
        public Person Planner { get; set; }

        [XmlElement("PlannedFor")]
        public Person PlannedFor { get; set; }

        [XmlElement("Weather")]
        public Weather Weather { get; set; }
    }

    public class Person
    {
        [XmlElement("Name")]
        public string Name { get; set; }

        [XmlElement("Address")]
        public string Address { get; set; }
    }

    public class Weather
    {
        [XmlElement("Temp")]
        public string Temp { get; set; }

        [XmlElement("Precipitation")]
        public string Precipitation { get; set; }
    }

}
