const moduleName: string = 'THIRD_PARTY_COMPONENTS';

export const FETCH_THIRD_PARTY_COMPONENTS: string = `${moduleName}.FETCH_THIRD_PARTY_COMPONENTS`;
export const FETCH_THIRD_PARTY_COMPONENTS_FULFILLED: string = `${moduleName}.FETCH_THIRD_PARTY_COMPONENTS_FULFILLED`;
export const FETCH_THIRD_PARTY_COMPONENTS_REJECTED: string = `${moduleName}.FETCH_THIRD_PARTY_COMPONENTS_REJECTED`;