const moduleName: string = 'APPLICATION_SETTINGS';

export const FETCH_APPLICATION_SETTINGS: string = `${moduleName}.FETCH_APPLICATION_SETTINGS`;
export const FETCH_APPLICATION_SETTINGS_FULFILLED = `${moduleName}.FETCH_APPLICATION_SETTINGS_FULFILLED`;
export const FETCH_APPLICATION_SETTINGS_REJECTED = `${moduleName}.FETCH_APPLICATION_SETTINGS_REJECTED`;
