{
 "title": "Overview",
 "tags": [ "altinn" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "org",
    "label": "Organization",
    "query": {}
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app",
    "label": "App name",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available,deployment)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Overview" } },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Instances created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_lib_instances_created",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ca0666d3-b3c0-4159-93f1-b71777ed4338"
    }
   ]
  },
  {
   "title": "Instances completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_lib_instances_completed",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ca0666d3-b3c0-4159-93f1-b71777ed4338"
    }
   ]
  },
  {
   "title": "Failed process/next requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\n| where success == false\n| where client_Type != 'Browser'\n| where toint(resultCode) >= 500\n| where name has 'PUT Process/NextElement'\n| summarize Count = sum(itemCount) by cloud_RoleName, DateTimeOffset = bin(timestamp, 1h)\n| order by DateTimeOffset asc",
      "resources": [
       "/subscriptions/$sub/resourceGroups/monitor-$org-$env-rg/providers/Microsoft.Insights/components/$org-$env-ai"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{cloud/rolename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "cloud/roleName", "filters": [ "$app" ], "operator": "eq" }
      ],
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "5xx failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{cloud/rolename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "cloud/roleName", "filters": [ "$app" ], "operator": "eq" },
       {
        "dimension": "request/resultCode",
        "filters": [
         "500",
         "501",
         "502",
         "503",
         "504",
         "505",
         "506",
         "507",
         "508",
         "510",
         "511"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{cloud/rolename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "cloud/roleName", "filters": [ "$app" ], "operator": "eq" }
      ],
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{cloud/rolename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "cloud/roleName", "filters": [ "$app" ], "operator": "eq" }
      ],
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n            container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}\n            * on(namespace,pod)\n            group_left(workload, workload_type)\n            namespace_workload_pod:kube_pod_owner:relabel{\n                namespace=\"default\",\n                workload_type=\"deployment\",\n                workload=~\"^$org-.*-deployment-v2$\"\n            }\n        ) by (workload)\n        /\n        sum(\n            kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"memory\"}\n            * on(namespace,pod)\n            group_left(workload, workload_type)\n            namespace_workload_pod:kube_pod_owner:relabel{\n                namespace=\"default\",\n                workload_type=\"deployment\",\n                workload=~\"^$org-.*-deployment-v2$\"\n            }\n        ) by (workload)\n        * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency call failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "dependency/target",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "dependency/resultCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-$org-$env-rg",
        "resourceName": "$org-$env-ai",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n                sum by (namespace, pod, container) (\n                    rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\"}[5m])\n                )\n                * on(namespace,pod)\n                group_left(workload, workload_type)\n                namespace_workload_pod:kube_pod_owner:relabel{\n                    namespace=\"default\",\n                    workload_type=\"deployment\",\n                    workload=~\"^$org-.*-deployment-v2$\"\n                }\n            ) by (workload)\n            /\n            sum(\n                kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"cpu\"}\n                * on(namespace,pod)\n                group_left(workload, workload_type)\n                namespace_workload_pod:kube_pod_owner:relabel{\n                    namespace=\"default\",\n                    workload_type=\"deployment\",\n                    workload=~\"^$org-.*-deployment-v2$\"\n                }\n            ) by (workload)\n            * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(\n  100 *\n  sum by (namespace, deployment) (\n    kube_deployment_status_replicas_available{namespace=\"default\", deployment=~\"^$org-.*-deployment-v2$\"}\n  )\n  /\n  clamp_min(\n    sum by (namespace, deployment) (\n      kube_deployment_spec_replicas{namespace=\"default\", deployment=~\"^$org-.*-deployment-v2$\"}\n    ), 1\n  ),\n  100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}