apiVersion: v1
kind: ServiceAccount
metadata:
  name: studio-kv-eso-uami
  namespace: nvt
  annotations:
    azure.workload.identity/client-id: ${ESO_STUDIO_KV_CLIENT_ID}
    azure.workload.identity/tenant-id: ${TENANT_ID}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: studio-key-vault
  namespace: nvt
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${STUDIO_KV_URI}
      serviceAccountRef:
        name: studio-kv-eso-uami
        namespace: nvt
