{
 "title": "App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(process_runtime_dotnet_thread_pool_threads_count,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Skjema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Skjemaer startet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_instances_created_total{job=\"$app\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skjemaer avsluttet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_processes_ended_total{job=\"$app\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fullførere",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_processes_ended_total{job=\"$app\"}[$__range]) / increase(altinn_app_lib_processes_created_total{job=\"$app\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skjematid - median",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(altinn_app_lib_processes_duration_bucket{job=\"$app\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skjemaoppdateringer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_data_patched_total{job=\"$app\", result=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feil",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SMS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_server_request_duration_seconds_count{job=\"$app\", http_response_status_code=~\"5..\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skjemaer per minutt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(altinn_app_lib_instances_created_total{job=\"$app\"}[$__rate_interval]) * 60",
     "legendFormat": "Skjemaer startet"
    },
    {
     "expr": "rate(altinn_app_lib_processes_ended_total{job=\"$app\"}[$__rate_interval]) * 60",
     "legendFormat": "Skjemaer fullført"
    }
   ]
  },
  {
   "title": "Skjematid - distribusjon",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_processes_duration_bucket{job=\"$app\", le!=\"+Inf\", le!=\"0\"}[$__range])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Skjematid - median over tid",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(altinn_app_lib_processes_duration_bucket{job=\"$app\"}[10m])) by (le))",
     "legendFormat": "Tidsbruk"
    }
   ]
  },
  { "title": "Varsler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "E-post - bestillinger",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_notification_orders_total{job=\"$app\", type=\"email\", result=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E-post - bestillingsfeil",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_notification_orders_total{job=\"$app\", type=\"email\", result!=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Varsler per minutt",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(altinn_app_lib_notification_orders_total{job=\"$app\"}[10m]) * 60)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "SMS - bestillinger",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_notification_orders_total{job=\"$app\", type=\"sms\", result=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS - bestillingsfeil",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(altinn_app_lib_notification_orders_total{job=\"$app\", type=\"sms\", result!=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}