/**
 * Below is the JSON itself as an example value of the `LayoutCollection` type.
 */
export const exampleLayoutCollection: any = {
  RadioButtonsPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'RadioButtonsPage-NavigationBar', type: 'NavigationBar' },
        {
          size: 'h2',
          id: 'RadioButtonsPage-Header',
          type: 'Header',
          textResourceBindings: { title: 'RadioButtonsPage' },
        },
        {
          size: 'h3',
          id: 'RadioButtonsPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          dataModelBindings: { simpleBinding: 'radioButtonInput' },
          id: 'RadioButtonsPage-RadioButtons',
          type: 'RadioButtons',
          textResourceBindings: { title: 'RadioButtonsPage.RadioButtons.title' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
          required: false,
        },
        {
          size: 'h3',
          id: 'RadioButtonsPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        {
          componentRef: 'RadioButtonsPage-RadioButtons',
          id: 'RadioButtonsPage-Summary',
          type: 'Summary',
          largeGroup: false,
        },
        {
          size: 'h3',
          id: 'RadioButtonsPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'RadioButtonsPage-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'RadioButtonsPage-RadioButtons' },
        },
        {
          id: 'RadioButtonsPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  RepeatingGroupPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'RepeatingGroup-NavigationBar', type: 'NavigationBar' },
        {
          id: 'RepeatingGroup-Header',
          type: 'Header',
          textResourceBindings: { title: 'RepeatingGroupPage' },
          size: 'h2',
        },
        {
          id: 'RepeatingGroup-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
          size: 'h3',
        },
        {
          id: 'RepeatingGroup',
          type: 'RepeatingGroup',
          textResourceBindings: { title: 'Repeterende Gruppe', description: 'Beskrivelse av repeterende gruppe' },
          dataModelBindings: { group: 'repeatingGroup' },
          hidden: false,
          children: ['RepeatingGroup-Input-Name', 'RepeatingGroup-Input-Points', 'RepeatingGroup-Input-Date'],
        },
        {
          id: 'RepeatingGroup-Input-Name',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Name' },
          dataModelBindings: { simpleBinding: 'repeatingGroup.name' },
          grid: { xs: 12, sm: 6 },
        },
        {
          id: 'RepeatingGroup-Input-Points',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Points' },
          dataModelBindings: { simpleBinding: 'repeatingGroup.points' },
          grid: { xs: 12, sm: 6 },
        },
        {
          id: 'RepeatingGroup-Input-Date',
          type: 'Datepicker',
          textResourceBindings: { title: 'RepeatingGroup.Date' },
          dataModelBindings: { simpleBinding: 'repeatingGroup.date' },
        },
        {
          id: 'RepeatingGroup-With-Group',
          type: 'RepeatingGroup',
          textResourceBindings: {
            title: 'Repeterende Gruppe med Gruppe',
            description: 'Beskrivelse av repeterende gruppe',
          },
          tableHeaders: ['RepeatingGroup-With-Group-Input-Name'],
          dataModelBindings: { group: 'repeatingGroup' },
          hidden: false,
          children: ['RepeatingGroup-Group'],
        },
        {
          id: 'RepeatingGroup-With-Group-Input-Name',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Name' },
          maxLength: 10,
          dataModelBindings: { simpleBinding: 'repeatingGroup.name' },
        },
        {
          id: 'RepeatingGroup-With-Group-Input-Points',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Points' },
          dataModelBindings: { simpleBinding: 'repeatingGroup.points' },
        },
        {
          id: 'RepeatingGroup-With-Group-Input-Date',
          type: 'Datepicker',
          textResourceBindings: { title: 'RepeatingGroup.Date' },
          dataModelBindings: { simpleBinding: 'repeatingGroup.date' },
        },
        {
          id: 'RepeatingGroup-Group',
          type: 'Group',
          textResourceBindings: { title: 'A group title' },
          children: [
            'RepeatingGroup-With-Group-Input-Name',
            'RepeatingGroup-With-Group-Input-Points',
            'RepeatingGroup-With-Group-Input-Date',
          ],
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup',
          type: 'RepeatingGroup',
          textResourceBindings: {
            title: 'Nøstet Repeterende Gruppe',
            description: 'Beskrivelse av repeterende gruppe',
          },
          dataModelBindings: { group: 'nestedRepeatingGroup' },
          hidden: false,
          children: [
            'RepeatingGroup-With-RepeatingGroup-Input-Name',
            'RepeatingGroup-With-RepeatingGroup-Input-Points',
            'RepeatingGroup-With-RepeatingGroup-Input-Date',
            'NestedRepeatingGroup-Cars',
          ],
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Input-Name',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Name' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.name' },
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Input-Points',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.Points' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.points' },
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Input-Date',
          type: 'Datepicker',
          textResourceBindings: { title: 'RepeatingGroup.Date' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.date' },
        },
        {
          id: 'NestedRepeatingGroup-Cars',
          type: 'RepeatingGroup',
          textResourceBindings: { title: 'RepeatingGroup.Cars' },
          dataModelBindings: { group: 'nestedRepeatingGroup.cars' },
          children: [
            'NestedRepeatingGroup-Input-CarBrand',
            'RepeatingGroup-With-RepeatingGroup-Input-Model',
            'RepeatingGroup-With-RepeatingGroup-Input-ModelYear',
          ],
        },
        {
          id: 'NestedRepeatingGroup-Input-CarBrand',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.CarBrand' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.cars.carBrand' },
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Input-Model',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.CarModel' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.cars.carModel' },
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Input-ModelYear',
          type: 'Input',
          textResourceBindings: { title: 'RepeatingGroup.ModelYear' },
          dataModelBindings: { simpleBinding: 'nestedRepeatingGroup.cars.modelYear' },
        },
        {
          id: 'RepeatingGroup-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
          size: 'h3',
        },
        { id: 'RepeatingGroup-Summary', type: 'Summary', componentRef: 'RepeatingGroup' },
        { id: 'RepeatingGroup-With-Group-Summary', type: 'Summary', componentRef: 'RepeatingGroup-With-Group' },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Summary',
          type: 'Summary',
          componentRef: 'RepeatingGroup-With-RepeatingGroup',
        },
        {
          id: 'RepeatingGroup-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
          size: 'h3',
        },
        {
          id: 'RepeatingGroup-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'RepeatingGroup' },
        },
        {
          id: 'RepeatingGroup-Header-Summary2-table',
          type: 'Header',
          textResourceBindings: { title: 'Displayed as table' },
          size: 'h3',
        },
        {
          id: 'RepeatingGroup-Summary2-table',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'RepeatingGroup' },
          overrides: [{ componentId: 'RepeatingGroup', display: 'table' }],
        },
        {
          id: 'RepeatingGroup-With-Group-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'RepeatingGroup-With-Group' },
        },
        {
          id: 'RepeatingGroup-With-RepeatingGroup-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'RepeatingGroup-With-RepeatingGroup' },
        },
        {
          id: 'RepeatingGroup-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  DatePage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'DatePage-NavigationBar', type: 'NavigationBar' },
        { id: 'DatePage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'Date' } },
        {
          id: 'date1',
          type: 'Date',
          textResourceBindings: { title: 'Dato' },
          value: '2022-09-27 18:00:00.000',
          format: 'dd.MM.yyyy',
          grid: { xs: 6 },
        },
        {
          id: 'date2',
          type: 'Date',
          textResourceBindings: { title: 'Dato med tid' },
          value: '2022-09-27 18:00:00.000',
          format: 'dd.MM.yyyy HH:mm:ss',
          grid: { xs: 6 },
        },
        {
          id: 'date3',
          type: 'Date',
          textResourceBindings: { title: 'Dato med annet format' },
          value: '2022-09-27',
          format: 'dd/MM/yyyy',
          grid: { xs: 6 },
        },
        {
          id: 'date4',
          type: 'Date',
          textResourceBindings: { title: 'Dato med tid på et annet format' },
          value: '2022-09-27 18:00:00.000',
          format: 'dd/MM/yyyy HH:mm:ss',
          direction: 'vertical',
          grid: { xs: 6 },
        },
        {
          id: 'date5',
          type: 'Date',
          textResourceBindings: { title: 'Dato med tid og input fra en annen tidssone' },
          direction: 'vertical',
          value: '2007-04-05T14:30Z',
          format: 'yyyy-MM-dd HH:mm:ss z',
          grid: { xs: 6 },
        },
        {
          type: 'Cards',
          id: 'date-Card',
          color: 'subtle',
          cards: [{ title: 'Datokort', description: '', children: ['date1', 'date2', 'date3', 'date4', 'date5'] }],
        },
        { id: 'Date-NavigationButtons', type: 'NavigationButtons', showBackButton: true, textResourceBindings: {} },
      ],
    },
  },
  SummaryPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'NavigationBar-dd9oO8', type: 'NavigationBar' },
        {
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          id: 'Input-Test',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.title' },
        },
        {
          size: 'M',
          id: 'Header-in-new-summaryaergreg',
          type: 'Header',
          textResourceBindings: { title: 'Her rendres summary av en enkelt komponent:' },
        },
        { id: 'Summary2-84wghp-componentaergaerg', type: 'Summary2', target: { type: 'component', id: 'Input-Test' } },
        {
          size: 'M',
          id: 'Header-in-new-summaryerg',
          type: 'Header',
          textResourceBindings: { title: 'Her vises Summary en enkelt side:' },
        },
        { id: 'Summary2-84wghp-page2', type: 'Summary2', hidden: false, target: { type: 'page', id: 'InputPage' } },
        { id: 'person-lookup-summary', type: 'Summary2', target: { type: 'component', id: 'personLookup' } },
        {
          size: 'M',
          id: 'whole-layoutset',
          type: 'Header',
          textResourceBindings: { title: 'Her vises summary av et helt layoutSet:' },
        },
        { id: 'Summary2-84wghp-layoutset', type: 'Summary2', hidden: false },
        { id: 'Button-qHGXDg', type: 'Button', textResourceBindings: { title: 'Side4.Button-qHGXDg.title' } },
        { id: 'NavigationButtons-dCTvo9', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
      ],
    },
  },
  TextareaPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'TextareaPage-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'TextareaPage-Header', type: 'Header', textResourceBindings: { title: 'TextareaPage' } },
        {
          size: 'h3',
          id: 'TextareaPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          dataModelBindings: { simpleBinding: 'longAnswerInput' },
          id: 'TextareaPage-Textarea',
          type: 'TextArea',
          textResourceBindings: { title: 'TextareaPage.Textarea.title' },
        },
        {
          size: 'h3',
          id: 'TextareaPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { componentRef: 'TextareaPage-Textarea', id: 'TextareaPage-Summary', type: 'Summary' },
        {
          size: 'h3',
          id: 'TextareaPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'TextareaPage-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'TextareaPage-Textarea' },
        },
        {
          id: 'TextareaPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  OrganisationLookupPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'OrganisationLookupPage-NavigationBar', type: 'NavigationBar' },
        {
          id: 'organisationLookup',
          type: 'OrganisationLookup',
          dataModelBindings: { organisation_lookup_orgnr: 'street', organisation_lookup_name: 'co' },
          textResourceBindings: {
            title: 'Legg til virksomhet',
            description: 'Her legger du inn organisasjonsnummer',
            help: 'Du kan finne organisasjonsnummeret ved å søke i Brønnøysundregistrene',
          },
          required: true,
        },
        {
          id: 'OrganisationLookup-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
          size: 'h3',
        },
        {
          id: 'organisation-lookup-summary-on-organisation-lookup-page',
          type: 'Summary2',
          target: { type: 'component', id: 'organisationLookup' },
        },
        {
          id: 'OrganisationLookupPage-NavigationButtons',
          type: 'NavigationButtons',
          showBackButton: true,
          textResourceBindings: { next: 'Neste', back: 'Forrige' },
        },
      ],
    },
  },
  PersonLookupPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'PersonLookupPage-NavigationBar', type: 'NavigationBar' },
        {
          id: 'personLookup',
          type: 'PersonLookup',
          dataModelBindings: { person_lookup_ssn: 'GridExample.ExampleInputTwo', person_lookup_name: 'street' },
          textResourceBindings: {
            title: 'Legg til person',
            description: 'Her legger du inn etternavn og fødselsnummer',
            help: 'For å kunne søke i registeret må du ha fødselsnummeret til personen',
          },
          required: true,
        },
        {
          id: 'PersonLookup-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
          size: 'h3',
        },
        {
          id: 'person-lookup-summary-on-person-lookup-page',
          type: 'Summary2',
          target: { type: 'component', id: 'personLookup' },
        },
        {
          id: 'PersonLookupPage-NavigationButtons',
          type: 'NavigationButtons',
          showBackButton: true,
          textResourceBindings: { next: 'Neste', back: 'Forrige' },
        },
      ],
    },
  },
  CheckboxesPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'CheckboxesPage-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'CheckboxesPage-Header', type: 'Header', textResourceBindings: { title: 'CheckboxesPage' } },
        {
          size: 'h3',
          id: 'CheckboxesPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          dataModelBindings: { simpleBinding: 'checkboxesInput' },
          id: 'CheckboxesPage-Checkboxes',
          type: 'Checkboxes',
          textResourceBindings: { title: 'CheckboxesPage.Checkboxes.title' },
          options: [
            { label: 'Kjøre til hytta på fjellet', value: 'kjoreTilHyttaPaaFjellet' },
            { label: 'Kjøring i skogen', value: 'kjoringISkogen' },
            { label: 'Korte strekninger med bykjøring, eller annen moro', value: 'korteStrekningerMedBykjoring' },
            { label: 'Lange strekninger på større veier i Norge', value: 'langeStrekningerPaStorreVeierINorge' },
          ],
          required: false,
        },
        {
          size: 'h3',
          id: 'CheckboxesPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { componentRef: 'CheckboxesPage-Checkboxes', id: 'CheckboxesPage-Summary', type: 'Summary', largeGroup: false },
        {
          size: 'h3',
          id: 'CheckboxesPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          size: 'h4',
          id: 'CheckboxesPage-Header-Summary2-Display-Auto',
          type: 'Header',
          textResourceBindings: { title: 'displayType: NULL (Auto)' },
        },
        {
          id: 'CheckboxesPage-Summary2-Display-Auto',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'CheckboxesPage-Checkboxes' },
        },
        {
          size: 'h4',
          id: 'CheckboxesPage-Header-Summary2-Display-String',
          type: 'Header',
          textResourceBindings: { title: 'displayType: String' },
        },
        {
          id: 'CheckboxesPage-Summary2-Display-String',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'CheckboxesPage-Checkboxes' },
          overrides: [{ componentId: 'CheckboxesPage-Checkboxes', displayType: 'string' }],
        },
        {
          size: 'h4',
          id: 'CheckboxesPage-Header-Summary2-Display-List',
          type: 'Header',
          textResourceBindings: { title: 'displayType: List' },
        },
        {
          id: 'CheckboxesPage-Summary2-Display-List',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'CheckboxesPage-Checkboxes' },
          overrides: [{ componentId: 'CheckboxesPage-Checkboxes', displayType: 'list' }],
        },
        {
          id: 'CheckboxesPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  DatepickerPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'Datepicker-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'DatepickerHeader', type: 'Header', textResourceBindings: { title: 'DatepickerPage' } },
        {
          id: 'DatepickerExample1',
          type: 'Datepicker',
          textResourceBindings: { title: 'datofeltet', shortName: 'dato-short' },
          dataModelBindings: { simpleBinding: 'DatepickerExample' },
          readOnly: false,
          format: 'DD/MM/YYYY',
          minDate: '1900-01-01T12:00:00Z',
          maxDate: '2100-01-01T12:00:00Z',
          required: true,
          timeStamp: false,
          grid: { md: 6 },
        },
        {
          size: 'h3',
          id: 'DatepickerHeader2',
          type: 'Header',
          textResourceBindings: { title: 'Datepicker Summary example:' },
        },
        { id: 'DatepickerSummary1', type: 'Summary2', target: { type: 'component', id: 'DatepickerExample1' } },
        {
          id: 'Datepicker-NavigationButtons',
          type: 'NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
        },
      ],
    },
  },
  MultipleSelectPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'MultipleSelectPage-NavigationBar', type: 'NavigationBar' },
        {
          id: 'MultipleSelectPage-Header',
          type: 'Header',
          size: 'h2',
          textResourceBindings: { title: 'CheckboxesPage' },
        },
        {
          id: 'MultipleSelectPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'MultipleSelectPage-Checkboxes',
          type: 'MultipleSelect',
          dataModelBindings: { simpleBinding: 'multipleSelect' },
          textResourceBindings: { title: 'MultipleSelectPage.MultipleSelect.title' },
          options: [
            { label: 'Kjøre til hytta på fjellet', value: 'kjoreTilHyttaPaaFjellet' },
            { label: 'Kjøring i skogen', value: 'kjoringISkogen' },
            { label: 'Korte strekninger med bykjøring, eller annen moro', value: 'korteStrekningerMedBykjoring' },
            { label: 'Lange strekninger på større veier i Norge', value: 'langeStrekningerPaStorreVeierINorge' },
          ],
          required: false,
        },
        {
          id: 'MultipleSelectPage-Header-Summary',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary' },
        },
        {
          id: 'MultipleSelectPage-Summary',
          componentRef: 'MultipleSelectPage-Checkboxes',
          type: 'Summary',
          largeGroup: false,
        },
        {
          id: 'MultipleSelectPage-Header-Summary2',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'MultipleSelectPage-Header-Summary2-Display-Auto',
          type: 'Header',
          size: 'h4',
          textResourceBindings: { title: 'displayType: NULL (Auto)' },
        },
        {
          id: 'MultipleSelectPage-Summary2-Display-Auto',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'MultipleSelectPage-Checkboxes' },
        },
        {
          id: 'MultipleSelectPage-Header-Summary2-Display-String',
          type: 'Header',
          size: 'h4',
          textResourceBindings: { title: 'displayType: String' },
        },
        {
          id: 'MultipleSelectPage-Summary2-Display-String',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'MultipleSelectPage-Checkboxes' },
          overrides: [{ componentId: 'MultipleSelectPage-Checkboxes', displayType: 'string' }],
        },
        {
          id: 'MultipleSelectPage-Header-Summary2-Display-List',
          type: 'Header',
          size: 'h4',
          textResourceBindings: { title: 'displayType: List' },
        },
        {
          id: 'MultipleSelectPage-Summary2-Display-List',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'MultipleSelectPage-Checkboxes' },
          overrides: [{ componentId: 'MultipleSelectPage-Checkboxes', displayType: 'list' }],
        },
        {
          id: 'MultipleSelectPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  FileUploadPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'FileUpload-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'FileUpload-Header', type: 'Header', textResourceBindings: { title: 'FileUpload' } },
        {
          displayMode: 'simple',
          hasCustomFileEndings: false,
          maxFileSizeInMB: 25,
          maxNumberOfAttachments: 10,
          minNumberOfAttachments: 1,
          id: 'FileUpload-N6frPq',
          type: 'FileUpload',
          textResourceBindings: { title: 'Enkel filopplasting' },
        },
        {
          size: 'h3',
          id: 'FileUpload-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Oppsummering av FileUpload' },
        },
        {
          id: 'FileUploadSummary',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'FileUpload-N6frPq' },
        },
        {
          size: 'h2',
          id: 'FileUpload-HeaderWithtag',
          type: 'Header',
          textResourceBindings: { title: 'FileUpload with tag' },
        },
        {
          displayMode: 'list',
          hasCustomFileEndings: false,
          maxFileSizeInMB: 25,
          maxNumberOfAttachments: 10,
          minNumberOfAttachments: 1,
          optionsId: '',
          id: 'FileUploadWithTag-UvbEiL',
          type: 'FileUploadWithTag',
          textResourceBindings: { tagTitle: 'Filtype', title: 'Filopplasting med type' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
        },
        {
          size: 'h3',
          id: 'FileUpload-Header-summary',
          type: 'Header',
          textResourceBindings: { title: 'Oppsummering av FileUpload with tag:' },
        },
        {
          id: 'FileUploadSummaryWithTag',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'FileUploadWithTag-UvbEiL' },
        },
        { id: 'NavigationButtons-L67e32', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
      ],
    },
  },
  GridPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'Grid-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'Grid-Header', type: 'Header', textResourceBindings: { title: 'Grid' } },
        {
          size: 'h3',
          id: 'GridPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'all-grid-components',
          type: 'Grid',
          textResourceBindings: { title: 'Grid.Title', description: 'Grid.Description' },
          rows: [
            { header: true, cells: [{ text: 'Komponenttype' }, { text: 'Eksempel' }] },
            { cells: [{ text: 'Button' }, { component: 'grid-example-button' }] },
            { cells: [{ text: 'PrintButton' }, { component: 'grid-example-print-button' }] },
            { cells: [{ text: 'InstantiationButton' }, { component: 'grid-example-instantiation-button' }] },
            { cells: [{ text: 'Header' }, { component: 'grid-example-header' }] },
            { cells: [{ text: 'Paragraph' }, { component: 'grid-example-paragraph' }] },
            { cells: [{ text: 'Image' }, { component: 'grid-example-image' }] },
            { cells: [{ text: 'Datepicker' }, { component: 'grid-example-datepicker' }] },
            { cells: [{ text: 'Dropdown' }, { component: 'grid-example-dropdown' }] },
            { cells: [{ text: 'MultipleSelect' }, { component: 'grid-example-multiple-select' }] },
            { cells: [{ text: 'TextArea' }, { component: 'grid-example-text-area' }] },
          ],
        },
        { id: 'grid-example-button', type: 'Button', textResourceBindings: { title: 'A button example' } },
        {
          id: 'grid-example-print-button',
          type: 'PrintButton',
          textResourceBindings: { title: 'Print button example' },
        },
        {
          id: 'grid-example-instantiation-button',
          type: 'InstantiationButton',
          textResourceBindings: { title: 'Instantiation button example' },
        },
        {
          id: 'grid-example-datepicker',
          type: 'Datepicker',
          textResourceBindings: { title: 'Datepicker example' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleDate' },
        },
        {
          id: 'grid-example-dropdown',
          type: 'Dropdown',
          textResourceBindings: { title: 'Dropdown example' },
          optionsId: 'reasons',
          dataModelBindings: { simpleBinding: 'GridExample.ExampleDropdown' },
        },
        { id: 'grid-example-header', type: 'Header', textResourceBindings: { title: 'Header example' }, size: 'h2' },
        {
          id: 'grid-example-image',
          type: 'Image',
          textResourceBindings: { altTextImg: 'Altinn logo' },
          image: { src: { nb: 'assets/altinn-logo.svg' }, width: '100%', align: 'flex-start' },
        },
        {
          id: 'grid-example-multiple-select',
          type: 'MultipleSelect',
          textResourceBindings: { title: 'Multiple select example' },
          optionsId: 'reasons',
          dataModelBindings: { simpleBinding: 'GridExample.ExampleMultiSelect' },
        },
        { id: 'grid-example-paragraph', type: 'Paragraph', textResourceBindings: { title: 'Paragraph example' } },
        {
          id: 'grid-example-text-area',
          type: 'TextArea',
          textResourceBindings: { title: 'Text area example' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleTextArea' },
        },
        {
          id: 'grid-example-common-fields',
          type: 'Grid',
          textResourceBindings: { title: 'Grid.Title', description: 'Grid.Description' },
          rows: [
            {
              header: true,
              readOnly: false,
              cells: [
                { text: 'Row number' },
                { labelFrom: 'grid-input-field' },
                { text: 'heading2' },
                { text: 'heading3' },
              ],
            },
            {
              header: false,
              readOnly: false,
              cells: [
                { text: 'Row 1' },
                { component: 'grid-input-field' },
                { component: 'grid-checkbox-field' },
                { component: 'grid-radio-field' },
              ],
            },
            {
              header: false,
              readOnly: false,
              cells: [
                { text: 'Row 2' },
                { component: 'grid-input-field-two' },
                { component: 'grid-checkbox-field-two' },
                { component: 'grid-radio-field-two' },
              ],
            },
            {
              header: false,
              readOnly: false,
              cells: [
                { text: 'Row 3' },
                { component: 'grid-input-field-three' },
                { component: 'grid-checkbox-field-three' },
                { component: 'grid-radio-field-three' },
              ],
            },
            {
              readOnly: true,
              cells: [
                { text: 'Row 1 - readonly' },
                { component: 'grid-input-field-readonly' },
                { component: 'grid-checkbox-field-readonly' },
                { component: 'grid-radio-field-readonly' },
              ],
            },
          ],
        },
        {
          id: 'grid-input-field',
          type: 'Input',
          textResourceBindings: { title: 'Grid.Input.Title' },
          required: false,
          dataModelBindings: { simpleBinding: 'GridExample.ExampleInput' },
        },
        {
          id: 'grid-radio-field',
          type: 'RadioButtons',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Ja', value: 'option1' },
            { label: 'Nei', value: 'option2' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleRadio' },
        },
        {
          id: 'grid-checkbox-field',
          type: 'Checkboxes',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Valg 1', value: 'option1' },
            { label: 'Valg 2', value: 'option2' },
            { label: 'Valg 3', value: 'option3' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleCheckbox' },
        },
        {
          id: 'grid-input-field-two',
          type: 'Input',
          textResourceBindings: { title: 'My input field' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleInputTwo' },
        },
        {
          id: 'grid-radio-field-two',
          type: 'RadioButtons',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Ja', value: 'option1' },
            { label: 'Nei', value: 'option2' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleRadioTwo' },
        },
        {
          id: 'grid-checkbox-field-two',
          type: 'Checkboxes',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Valg 1', value: 'option1' },
            { label: 'Valg 2', value: 'option2' },
            { label: 'Valg 3', value: 'option3' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleCheckboxTwo' },
        },
        {
          id: 'grid-input-field-three',
          type: 'Input',
          textResourceBindings: { title: 'My input field' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleInputThree' },
        },
        {
          id: 'grid-radio-field-three',
          type: 'RadioButtons',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Ja', value: 'option1' },
            { label: 'Nei', value: 'option2' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleRadioThree' },
        },
        {
          id: 'grid-checkbox-field-three',
          type: 'Checkboxes',
          textResourceBindings: { title: 'My radio field' },
          options: [
            { label: 'Valg 1', value: 'option1' },
            { label: 'Valg 2', value: 'option2' },
            { label: 'Valg 3', value: 'option3' },
          ],
          dataModelBindings: { simpleBinding: 'GridExample.ExampleCheckboxThree' },
        },
        {
          id: 'grid-input-field-readonly',
          type: 'Input',
          textResourceBindings: { title: 'My input field' },
          readOnly: true,
          dataModelBindings: { simpleBinding: 'GridExample.ExampleInput' },
        },
        {
          id: 'grid-radio-field-readonly',
          type: 'Input',
          textResourceBindings: { title: 'My radio field' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleRadio' },
          readOnly: true,
        },
        {
          id: 'grid-checkbox-field-readonly',
          type: 'Input',
          textResourceBindings: { title: 'My radio field' },
          dataModelBindings: { simpleBinding: 'GridExample.ExampleCheckbox' },
          readOnly: true,
        },
        {
          size: 'h3',
          id: 'GridPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { id: 'old-summary', type: 'Summary', componentRef: 'all-grid-components' },
        { id: 'old-summary-common-fields', type: 'Summary', componentRef: 'grid-example-common-fields' },
        {
          size: 'h3',
          id: 'GridPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        { id: 'new-summary', type: 'Summary2', target: { type: 'page', id: 'GridPage' } },
        { id: 'NavigationButtons-nkqJlY', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
      ],
    },
  },
  TabsPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'Tabs-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'TabsHeader', type: 'Header', textResourceBindings: { title: 'TabsPage' } },
        {
          id: 'TabsPageHeaderComponent',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'TabsPageTabsComponent',
          type: 'Tabs',
          defaultTab: 'tab2',
          tabs: [
            {
              id: 'tab1',
              title: 'Tab uten ikon',
              children: ['TabsPageParagraphComponent1', 'TabsPage-Address', 'TabsPage-Dropdown'],
            },
            {
              id: 'tab2',
              title: 'Default tab',
              children: ['TabsPageParagraphComponent2', 'TabsPage-RadioButtons', 'TabsPage-Textarea'],
            },
            {
              id: 'tab3',
              title: 'Tab med ikon',
              icon: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/svg.svg',
              children: ['TabsPageParagraphComponent3', 'TabsPage-Input', 'TabsPage-Input2'],
            },
          ],
        },
        {
          id: 'TabsPageParagraphComponent1',
          type: 'Paragraph',
          textResourceBindings: { title: 'Dette er en lorem ipsum tekst' },
        },
        {
          id: 'TabsPage-Address',
          type: 'Address',
          required: true,
          dataModelBindings: {
            address: 'street',
            zipCode: 'postnr',
            postPlace: 'city',
            careOf: 'co',
            houseNumber: 'streetnr',
          },
          simplified: false,
          saveWhileTyping: 400,
        },
        {
          id: 'TabsPage-Dropdown',
          type: 'Dropdown',
          dataModelBindings: { simpleBinding: 'dropdown' },
          textResourceBindings: { title: 'DropdownPage.Dropdown.title' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
        },
        {
          id: 'TabsPageParagraphComponent2',
          type: 'Paragraph',
          textResourceBindings: { title: 'Dette er en lorem ipsum tekst 123' },
        },
        {
          id: 'TabsPage-RadioButtons',
          dataModelBindings: { simpleBinding: 'radioButtonInput' },
          type: 'RadioButtons',
          textResourceBindings: { title: 'RadioButtonsPage.RadioButtons.title' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
        },
        {
          id: 'TabsPage-Textarea',
          dataModelBindings: { simpleBinding: 'longAnswerInput' },
          type: 'TextArea',
          textResourceBindings: { title: 'TextareaPage.Textarea.title' },
        },
        {
          id: 'TabsPageParagraphComponent3',
          type: 'Paragraph',
          textResourceBindings: { title: 'Dette er en lorem ipsum tekst' },
        },
        {
          id: 'TabsPage-Input',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.title' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          showValidations: ['All'],
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'TabsPage-Input2',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.title' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          showValidations: ['All'],
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'TabsPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
          size: 'h3',
        },
        { id: 'TabsPage-Summary', componentRef: 'TabsPageTabsComponent', type: 'Summary' },
        {
          id: 'TabsPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
          size: 'h3',
        },
        { id: 'TabsPage-Summary2', type: 'Summary2', target: { type: 'component', id: 'TabsPageTabsComponent' } },
        { id: 'TabsPage-NavigationButtons', type: 'NavigationButtons', showBackButton: true, textResourceBindings: {} },
      ],
    },
  },
  InputPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'InputPage-NavigationBar', type: 'NavigationBar' },
        { id: 'InputPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'InputPage' } },
        {
          id: 'InputPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'InputPage-Input',
          required: false,
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.title' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          showValidations: ['All'],
        },
        {
          id: 'InputPage-Input-grid1',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.Grid.title-1' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'InputPage-Input-grid2',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.Grid.title-2' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'InputPage-Input-long',
          type: 'Input',
          textResourceBindings: { title: 'InputPage.Input.Grid.title.long' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          required: false,
          grid: { innerGrid: { xs: 12, md: 6 } },
        },
        {
          id: 'InputPage-Header-Summary',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { id: 'InputPage-Summary', type: 'Summary', componentRef: 'InputPage-Input' },
        { id: 'InputPage-Summary-grid1', type: 'Summary', componentRef: 'InputPage-Input-grid1' },
        { id: 'InputPage-Summary-grid2', type: 'Summary', componentRef: 'InputPage-Input-grid2' },
        { id: 'InputPage-Summary-long', type: 'Summary', componentRef: 'InputPage-Input-long' },
        {
          id: 'InputPage-Header-Summary2',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        { id: 'InputPage-Summary2', type: 'Summary2', target: { type: 'component', id: 'InputPage-Input' } },
        {
          id: 'InputPage-Summary2-grid1',
          type: 'Summary2',
          target: { type: 'component', id: 'InputPage-Input-grid1' },
        },
        {
          id: 'InputPage-Summary2-grid2',
          type: 'Summary2',
          target: { type: 'component', id: 'InputPage-Input-grid2' },
        },
        {
          id: 'InputPage-Summary2-grid-long',
          type: 'Summary2',
          hideEmptyFields: true,
          target: { type: 'component', id: 'InputPage-Input-long' },
        },
        {
          id: 'Tekst-Fra-Eksternt-Api',
          type: 'Text',
          textResourceBindings: { title: 'Eksternt api' },
          value: ['externalApi', 'testId', 'details[0].id'],
          direction: 'vertical',
          grid: { xs: 6 },
        },
        {
          id: 'InputPage-NavigationButtons',
          type: 'NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
        },
      ],
    },
  },
  MapPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'MapPage-NavigationBar', type: 'NavigationBar' },
        { id: 'MapPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'MapPage' } },
        {
          id: 'MapPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'MapPage-MapComponent',
          type: 'Map',
          textResourceBindings: { title: 'MapPage.Map.title' },
          dataModelBindings: { simpleBinding: 'mapComponent' },
          zoom: 6,
          centerLocation: { latitude: 59.93080398894555, longitude: 10.8012469132984 },
        },
        { id: 'MapPage-Header-Summary', type: 'Header', size: 'h3', textResourceBindings: { title: 'Header.Summary' } },
        { id: 'MapPage-Summary', type: 'Summary', componentRef: 'MapPage-MapComponent' },
        {
          id: 'MapPage-Header-Summary2',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        { id: 'MapPage-Summary2', type: 'Summary2', target: { type: 'component', id: 'MapPage-MapComponent' } },
        { id: 'MapPage-NavigationButtons', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
      ],
    },
  },
  CardsPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'CardsPage-NavigationBar', type: 'NavigationBar' },
        { id: 'CardsPage-Header', type: 'Header', textResourceBindings: { title: 'CardsPage' }, size: 'h2' },
        {
          id: 'CardsPage-Cards',
          type: 'Cards',
          color: 'subtle',
          cards: [
            {
              title: 'Varemerke',
              description:
                'Dette er et eksempel på hvordan et varemerke kan se ut. Dette kan være en logo, et navn, en farge eller en kombinasjon av disse.',
              media: 'CardsPage-Image',
            },
            {
              title: 'Lydmerke',
              description:
                'Et lydmerke kan være en jingle, en melodi eller en annen lyd. Et opptak av at noen brøler firmanavnet ditt godtar vi ikke.',
              media: 'CardsPage-Audio',
            },
            {
              title: 'Videomerke',
              description:
                'Videomerker er en kombinasjon bilde og av og til lyd. Dette kan være en reklamefilm, en animasjon eller en annen type video.',
              media: 'CardsPage-Video',
            },
            {
              title: 'Andre',
              description:
                'Vi kan registrere alt mulig rart som et kjennemerke. Hvis du vil registere gode kaker, kryss av her så tar vi kontakt for prøvesmaking.',
              children: ['CardsPage-Cards-Checkboxes'],
            },
          ],
        },
        {
          id: 'CardsPage-Image',
          type: 'Image',
          textResourceBindings: { altTextImg: 'CardsPage-image-alt-text' },
          image: {
            align: 'center',
            width: '100%',
            src: { nb: 'assets/kitten.jpg', en: 'assets/kitten.jpg', nn: 'assets/kitten.jpg' },
          },
        },
        {
          id: 'CardsPage-Audio',
          type: 'Audio',
          textResourceBindings: { altText: 'CardsPage-Lydmerke-alt-text' },
          audio: {
            src: {
              nb: 'assets/xylophone_melody_sample.wav',
              en: 'assets/xylophone_melody_sample.wav',
              nn: 'assets/xylophone_melody_sample.wav',
            },
          },
        },
        {
          id: 'CardsPage-Video',
          type: 'Video',
          textResourceBindings: { altText: 'CardsPage-Videomerke-alt-text' },
          video: { src: { nb: 'assets/samplevideo.mov', en: 'assets/samplevideo.mov', nn: 'assets/samplevideo.mov' } },
        },
        {
          id: 'CardsPage-Cards-Checkboxes',
          type: 'Checkboxes',
          dataModelBindings: { simpleBinding: 'checkboxForCard' },
          options: [{ label: 'Jeg inviterer Patentstyret til å smake på kaker', value: true }],
        },
        {
          id: 'CardsPage-Number-Input',
          type: 'Input',
          textResourceBindings: { title: 'CardsPage-Number-Input' },
          dataModelBindings: { simpleBinding: 'anyNumber' },
          grid: { md: 6 },
        },
        {
          id: 'CardsPage-Percentage-Input',
          type: 'Input',
          textResourceBindings: { title: 'CardsPage-Percentage-Input' },
          dataModelBindings: { simpleBinding: 'numberPercentage' },
          grid: { md: 6 },
        },
        {
          id: 'CardsPage-number1',
          type: 'Number',
          textResourceBindings: { title: 'Total gjeld' },
          value: ['dataModel', 'anyNumber'],
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'CardsPage-number2',
          type: 'Number',
          textResourceBindings: { title: 'Statisk verdi som tall' },
          value: 2000,
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'CardsPage-number3',
          type: 'Number',
          textResourceBindings: { title: 'Kredittkort prosent', description: '', helpText: '' },
          value: ['dataModel', 'numberPercentage'],
          direction: 'horizontal',
          formatting: { unit: 'percent', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'CardsPage-number4',
          type: 'Number',
          textResourceBindings: {
            title: 'Statisk verdi med desimal',
            description: 'Dette er en beskrivelse',
            help: 'Dette er en helptext',
          },
          value: 20000.2,
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'CardsPage-number-Card',
          type: 'Cards',
          color: 'subtle',
          cards: [
            {
              title: 'Nummerkort',
              description: '',
              children: ['CardsPage-number1', 'CardsPage-number2', 'CardsPage-number3', 'CardsPage-number4'],
            },
          ],
        },
        {
          id: 'CardsPage-text1',
          type: 'Text',
          textResourceBindings: { title: 'Fornavn' },
          value: ['dataModel', 'shortAnswerInput'],
          grid: { xs: 6 },
        },
        {
          id: 'CardsPage-text2',
          type: 'Text',
          textResourceBindings: { title: 'Etternavn' },
          value: 'Mitt etternavn',
          grid: { xs: 6 },
        },
        {
          id: 'CardsPage-text3',
          type: 'Text',
          textResourceBindings: { title: 'Adresse' },
          value: 'Min adresse',
          grid: { xs: 6 },
        },
        {
          id: 'CardsPage-text4',
          type: 'Text',
          textResourceBindings: { title: 'Tekst' },
          value: 'Test',
          direction: 'vertical',
          grid: { xs: 6 },
        },
        {
          id: 'CardsPage-text5',
          type: 'Text',
          textResourceBindings: { title: 'Språk' },
          value: ['language'],
          direction: 'vertical',
          grid: { xs: 6 },
        },
        {
          id: 'CardsPage-text-Input',
          type: 'Input',
          textResourceBindings: { title: 'CardsPage-text-Input' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
        },
        {
          id: 'CardsPage-text-Card',
          type: 'Cards',
          color: 'subtle',
          cards: [
            {
              title: 'Tekstkort',
              description: '',
              children: ['CardsPage-text1', 'CardsPage-text2', 'CardsPage-text3', 'CardsPage-text4', 'CardsPage-text5'],
            },
          ],
        },
      ],
    },
  },
  ListPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'ListPage-NavigationBar', type: 'NavigationBar' },
        { id: 'ListPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'ListPage' } },
        {
          id: 'ListPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'ListPage-ListComponent',
          type: 'List',
          dataModelBindings: { name: 'list' },
          textResourceBindings: { title: 'ListPage.List.title' },
          bindingToShowInSummary: 'list',
          dataListId: 'people',
          tableHeaders: { name: 'Navn', age: 'Alder', profession: 'Yrke' },
          sortableColumns: ['age'],
          pagination: { alternatives: [5, 10], default: 5 },
          mapping: { Search: 'search' },
        },
        {
          id: 'ListPage-Header-Summary',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { id: 'ListPage-Summary', type: 'Summary', componentRef: 'ListPage-ListComponent' },
        {
          id: 'ListPage-Header-Summary2',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        { id: 'ListPage-Summary2', type: 'Summary2', target: { type: 'component', id: 'ListPage-ListComponent' } },
        { id: 'ListPage-NavigationButtons', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
      ],
    },
  },
  DropdownPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'DropdownPage-NavigationBar', type: 'NavigationBar' },
        { id: 'DropdownPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'RadioButtonsPage' } },
        {
          id: 'DropdownPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'DropdownPage-RadioButtons',
          type: 'Dropdown',
          dataModelBindings: { simpleBinding: 'dropdown' },
          textResourceBindings: { title: 'DropdownPage.Dropdown.title' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
          required: false,
        },
        {
          id: 'DropdownPage-Header-Summary',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { id: 'DropdownPage-Summary', type: 'Summary', componentRef: 'DropdownPage-RadioButtons', largeGroup: false },
        {
          id: 'DropdownPage-Header-Summary2',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'DropdownPage-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'DropdownPage-RadioButtons' },
        },
        {
          id: 'DropdownPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  TextPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'TextPage-NavigationBar', type: 'NavigationBar' },
        { id: 'TextPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'Text' } },
        {
          id: 'textWithoutLabel',
          type: 'Text',
          value: 'Dette er helt vanlig tekst uten noe merkelapp eller datamodell.',
        },
        { id: 'firstName', type: 'Text', textResourceBindings: { title: 'Fornavn' }, value: 'Espen' },
        { id: 'lastName', type: 'Text', textResourceBindings: { title: 'Etternavn' }, value: 'Askeladd' },
        {
          id: 'street',
          type: 'Text',
          textResourceBindings: { title: 'Gatenavn' },
          value: 'Testveien 23',
          direction: 'vertical',
        },
        {
          id: 'postPlace',
          type: 'Text',
          textResourceBindings: { title: 'Postnummer' },
          value: '0123',
          direction: 'vertical',
          grid: { xs: 6 },
        },
        {
          id: 'place',
          type: 'Text',
          textResourceBindings: { title: 'Sted' },
          value: 'Oslo',
          direction: 'vertical',
          grid: { xs: 6 },
        },
        { id: 'language', type: 'Text', textResourceBindings: { title: 'Språk' }, value: ['language'] },
        {
          type: 'Cards',
          id: 'person-Card',
          color: 'subtle',
          cards: [{ title: 'Person', description: '', children: ['firstName', 'lastName', 'language'] }],
          grid: { xs: 12, innerGrid: { xs: 6 } },
        },
        {
          type: 'Cards',
          id: 'address-Card',
          color: 'subtle',
          cards: [{ title: 'Adresse', description: '', children: ['street', 'postPlace', 'place'] }],
          grid: { xs: 12, innerGrid: { xs: 6 } },
        },
        { id: 'Text-NavigationButtons', type: 'NavigationButtons', showBackButton: true, textResourceBindings: {} },
      ],
    },
  },
  GroupPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'GroupPage-Header', type: 'Header', textResourceBindings: { title: 'GroupPage' } },
        {
          size: 'h3',
          id: 'GroupPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'GroupPage-Group',
          type: 'Group',
          groupingIndicator: 'indented',
          hidden: false,
          textResourceBindings: { title: 'Group.Title', description: 'Group.Description' },
          children: ['GroupPage-Group-Header', 'GroupPage-Input', 'GroupPage-Group-Nested'],
        },
        {
          id: 'GroupPage-PanelGroup',
          type: 'Group',
          textResourceBindings: { description: 'Panel group description' },
          groupingIndicator: 'panel',
          children: ['GroupPage-PanelGroup-Input1', 'GroupPage-PanelGroup-Input2', 'GroupPage-PanelGroup-Input3'],
        },
        {
          id: 'GroupPage-PanelGroup-Input1',
          type: 'Input',
          textResourceBindings: { title: 'Input 1' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          grid: { xs: 12, sm: 4 },
        },
        {
          id: 'GroupPage-PanelGroup-Input2',
          type: 'Input',
          textResourceBindings: { title: 'Input 2' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          grid: { xs: 12, sm: 4 },
        },
        {
          id: 'GroupPage-PanelGroup-Input3',
          type: 'Input',
          textResourceBindings: { title: 'Input 3' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          grid: { xs: 12, sm: 4 },
        },
        {
          size: 'h3',
          id: 'GroupPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { componentRef: 'GroupPage-Group', id: 'GroupPage-Summary', type: 'Summary' },
        { componentRef: 'GroupPage-PanelGroup', id: 'GroupPage-PanelGroup-Summary', type: 'Summary' },
        {
          size: 'h3',
          id: 'GroupPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'GroupPage-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'GroupPage-Group' },
        },
        {
          id: 'GroupPage-PanelGroup-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'GroupPage-PanelGroup' },
        },
        { id: 'NavigationButtons', showBackButton: true, textResourceBindings: {}, type: 'NavigationButtons' },
        {
          size: 'L',
          id: 'GroupPage-Group-Header',
          type: 'Header',
          textResourceBindings: { title: 'GroupPage-Group-Header.title' },
        },
        {
          id: 'GroupPage-Input',
          type: 'Input',
          textResourceBindings: { title: 'Required input field inside group' },
          dataModelBindings: { simpleBinding: 'shortAnswerInput' },
          required: false,
          showValidations: ['All'],
        },
        {
          id: 'GroupPage-Group-Nested',
          type: 'Group',
          groupingIndicator: 'indented',
          hidden: false,
          textResourceBindings: { description: 'Nested group description' },
          children: [
            'GroupPage-Nested-Header',
            'GroupPage-Nested-Input',
            'GroupPage-Nested-Input2',
            'GroupPage-Nested-Textarea',
            'GroupPage-Nested-Checkboxes',
            'GroupPage-Group-Nested-Nested',
          ],
        },
        {
          size: 'L',
          id: 'GroupPage-Nested-Header',
          type: 'Header',
          textResourceBindings: { title: 'I am a nested header' },
        },
        {
          dataModelBindings: { simpleBinding: 'nestedInput' },
          id: 'GroupPage-Nested-Input',
          type: 'Input',
          textResourceBindings: { title: 'I am input inside nested group' },
        },
        {
          dataModelBindings: { simpleBinding: 'nestedInput2' },
          id: 'GroupPage-Nested-Input2',
          type: 'Input',
          textResourceBindings: { title: 'I am nested input 2' },
        },
        {
          dataModelBindings: { simpleBinding: 'longAnswerInput' },
          id: 'GroupPage-Nested-Textarea',
          type: 'TextArea',
          textResourceBindings: { title: 'TextareaPage.Textarea.title' },
        },
        {
          dataModelBindings: { simpleBinding: 'checkboxesInput' },
          id: 'GroupPage-Nested-Checkboxes',
          type: 'Checkboxes',
          textResourceBindings: { title: 'CheckboxesPage.Checkboxes.title' },
          options: [
            { label: 'Kjøre til hytta på fjellet', value: 'kjoreTilHyttaPaaFjellet' },
            { label: 'Kjøring i skogen', value: 'kjoringISkogen' },
            { label: 'Korte strekninger med bykjøring, eller annen moro', value: 'korteStrekningerMedBykjoring' },
            { label: 'Lange strekninger på større veier i Norge', value: 'langeStrekningerPaStorreVeierINorge' },
          ],
          required: false,
        },
        {
          id: 'GroupPage-Group-Nested-Nested',
          type: 'Group',
          groupingIndicator: 'indented',
          hidden: false,
          textResourceBindings: {
            title: 'Nested group title inside nested group',
            description: 'Nested nested group description inside nested group',
          },
          children: ['GroupPage-Nested-Nested-Input', 'GroupPage-Nested-Nested-RadioButtons'],
        },
        {
          dataModelBindings: { simpleBinding: 'nestedInput3' },
          id: 'GroupPage-Nested-Nested-Input',
          type: 'Input',
          textResourceBindings: { title: 'I am input inside nested group inside nested group' },
        },
        {
          dataModelBindings: { simpleBinding: 'radioButtonInput' },
          id: 'GroupPage-Nested-Nested-RadioButtons',
          type: 'RadioButtons',
          textResourceBindings: { title: 'RadioButtonsPage.RadioButtons.title' },
          options: [
            { label: 'Bil', value: 'bil' },
            { label: 'Moped', value: 'moped' },
            { label: 'Traktor', value: 'traktor' },
            { label: 'Båt', value: 'baat' },
          ],
          required: false,
        },
      ],
    },
  },
  AddressPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      layout: [
        { id: 'AddressPage-NavigationBar', type: 'NavigationBar' },
        { size: 'h2', id: 'AddressPage-Header', type: 'Header', textResourceBindings: { title: 'AddressPage' } },
        {
          size: 'h3',
          id: 'AddressPage-Header-Component',
          type: 'Header',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          dataModelBindings: {
            address: 'street',
            zipCode: 'postnr',
            postPlace: 'city',
            careOf: 'co',
            houseNumber: 'streetnr',
          },
          simplified: false,
          saveWhileTyping: 400,
          id: 'AddressPage-Address',
          type: 'Address',
          required: true,
        },
        {
          size: 'h3',
          id: 'AddressPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { componentRef: 'AddressPage-Address', id: 'AddressPage-Summary', type: 'Summary', largeGroup: false },
        {
          size: 'h3',
          id: 'AddressPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'AddressPage-Summary2',
          type: 'Summary2',
          hideEmptyFields: true,
          hidden: false,
          target: { type: 'component', id: 'AddressPage-Address' },
        },
        {
          id: 'AddressPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
  NumberPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'NumberPage-NavigationBar', type: 'NavigationBar' },
        { id: 'NumberPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'Number' } },
        {
          id: 'totalDebt',
          type: 'Input',
          dataModelBindings: { simpleBinding: 'Numbers.TotalGjeld' },
          textResourceBindings: { title: 'Total Gjeld' },
          formatting: { currency: 'NOK' },
          grid: { xs: 6 },
        },
        {
          id: 'creditPercentage',
          type: 'Input',
          dataModelBindings: { simpleBinding: 'Numbers.Gjeldsfordeling.Prosent' },
          textResourceBindings: { title: 'Kredittkort prosent' },
          formatting: { unit: 'percent' },
          grid: { xs: 6 },
        },
        {
          id: 'number1',
          type: 'Number',
          textResourceBindings: { title: 'Total gjeld' },
          value: ['dataModel', 'Numbers.TotalGjeld'],
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'number2',
          type: 'Number',
          textResourceBindings: { title: 'Statisk verdi som tall' },
          value: 2000,
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'number3',
          type: 'Number',
          textResourceBindings: { title: 'Kredittkort prosent', description: '', helpText: '' },
          value: ['dataModel', 'Numbers.Gjeldsfordeling.Prosent'],
          direction: 'horizontal',
          formatting: { unit: 'percent', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          id: 'number4',
          type: 'Number',
          textResourceBindings: {
            title: 'Statisk verdi med desimal',
            description: 'Dette er en beskrivelse',
            help: 'Dette er en helptext',
          },
          value: 20000.2,
          direction: 'horizontal',
          formatting: { currency: 'NOK', position: 'suffix', number: { thousandSeparator: ' ' } },
          grid: { xs: 12 },
        },
        {
          type: 'Cards',
          id: 'number-Card',
          color: 'subtle',
          cards: [{ title: 'Nummerkort', description: '', children: ['number1', 'number2', 'number3', 'number4'] }],
        },
        { id: 'Number-NavigationButtons', type: 'NavigationButtons', showBackButton: true, textResourceBindings: {} },
      ],
    },
  },
  LikertPage: {
    $schema: 'https://altinncdn.no/toolkits/altinn-app-frontend/4/schemas/json/layout/layout.schema.v1.json',
    data: {
      hidden: false,
      layout: [
        { id: 'LikertPage-NavigationBar', type: 'NavigationBar' },
        { id: 'LikertPage-Header', type: 'Header', size: 'h2', textResourceBindings: { title: 'LikertPage' } },
        {
          id: 'LikertPage-Header-Component',
          type: 'Header',
          size: 'h3',
          textResourceBindings: { title: 'Header.Component' },
        },
        {
          id: 'LikertPage-Likert',
          type: 'Likert',
          textResourceBindings: {
            title: 'Skolearbeid',
            description: 'På de neste spørsmålene skal du svare i kontekst av klasserommet.',
            leftColumnHeader: 'Spørsmål',
            questions: 'likert-row-title',
          },
          dataModelBindings: { questions: 'LikertExample', answer: 'LikertExample.Answer' },
          filter: [
            { key: 'start', value: '0' },
            { key: 'stop', value: '3' },
          ],
          optionsId: 'likertOptions',
        },
        {
          size: 'h3',
          id: 'LikertPage-Header-Summary',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary' },
        },
        { id: 'LikertPage-Summary', type: 'Summary', componentRef: 'LikertPage-Likert' },
        {
          size: 'h3',
          id: 'LikertPage-Header-Summary2',
          type: 'Header',
          textResourceBindings: { title: 'Header.Summary2' },
        },
        {
          id: 'LikertPage-Summary2',
          type: 'Summary2',
          hidden: false,
          target: { type: 'component', id: 'LikertPage-Likert' },
        },
        {
          id: 'LikertPage-NavigationButtons',
          showBackButton: true,
          textResourceBindings: {},
          type: 'NavigationButtons',
        },
      ],
    },
  },
};
