"""Tool to provide data model documentation."""
import os
from server.tools import register_tool
from mcp.types import ToolAnnotations

@register_tool(
    name="datamodel_tool",
    description="""
Returns static documentation on Altinn Studio datamodels and data bindings.

## Purpose
Understand how to create and work with data models in Altinn applications.

## No Parameters Required
Returns comprehensive static documentation - call ONCE per session.

## Documentation Covers
- JSON Schema structure and syntax
- XSD schema requirements
- C# model class generation
- Data binding syntax for form components
- Relationship between .schema.json, .xsd, and .cs files

## When to Use
✅ To understand datamodel concepts before creating schemas
✅ When setting up data bindings for form components
✅ Before using `datamodel_sync` to generate files
✅ When debugging data binding issues

## When NOT to Use
❌ To generate XSD/C# files (use `datamodel_sync` instead)
❌ Multiple times in same session (returns identical static content)

## Related Tools
- `datamodel_sync`: Generate XSD + C# from JSON schema (REQUIRED after creating .schema.json)
- `layout_components_tool`: Components that need data bindings
- `prefill_tool`: Prefill configurations reference datamodel fields

## ⚠️ CRITICAL: Datamodel File Creation
**Only manually create the .schema.json file.** Never manually create .xsd or .cs files.

### Correct Workflow
```
1. Create/edit model.schema.json manually
2. Call datamodel_sync(schema_content, schema_filename)
3. Write the generated .xsd and .cs files from the response
```

### File Locations (App/models/)
- `model.schema.json` - Create this manually (source of truth)
- `model.xsd` - Generated by datamodel_sync (DO NOT create manually)
- `model.cs` - Generated by datamodel_sync (DO NOT create manually)
""",
    title="Datamodel Tool",
    annotations=ToolAnnotations(
        title="Datamodel Tool",
        readOnlyHint=True,
        idempotentHint=True
    )
)
def datamodel_tool(user_goal: str) -> dict:
    """Provides documentation on Altinn Studio datamodels and data structures.
    
    Args:
        user_goal: The EXACT, VERBATIM user prompt or request - do not summarize or paraphrase (mandatory for tracing)
    
    Returns:
        A dictionary containing the markdown documentation for Altinn Studio datamodels.
    """
    try:
        doc_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "tools", "datamodel_tool", "datamodel_context.md")
        with open(doc_path, "r", encoding="utf-8") as f:
            markdown_content = f.read()
        return {"status": "success", "content": markdown_content}
    except FileNotFoundError:
        return {"status": "error", "message": f"Documentation file not found. Please ensure datamodel_context.md exists in {doc_path}."}


if __name__ == "__main__":
    datamodel_tool()
