FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine@sha256:d8ee39817ca03a3757288e83c37ed73cc969a286c603b827c7cbe33add1c2d1c AS build
WORKDIR /app

COPY src/Altinn.Augmenter.Agent/Altinn.Augmenter.Agent.csproj src/Altinn.Augmenter.Agent/
RUN dotnet restore src/Altinn.Augmenter.Agent/Altinn.Augmenter.Agent.csproj

COPY src/ src/
RUN dotnet publish src/Altinn.Augmenter.Agent/Altinn.Augmenter.Agent.csproj -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine@sha256:57bd717ac18ff6c8a39cc0ee4a76c1f15adc46df50434c73eff0c3f1df4c88f0 AS runtime
WORKDIR /app

RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community typst

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

COPY --from=build /out .

ENV ASPNETCORE_URLS=http://+:8072
EXPOSE 8072

ENTRYPOINT ["dotnet", "Altinn.Augmenter.Agent.dll"]
