apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberneteswrapper.serviceName" . }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ include "kuberneteswrapper.serviceExternalPort" . }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
