// <auto-generated/>

using System;

namespace AltinnCoreServiceImplementation.tdd.xyz23
{
    public class InstantiationHandler
    {
        public InstantiationHandler()
        {
        }

        public void Instansiate(Skjema Skjema)
        {

        }

    }
}
