import AltinnInformationCard from '../../../shared/src/components/AltinnInformationCard';
import uieditorApp from '../../../ux-editor/src/SubApp';
import HandleMergeConflictContainer from '../features/handleMergeConflict/HandleMergeConflictContainer';

export const routes = [
  {
    path: '/uieditor',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'GUI',
    menu: 'create',
    subapp: uieditorApp,
  },
  {
    path: '/preview',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    menu: 'create',
    subapp: uieditorApp,
  },
  {
    path: '/text',
    exact: true,
    activeSubHeaderSelection: 'Språk',
    activeLeftMenuSelection: 'Tekst',
    menu: 'language',
    subapp: AltinnInformationCard,
  },
  {
    path: '/test',
    exact: true,
    activeSubHeaderSelection: 'Teste',
    activeLeftMenuSelection: 'Test',
    menu: 'test',
    subapp: AltinnInformationCard,
  },
  {
    path: '/aboutservice',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Om tjenesten',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/rolesandrights',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Roller og rettigheter',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/production',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Produksjon',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/versionhistory',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Versjonshistorikk',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/aboutenduser',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Om sluttbrukeren',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/altinn',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Altinn',
    menu: 'about',
    subapp: AltinnInformationCard,
  },
  {
    path: '/datamodel',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'Datamodell',
    menu: 'create',
    subapp: AltinnInformationCard,
  },
  {
    path: '/api',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'API',
    menu: 'create',
    subapp: AltinnInformationCard,
  },
  {
    path: '/translate',
    exact: true,
    activeSubHeaderSelection: 'Språk',
    activeLeftMenuSelection: 'Flere språk',
    menu: 'language',
    subapp: AltinnInformationCard,
  },
  {
    path: '/productionsetting',
    exact: true,
    activeSubHeaderSelection: 'Publisere',
    activeLeftMenuSelection: 'Produksjonsette',
    menu: 'publish',
    subapp: AltinnInformationCard,
  },
  {
    path: '/status',
    exact: true,
    activeSubHeaderSelection: 'Publisere',
    activeLeftMenuSelection: 'Status',
    menu: 'publish',
    subapp: AltinnInformationCard,
  },
  {
    path: '/designSystem',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'GUI',
    menu: 'create',
    subapp: AltinnInformationCard,
  },
  {
    path: '/mergeconflict',
    exact: true,
    activeSubHeaderSelection: '',
    activeLeftMenuSelection: 'Mergekonflikt',
    menu: 'about',
    subapp: HandleMergeConflictContainer,
  },
];
