import AltinnInformationCard from '../../../shared/src/components/AltinnInformationCard';
import uieditorApp from '../../../ux-editor/src/SubApp';
import { Administration } from '../features/administration/components/Administration';
import HandleMergeConflictContainer from '../features/handleMergeConflict/HandleMergeConflictContainer';
import { IFrame } from '../features/iFrame/iFrameComponent';
import RedirectComponent from '../features/iFrame/RedirectComponent';
import TestingInTestenvironmentContainer from '../features/testing-in-testenvironment/testing-in-testenvironment';

export const routes = [
  {
    path: '/uieditor',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'GUI',
    menu: 'create',
    subapp: uieditorApp,
  },
  {
    path: '/preview',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    menu: 'create',
    subapp: uieditorApp,
  },
  {
    path: '/text',
    exact: true,
    activeSubHeaderSelection: 'Språk',
    activeLeftMenuSelection: 'Tekst',
    menu: 'language',
    subapp: IFrame,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
      iframeEndingUrl: 'Text',
    },
  },
  {
    path: '/test',
    exact: true,
    activeSubHeaderSelection: 'Teste',
    activeLeftMenuSelection: 'Test',
    menu: 'test',
    subapp: RedirectComponent,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
      redirectUrl: 'runtime/ManualTesting/Users/',
    },
  },
  {
    path: '/testingintestenvironment',
    exact: true,
    activeSubHeaderSelection: 'Teste',
    activeLeftMenuSelection: 'Test i testmiljø',
    menu: 'test',
    subapp: TestingInTestenvironmentContainer,
  },
  {
    path: '/aboutservice',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Om tjenesten',
    menu: 'about',
    subapp: Administration,
  },
  {
    path: '/rolesandrights',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Roller og rettigheter',
    menu: 'about',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/production',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Produksjon',
    menu: 'about',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/versionhistory',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Versjonshistorikk',
    menu: 'about',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/aboutenduser',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Om sluttbrukeren',
    menu: 'about',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/altinn',
    exact: true,
    activeSubHeaderSelection: 'Om',
    activeLeftMenuSelection: 'Altinn',
    menu: 'about',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/datamodel',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'Datamodell',
    menu: 'create',
    subapp: IFrame,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
      iframeEndingUrl: 'Model',
    },
  },
  {
    path: '/api',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'API',
    menu: 'create',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/code',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'Kode',
    menu: 'create',
    subapp: IFrame,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
      iframeEndingUrl: 'Rules/Code',
    },
  },
  {
    path: '/translate',
    exact: true,
    activeSubHeaderSelection: 'Språk',
    activeLeftMenuSelection: 'Flere språk',
    menu: 'language',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/publish',
    exact: true,
    activeSubHeaderSelection: 'Publisere',
    activeLeftMenuSelection: 'Produksjonsette',
    menu: 'publish',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
      iframeEndingUrl: 'Deploy',
    },
  },
  {
    path: '/status',
    exact: true,
    activeSubHeaderSelection: 'Publisere',
    activeLeftMenuSelection: 'Status',
    menu: 'publish',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/designsystem',
    exact: true,
    activeSubHeaderSelection: 'Lage',
    activeLeftMenuSelection: 'GUI',
    menu: 'create',
    subapp: AltinnInformationCard,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
  {
    path: '/mergeconflict',
    exact: true,
    activeSubHeaderSelection: '',
    activeLeftMenuSelection: 'Mergekonflikt',
    menu: '',
    subapp: HandleMergeConflictContainer,
    props: {
      headerTextKey: 'shared.wip_title',
      subtext1TextKey: 'shared.wip_subtext_1',
      subtext2TextKey: 'shared.wip_subtext_2',
      linkTextKey: 'shared.wip_link_text',
      urlKey: 'shared.wip_link_github_url',
      imageSource: '../../designer/img/illustration-help-circle.svg',
      shadow: true,
    },
  },
];
