name: App Libraries - Unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'app-libs/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/app-libs-unit-test.yml'
      - '!**/AGENTS.md'
      - '!**/CLAUDE.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    runs-on: self-hosted-single
    timeout-minutes: 30
    name: Unit tests
    defaults:
      run:
        working-directory: app-libs/
    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          persist-credentials: false

      - name: install node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '22'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --immutable

      - name: type-check
        run: yarn typecheck

      - name: run eslint
        run: yarn lint

      - name: run tests
        run: yarn test:ci
        # TODO : Run with coverage (yarn test:ci --coverage ?)
