name: App Backend - Verify formatting

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/backend/**'
      - '.github/workflows/app-backend-formatting.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify-no-changes:
    if: |
      github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: src/App/backend/

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          global-json-file: src/App/backend/global.json
      - name: Install csharpier
        run: dotnet tool restore
      - name: Run csharpier
        run: dotnet csharpier check .
