name: App Frontend - Unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'src/App/frontend/src/**'
      - 'src/App/frontend/package.json'
      - '.github/workflows/app-frontend-unit-tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Type-checks, eslint, unit tests and SonarCloud
    defaults:
      run:
        working-directory: src/App/frontend/
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: install node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '22'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --immutable

      - name: type-check
        run: yarn tsc

      - name: type-check-strict
        run: |
          strict_error_count="$(yarn tsc-strict:error-count)"
          echo "Strict TypeScript error count: ${strict_error_count}"

          if (( strict_error_count >= 301 )); then
            echo "Strict TypeScript error count is ${strict_error_count}, expected less than 301."
            exit 1
          fi

      - name: run eslint
        run: yarn lint

      - name: run tests
        run: yarn test --coverage

      # TODO: consider for removal?
      # - name: SonarCloud Scan
      #   if: |
      #     github.repository_owner == 'Altinn' &&
      #     (github.event_name != 'pull_request' && github.event.repository.fork == false) ||
      #     (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
      #   with:
      #     projectBaseDir: src/App/frontend/
      #   uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
