name: App Backend - Verify formatting

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/backend/**'
      - '.github/workflows/app-backend-formatting.yml'
      - '!**/AGENTS.md'
      - '!**/CLAUDE.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify-no-changes:
    if: |
      github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: self-hosted-ubuntu
    timeout-minutes: 5
    defaults:
      run:
        working-directory: src/App/backend/

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: src/App/backend/global.json
      - name: Install csharpier
        run: dotnet tool restore
      - name: Run csharpier
        run: dotnet csharpier check .
