name: Construct Environments Script - Test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - ".github/scripts/construct-environments.mjs"
      - ".github/scripts/construct-environments.test.mjs"
      - ".github/workflows/construct-environments-script-test.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    name: Run node tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          sparse-checkout: |
            .github/scripts

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "22"
          package-manager-cache: false

      - name: Test construct environments script
        run: node --test .github/scripts/construct-environments.test.mjs
