name: Deployer - Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/tools/deployer/**'
      - '.github/workflows/deployer-check.yaml'
  workflow_dispatch:

jobs:
  check:
    name: Run make check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tools/deployer
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '22'

      - name: Run checks
        run: make check
