name: Admin - deploy workflow-engine-tenant-db-template

on:
  push:
    branches:
      - main
      - feat/admin-syncroot
    paths:
      - infra/admin/workflow-engine-tenant-db-template/**
      - .github/workflows/deploy-admin-workflow-engine-tenant-db-template.yaml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  push-workflow-engine-tenant-db-template-artifact:
    name: Push workflow-engine-tenant-db-template as OCI artifact
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      short-sha: ${{ steps.vars.outputs.short-sha }}
    defaults:
      run:
        working-directory: ./infra/admin
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set vars
        id: vars
        run: echo "short-sha=${GITHUB_SHA::10}" >> "$GITHUB_OUTPUT"

      - name: az login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}

      - name: az acr login
        run: az acr login --name altinncr

      - name: flux install
        uses: fluxcd/flux2/action@bfa461ed2153ae5e0cca6bce08e0845268fb3088 # v2.8.2

      - name: push tenant-db-template artifact
        run: |
          cd workflow-engine-tenant-db-template/
          flux push artifact oci://altinncr.azurecr.io/studio/workflow-engine-tenant-db-template:${{ steps.vars.outputs.short-sha }} \
            --provider=generic \
            --reproducible \
            --path="." \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

  tag-workflow-engine-tenant-db-template:
    name: Tag workflow-engine-tenant-db-template (${{ matrix.tag }})
    needs: push-workflow-engine-tenant-db-template-artifact
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: test
            environment: adminservices_test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: az login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}

      - name: az acr login
        run: az acr login --name altinncr

      - name: flux install
        uses: fluxcd/flux2/action@bfa461ed2153ae5e0cca6bce08e0845268fb3088 # v2.8.2

      - name: tag tenant-db-template artifact
        run: |
          flux tag artifact oci://altinncr.azurecr.io/studio/workflow-engine-tenant-db-template:${{ needs.push-workflow-engine-tenant-db-template-artifact.outputs.short-sha }} \
            --tag ${{ matrix.tag }}
