name: Designer Backend - Gitea and Db integration tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'src/Designer/backend/**'
      - 'src/Designer/testdata/**'
      - 'src/Designer/development/fake-ansattporten/**'
      - 'src/gitea/**'
      - '.github/workflows/designer-backend-gitea-and-db-integration-tests.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gitea-and-db-integration-tests:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    name: Run integration tests against actual gitea and dbs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: |
            9.0.x
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Build
        run: |
           dotnet build backend/Designer.sln -v m
        working-directory: src/Designer

      - name: Run integration tests
        run: |
           dotnet test backend/Designer.sln --filter "(Category=GiteaIntegrationTest)|(Category=StudioOidcGiteaIntegrationTest)|(Category=DbIntegrationTest)" -v m
        working-directory: src/Designer
