name: Designer Backend - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'src/common/dotnet/**'
      - 'src/Designer/backend/**'
      - 'src/Designer/testdata/**'
      - 'src/Designer/development/fake-ansattporten/**'
      - 'src/App/template/**'
      - 'src/gitea/**'
      - '.github/workflows/designer-backend-dotnet-test.yaml'
      - '!**/AGENTS.md'
      - '!**/CLAUDE.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  analyze:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    name: Run dotnet build and test
    runs-on: ${{ matrix.os == 'ubuntu-latest' && 'self-hosted-ubuntu' || matrix.os }}
    timeout-minutes: 30
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Enable long paths for git on Windows
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: src/Designer/backend/global.json
      - name: Build
        run: |
          dotnet build Designer.sln -v m
        working-directory: src/Designer/backend
      - name: Test
        run: |
          dotnet test Designer.sln --filter "(Category!=StudioOidcGiteaIntegrationTest)&(Category!=DbIntegrationTest)" -v m --no-build
        working-directory: src/Designer/backend
        env:
          DOTNET_gcServer: 1
          DOTNET_GCConserveMemory: 1

  gitea-and-db-integration-tests:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    name: Run integration tests against actual gitea and dbs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: src/Designer/backend/global.json

      - name: Build
        run: |
          dotnet build Designer.sln -v m
        working-directory: src/Designer/backend

      - name: Run integration tests
        run: |
          dotnet test Designer.sln --filter "(Category=StudioOidcGiteaIntegrationTest)|(Category=DbIntegrationTest)" -v m --no-build
        working-directory: src/Designer/backend
