name: Designer Backend - Ensure Migrations Compatibility

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'src/Designer/backend/**'
      - '.github/workflows/designer-backend-dotnet-migrations-ensure-compatibility.yaml'
      - '!**/AGENTS.md'
      - '!**/CLAUDE.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ensure-migrations-compatibility:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    name: Try to generate script and to add a new migrations
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OidcLoginSettings__FetchClientIdAndSecretFromRootEnvFile: 'false'
      OidcLoginSettings__ClientId: 'dummyRequired'
      OidcLoginSettings__ClientSecret: 'dummyRequired'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: src/Designer/backend/global.json

      - name: Install dotnet ef # Version should be the same as Migrations docker file and project
        run: dotnet tool install --version 10.0.10 --global dotnet-ef

      - name: Build Designer backend
        run: |
            dotnet restore src/Designer/Designer.csproj
            dotnet build src/Designer/Designer.csproj --no-restore
        working-directory: src/Designer/backend

      - name: Check if migrations script can be generated
        run: |
            dotnet ef migrations script --project src/Designer --no-build
        working-directory: src/Designer/backend

      - name: Check if it's possible to add a new migration
        run: |
            dotnet ef migrations add Test --project src/Designer --no-build
        working-directory: src/Designer/backend
