name: Verify dotnet format

on:
  pull_request:

jobs:
  verify-no-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Install csharpier
      run: dotnet tool restore
    - name: Run csharpier
      run: dotnet csharpier check .
