name: Library Form Component - Unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'libs/form-component/src/**'
      - 'libs/form-component/package.json'
      - 'libs/form-component/tsconfig.json'
      - 'libs/form-component/vitest.config.ts'
      - '.github/workflows/libs-form-component-unit-tests.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Unit tests
    defaults:
      run:
        working-directory: libs/form-component/
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          persist-credentials: false

      - name: install node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '22'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --immutable

      - name: type-check
        run: yarn typecheck

      todo:
      - name: run eslint
        run: yarn lint

      - name: run tests
        run: yarn test
        # TODO : Run with coverage (yarn test --coverage ?)
