name: Repositories Scan

on:
  schedule:
  - cron: '0 8 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Build the Docker image
      run: docker build ./gitea --tag altinn-repos:${{github.sha}}

    - uses: Azure/container-scan@f9af925b897d8af5f7e0026b8bca9346261abc93 # v0.1
      env:
        # See https://github.com/goodwithtech/dockle/issues/188
        DOCKLE_HOST: "unix:///var/run/docker.sock"
      with:
        image-name: altinn-repos:${{github.sha}}
