name: Runtime Workflow Engine App - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - 'src/common/**'
      - 'src/Runtime/workflow-engine/src/**'
      - 'src/Runtime/workflow-engine/tests/**'
      - 'src/Runtime/workflow-engine/Directory.Build.props'
      - 'src/Runtime/workflow-engine/Directory.Packages.props'
      - 'src/Runtime/workflow-engine-app/src/**'
      - 'src/Runtime/workflow-engine-app/tests/**'
      - 'src/Runtime/workflow-engine-app/Directory.Build.props'
      - 'src/Runtime/workflow-engine-app/Directory.Packages.props'
      - 'src/Runtime/workflow-engine-app/typos.toml'
      - '.github/workflows/runtime-workflow-engine-app-tests.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: src/Runtime/workflow-engine-app/
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Spell check
        uses: crate-ci/typos@7c572958218557a3272c2d6719629443b5cc26fd # v1.45.2
        with:
          config: src/Runtime/workflow-engine-app/typos.toml
          files: src/Runtime/workflow-engine-app

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: |
            10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        env:
          CI: true

      - name: Test
        run: dotnet test --no-build
