name: Localtest - Build

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft, closed]
    paths:
      - '.github/workflows/runtime-localtest-build.yml'
      - 'src/Runtime/common/dotnet/**'
      - 'src/Runtime/localtest/**'
      - '!**/AGENTS.md'
      - '!**/CLAUDE.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && !github.event.pull_request.draft) }}
    runs-on: self-hosted-ubuntu
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: src/Runtime/localtest/global.json
      - name: Install dependencies
        run: dotnet restore
        working-directory: 'src/Runtime/localtest/src/'
      - name: Build LocalTest
        run: dotnet build --configuration Debug --no-restore
        working-directory: 'src/Runtime/localtest/src/'
