name: Runtime kubernetes-wrapper - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Runtime/kubernetes-wrapper/**'
      - '.github/workflows/runtime-kubernetes-wrapper-build.yaml'
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: src/Runtime/kubernetes-wrapper

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: src/Runtime/kubernetes-wrapper/go.mod
          cache-dependency-path: src/Runtime/kubernetes-wrapper/go.sum

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        env:
          UPDATE_SNAPS: "false"
        run: make test
