# Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:0.9.7-python3.12-bookworm-slim@sha256:4f52717de41541452f5318571b05da783d2ddf346a94b4d5c6512a4b51e986bd

WORKDIR /app

COPY pyproject.toml ./
COPY uv.lock ./

RUN uv sync --locked --no-dev --no-install-project

COPY codegen/ ./codegen/
COPY server/ ./server/
COPY scripts/ ./scripts/

EXPOSE 8069

ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

CMD ["python", "-m", "server.main"]
