<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="../Directory.Build.props" />
  <Import Project="$(MSBuildThisFileDirectory)../../PackageVersioning.props" />

  <ItemGroup>
    <PackageReference Include="Nullable.Extended.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <None Include="../../README.md" Link="README.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)../../../../LICENSE" Link="LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

  <Target Name="PreparePackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec">
    <ReadLinesFromFile File="../../RELEASE_NOTES.md">
      <Output TaskParameter="Lines" ItemName="ReleaseNoteLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <PackageReleaseNotes>@(ReleaseNoteLines, '%0a')</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

  <PropertyGroup>
    <AnalysisMode>Recommended</AnalysisMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <RepoRoot>$([System.IO.Directory]::GetParent($(MSBuildThisFileDirectory)).Parent.FullName)</RepoRoot>
    <PackageVersionTagPrefix>app/v</PackageVersionTagPrefix>
    <PackageDefaultBaseVersion>9.0.0-preview.0</PackageDefaultBaseVersion>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Altinn Platform Contributors</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Altinn/app-lib-dotnet</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseExperimentalPackageId)' == ''">
    <UseExperimentalPackageId>false</UseExperimentalPackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseExperimentalPackageId)' == 'true'">
    <PackageId>$(MSBuildProjectName).Experimental</PackageId>
  </PropertyGroup>

  <ItemGroup Condition="'$(Deterministic)'=='true'">
    <SourceRoot Include="$(MSBuildThisFileDirectory)/" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Deterministic)'=='true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
