const moduleName = 'TEXT_RESOURCES';

export const REPLACE_TEXT_RESOURCES = `${moduleName}.REPLACE_TEXT_RESOURCES`;
export const REPLACE_TEXT_RESOURCES_FULFILLED = `${moduleName}.REPLACE_TEXT_RESOURCES_FULFILLED`;
export const REPLACE_TEXT_RESOURCES_REJECTED = `${moduleName}.REPLACE_TEXT_RESOURCES_REJECTED`;
